/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
/* The HTML the console sends is generated by its own macros under Jinja autoescaping, so it holds no scripts, inline styles or event
   handlers. This is the second line of defence (ELEMENTS.md section 10): everything is parsed inertly and rebuilt from an allow-list of
   elements and attributes, then handed to the DOM through one Trusted Types policy, `drishti-elements`, so a host that enforces
   `require-trusted-types-for 'script'` adds `trusted-types drishti-elements` and nothing else. */
import { API } from './config.js';

const TAGS = new Set(('a abbr article aside b br button caption circle code col colgroup dd details div dl dt em figcaption figure form g h1 h2 h3 h4 h5 h6 '
  + 'header hr i input kbd label li mark nav ol option p path pre section select small span strong sub summary sup svg table tbody td text tfoot th thead '
  + 'time tr tspan ul line polyline polygon rect ellipse title').split(' '));
const DROP = new Set(['script', 'style', 'iframe', 'frame', 'frameset', 'object', 'embed', 'applet', 'link', 'meta', 'base', 'noscript', 'template',
  'foreignobject', 'use', 'animate', 'set', 'audio', 'video', 'source', 'img', 'image', 'textarea']);
const ATTRS = new Set(('class id role title href target rel type name value placeholder for colspan rowspan scope headers tabindex hidden disabled '
  + 'checked selected open datetime maxlength autocomplete lang dir focusable viewbox d cx cy r rx ry x y x1 x2 y1 y2 width height points fill stroke '
  + 'stroke-width stroke-linecap stroke-linejoin transform opacity text-anchor').split(' '));
const SAFE_URL = /^(?:\/(?!\/)|#|\.\/|https?:|mailto:)/i;

function clean(node) {
  for (const child of [...node.childNodes]) {
    if (child.nodeType === 8) { child.remove(); continue; }                         // comments
    if (child.nodeType !== 1) { continue; }
    const tag = child.localName.toLowerCase();
    if (DROP.has(tag)) { child.remove(); continue; }                                // dangerous: with its content
    clean(child);
    if (!TAGS.has(tag)) { child.replaceWith(...child.childNodes); continue; }       // unknown: keep what is inside, not the element
    for (const a of [...child.attributes]) {
      const n = a.name.toLowerCase();
      const ok = (ATTRS.has(n) || n.startsWith('data-') || n.startsWith('aria-')) && !n.startsWith('on');
      if (!ok) { child.removeAttribute(a.name); continue; }
      if (n === 'href' && !SAFE_URL.test(a.value.replace(/[\u0000- ]/g, ''))) { child.removeAttribute(a.name); }   // javascript:, data:, vbscript:
    }
    if (tag === 'form') { child.removeAttribute('action'); }
  }
}

let policy = null;
function serialise(raw) {
  const t = document.createElement('template');
  t.innerHTML = raw;
  clean(t.content);
  return t.innerHTML;
}
try {
  if (window.trustedTypes && window.trustedTypes.createPolicy) {
    // createHTML(s, 'raw') hands the parser an unsanitised value to parse; the one policy does both steps, so a host lists one name
    policy = window.trustedTypes.createPolicy('drishti-elements', {
      createHTML: (s, mode) => (mode === 'raw' ? s : serialise(policy.createHTML(s, 'raw'))),
      createScriptURL: (u) => {
        if (new URL(u, document.baseURI).pathname.startsWith(API + '/')) { return u; }       // only the library's own assets (the origin is the host's CSP's to allow)
        throw new TypeError('drishti-elements: not a library script: ' + u);
      }
    });
  }
} catch (e) { policy = null; }           // the host's trusted-types list does not name drishti-elements: plain strings (the host then sees why)

/** The allow-listed form of an HTML string, as a plain string. */
export function sanitise(html) {
  const s = String(html == null ? '' : html);
  const t = document.createElement('template');
  t.innerHTML = policy ? policy.createHTML(s, 'raw') : s;
  clean(t.content);
  return t.innerHTML;
}
/** Sets an element's markup: sanitised, through the Trusted Types policy where the browser has them. */
export function setHtml(el, html) {
  const s = String(html == null ? '' : html);
  el.innerHTML = policy ? policy.createHTML(s) : sanitise(s);
}
/** A sanitised fragment for a string. */
export function fragment(html) {
  const t = document.createElement('template');
  setHtml(t, html);
  return t.content;
}
export const scriptUrl = (u) => (policy ? policy.createScriptURL(u) : u);
export const trustedTypesActive = () => !!policy;
