/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.jdbc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.EntityRef;
import com.ash.drishti.api.tls.TlsException;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.TlsFixture;
import java.nio.file.Files;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * PostgreSQL over TLS with the shared {@code tls.*} settings: the wiring (no Docker), then a real PostgreSQL 18 with
 * {@code ssl=on} and certificates generated by the test. Three log-ins: a password user over verified TLS, a user who logs in
 * by client certificate (pg_hba {@code cert}), and the refusals. Skipped where Docker is not reachable.
 */
class PostgresTlsTest {

    private static TlsFixture pki;
    private static GenericContainer<?> pg;

    @BeforeAll
    static void start() throws Exception {
        pki = new TlsFixture();
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
        } catch (RuntimeException e) {
            docker = false;
        }
        if (!docker) {
            return;
        }
        Files.writeString(pki.path("pg_hba.conf"), """
                local all all trust
                hostssl all pwuser all scram-sha-256
                hostssl all drishti all cert
                """);
        GenericContainer<?> c = new GenericContainer<>("postgres:18-alpine").withExposedPorts(5432)
                .withEnv("POSTGRES_PASSWORD", "unused")
                .withCommand("sh", "-c", "mkdir -p /pgtls && cp /tls/* /pgtls/ && chown -R postgres:postgres /pgtls && chmod 600 /pgtls/server.key"
                        + " && exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/pgtls/server.pem -c ssl_key_file=/pgtls/server.key"
                        + " -c ssl_ca_file=/pgtls/ca.pem -c hba_file=/pgtls/pg_hba.conf")
                .waitingFor(Wait.forLogMessage(".*database system is ready to accept connections.*", 2).withStartupTimeout(Duration.ofMinutes(2)));
        for (String f : new String[] {"ca.pem", "server.pem", "server.key", "pg_hba.conf"}) {
            c.withCopyFileToContainer(MountableFile.forHostPath(pki.path(f), 0644), "/tls/" + f);
        }
        pg = c;
        pg.start();
        psql("create table entities(kind text, id text, business_date date, doc jsonb)",
                "insert into entities values ('trade','T-1','2026-09-29','{\"tradeId\":\"T-1\",\"mtm\":5}')",
                "create role pwuser login password 'pw'", "create role drishti login",
                "grant select on entities to pwuser, drishti");
    }

    private static void psql(String... statements) throws Exception {
        for (String s : statements) {
            var r = pg.execInContainer("psql", "-U", "postgres", "-c", s);
            if (r.getExitCode() != 0) {
                throw new IllegalStateException(s + ": " + r.getStderr());
            }
        }
    }

    @AfterAll
    static void stop() {
        if (pg != null) {
            pg.stop();
        }
        pki.delete();
    }

    private static void assumePg() {
        org.junit.jupiter.api.Assumptions.assumeTrue(pg != null, "Docker is needed");
    }

    private static Map<String, String> settings(String host, String user, String password, Map<String, String> tls) {
        Map<String, String> s = new LinkedHashMap<>(tls);
        s.put("url", "jdbc:postgresql://" + host + ":" + pg.getMappedPort(5432) + "/postgres");
        s.put("user", user);
        s.put("password", password);
        s.put("table", "entities");
        s.put("pool-size", "1");
        s.put("refresh-seconds", "3600");
        return s;
    }

    private static Map<String, String> enabled(Map<String, String> tls) {
        Map<String, String> s = new LinkedHashMap<>(tls);
        s.put("tls.enabled", "true");
        return s;
    }

    private static JdbcSourcePlugin open(Map<String, String> s) throws Exception {
        JdbcSourcePlugin p = new JdbcSourcePlugin();
        p.start(DatedSourceContract.context(s));
        return p;
    }

    // ---- wiring, without a server

    @Test
    void otherDriversAreToldWhereTheirTlsOptionsGo() {
        assertThatThrownBy(() -> JdbcTls.plan(Map.of("tls.enabled", "true"), "jdbc:mysql://h/db", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("only mapped for jdbc:postgresql").hasMessageContaining("sslMode=VERIFY_IDENTITY");
    }

    @Test
    void driverOptionsInTheUrlAndTlsSettingsAreNotMixed() {
        assertThatThrownBy(() -> JdbcTls.plan(Map.of("tls.enabled", "true"), "jdbc:postgresql://h/db?sslmode=require", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("give TLS one way");
        assertThat(JdbcTls.plan(Map.of(), "jdbc:postgresql://h/db?sslmode=verify-full&sslrootcert=/ca.pem", System::getenv).tls()).isNull();
    }

    @Test
    void tlsSettingsWithoutEnabledAndAMissingCaFileAreStartUpErrors() {
        assertThatThrownBy(() -> JdbcTls.plan(Map.of("tls.ca-file", "/x.pem"), "jdbc:postgresql://h/db", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.enabled is not true");
        assertThatThrownBy(() -> JdbcTls.plan(Map.of("tls.enabled", "true", "tls.ca-file", "/etc/drishti/nope.pem"), "jdbc:postgresql://h/db", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.ca-file '/etc/drishti/nope.pem'");
    }

    @Test
    void thePlanMapsOntoTheDriverOptions() {
        JdbcTls.Plan p = JdbcTls.plan(Map.of("tls.enabled", "true"), "jdbc:postgresql://h/db", System::getenv);
        try {
            assertThat(p.properties().getProperty("sslmode")).isEqualTo("verify-full");
            assertThat(p.properties().getProperty("ssl")).isEqualTo("true");
            assertThat(p.properties().getProperty("sslfactory")).isEqualTo(PgSslFactory.class.getName());
        } finally {
            PgSslFactory.unregister(p.factoryId());
        }
        JdbcTls.Plan lax = JdbcTls.plan(Map.of("tls.enabled", "true", "tls.verify-hostname", "false"), "jdbc:postgresql://h/db", System::getenv);
        assertThat(lax.properties().getProperty("sslmode")).isEqualTo("require");
        PgSslFactory.unregister(lax.factoryId());
    }

    // ---- a real PostgreSQL with ssl=on

    @Test
    void aPasswordUserOverVerifiedTlsReads() throws Exception {
        assumePg();
        JdbcSourcePlugin p = open(settings("localhost", "pwuser", "pw", enabled(pki.trustOnlySettings())));
        try {
            assertThat(p.fetch(EntityRef.of("trade", "T-1"))).isPresent();
            assertThat(p.health()).isEqualTo("UP");
        } finally {
            p.close();
        }
    }

    @Test
    void theClientCertificateIsTheLoginAndHealthCarriesItsExpiry() throws Exception {
        assumePg();
        JdbcSourcePlugin p = open(settings("localhost", "drishti", "", enabled(pki.clientSettings())));
        try {
            assertThat(p.fetch(EntityRef.of("trade", "T-1"))).isPresent();
            assertThat(p.health()).startsWith("UP").containsPattern("TLS certificate CN=drishti \\(tls.cert-file\\) expires in \\d+ days");
        } finally {
            p.close();
        }
    }

    @Test
    void aCertificateUserWithoutACertificateIsRefused() throws Exception {
        assumePg();
        JdbcSourcePlugin p = open(settings("localhost", "drishti", "whatever", enabled(pki.trustOnlySettings())));
        try {
            assertThatThrownBy(() -> p.fetch(EntityRef.of("trade", "T-1"))).hasMessageContaining("requires a valid client certificate");
            assertThat(p.health()).startsWith("DOWN");
        } finally {
            p.close();
        }
    }

    @Test
    void anUntrustedServerIsRefusedWithThePkixReason() throws Exception {
        assumePg();
        JdbcSourcePlugin p = open(settings("localhost", "pwuser", "pw", enabled(pki.wrongCaSettings())));
        try {
            assertThatThrownBy(() -> p.fetch(EntityRef.of("trade", "T-1"))).hasStackTraceContaining("PKIX path building failed");
            assertThat(p.health()).startsWith("DOWN");
        } finally {
            p.close();
        }
    }

    @Test
    void plainTextIsRefusedByTheServer() throws Exception {
        assumePg();
        Map<String, String> s = settings("localhost", "pwuser", "pw", Map.of());
        s.put("url", s.get("url") + "?sslmode=disable");
        JdbcSourcePlugin p = open(s);
        try {
            assertThatThrownBy(() -> p.fetch(EntityRef.of("trade", "T-1"))).hasMessageContaining("no pg_hba.conf entry");
        } finally {
            p.close();
        }
    }

    @Test
    void theHostNameIsCheckedUnlessTurnedOff() throws Exception {
        assumePg();
        // the certificate names localhost and 127.0.0.1; 127.0.0.2 reaches the same machine under an address it does not carry
        Map<String, String> tls = enabled(pki.trustOnlySettings());
        JdbcSourcePlugin strict = open(settings("127.0.0.2", "pwuser", "pw", tls));
        try {
            assertThatThrownBy(() -> strict.fetch(EntityRef.of("trade", "T-1"))).hasStackTraceContaining("could not be verified");
        } finally {
            strict.close();
        }
        tls.put("tls.verify-hostname", "false");
        JdbcSourcePlugin lax = open(settings("127.0.0.2", "pwuser", "pw", tls));
        try {
            assertThat(lax.fetch(EntityRef.of("trade", "T-1"))).isPresent();
        } finally {
            lax.close();
        }
    }
}
