#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-risk/var_backtest.py there. Edit that source, not this file.
# title: VaR backtest: exceptions, Kupiec and the traffic light
# description: The desk's daily P&L series against today's 99% VaR: the days the loss exceeded VaR, Kupiec's proportion-of-failures test (likelihood ratio and p-value), the Basel traffic light scaled to 250 days, and the P&L drawn against the VaR line. Uses one VaR figure for every day, a simplification: a real backtest compares each day with that day's VaR.
# kinds: var

import pandas as pd
from drishti import quant as q

doc = view.doc
var99 = doc["var99"]
pnl = pd.DataFrame(doc["pnlSeries"]).set_index("date")["pnl"].astype(float)
breach = pnl < -var99
k = q.kupiec_pof(int(breach.sum()), len(pnl), 0.99)

show(pd.DataFrame({
    "measure": ["days", "VaR 99%", "exceptions", "expected exceptions", "exceptions (engine)", "Kupiec LR", "p-value",
                "traffic light (scaled to 250 days)", "worst day", "worst loss / VaR"],
    "value": [len(pnl), var99, k["exceptions"], round(k["expected"], 2), doc.get("exceptions"), round(k["lr"], 3),
              round(k["pvalue"], 4), k["light"], pnl.idxmin(), round(-pnl.min() / var99, 2)],
}), title=f"{view.id}: backtest of {doc.get('method', '')}")
if breach.any():
    show(pnl[breach].to_frame("P&L").assign(**{"excess over VaR": lambda d: -d["P&L"] - var99}), title="Exceptions")
verdict = "rejected" if k["pvalue"] < 0.05 else "not rejected"
print(f"At 5% significance the 99% VaR model is {verdict} on {len(pnl)} days "
      f"({k['exceptions']} exceptions against {k['expected']:.1f} expected).")
chart(pd.DataFrame({"P&L": pnl, "-VaR 99%": -var99}), kind="line", title="Daily P&L against VaR")
