#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/curve_tenor.py there. Edit that source, not this file.
# title: Interpolate the curve at any tenor
# description: Zero rates at tenors the curve does not quote: linear on zero rates, log-linear on discount factors (how the curve is built) and a cubic spline (scipy), with a matplotlib figure.
# kinds: ir-curve

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline

WANT = ["18M", "4Y", "12Y"]                  # change these: 3W, 9M, 7Y, ...
UNIT = {"D": 365.0, "W": 52.0, "M": 12.0, "Y": 1.0}


def years(tenor):
    return float(tenor[:-1]) / UNIT[tenor[-1].upper()]


pts = pd.DataFrame(view.doc["points"])
pts["years"] = pts["tenor"].map(years)
pts = pts.sort_values("years")
t, z, df = pts["years"].to_numpy(), pts["zeroRate"].to_numpy(), pts["df"].to_numpy()
spline = CubicSpline(t, z)


def log_linear(x):                            # linear in log(df), back to a continuously compounded zero rate in %
    return -np.interp(x, t, np.log(df)) / x * 100


want = pd.DataFrame({"tenor": WANT, "years": [years(w) for w in WANT]})
want["linear zero %"] = np.interp(want["years"], t, z)
want["log-linear df, zero %"] = log_linear(want["years"].to_numpy())
want["cubic spline %"] = spline(want["years"])
show(want, title=f"{view.id}: interpolated zero rates")

grid = np.linspace(t.min(), t.max(), 200)
fig, ax = plt.subplots(figsize=(7, 3.2))
ax.plot(grid, spline(grid), label="cubic spline")
ax.plot(grid, log_linear(grid), "--", label="log-linear df")
ax.scatter(t, z, color="black", s=12, zorder=3, label="quoted")
ax.scatter(want["years"], want["cubic spline %"], color="tab:red", s=30, zorder=4, label="asked")
ax.set_xlabel("years")
ax.set_ylabel("zero rate %")
ax.set_title(f"{view.id} ({view.doc.get('index', '')})")
ax.legend(fontsize=8)
