#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/eq_vol_arbitrage.py there. Edit that source, not this file.
# title: Equity vol surface: skew, term structure and arbitrage checks
# description: The surface's smile per expiry and its ATM term structure; skew (90 less 110) and wings; a calendar check (total variance must not fall with expiry at any moneyness) and a butterfly check (undiscounted Black call prices must be convex and decreasing in strike). Moneyness is read as forward moneyness, a simplification.
# kinds: equity-vol-surface

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from drishti import quant as q

doc = view.doc
grid = pd.DataFrame(doc["grid"]).set_index("expiry")
cols = [c for c in grid.columns if c.startswith("m") and c[1:].isdigit()]
m = np.array([int(c[1:]) / 100 for c in cols])                 # strike / forward: 0.8 ... 1.2
T = np.array([q.tenor_years(e) for e in grid.index])
vol = grid[cols].to_numpy() / 100

summary = pd.DataFrame({"years": T, "ATM %": grid["m100"], "skew 90-110 pts": grid["m90"] - grid["m110"],
                        "wings 80+120 - 2 ATM pts": grid["m80"] + grid["m120"] - 2 * grid["m100"]}, index=grid.index)

w = vol ** 2 * T[:, None]                                       # total implied variance by expiry and moneyness
calendar = np.vstack([np.full(len(m), True), np.diff(w, axis=0) >= -1e-12])
summary["calendar ok"] = calendar.all(axis=1)

butterfly = []
for i, t in enumerate(T):                                       # call prices for a forward of 1, undiscounted
    c = q.black76(1.0, m, t, 0.0, vol[i], True)
    slope = np.diff(c) / np.diff(m)                              # must lie in [-1, 0] and rise (convexity)
    butterfly.append(bool(np.all(slope <= 1e-12) and np.all(slope >= -1 - 1e-12) and np.all(np.diff(slope) >= -1e-12)))
summary["butterfly ok"] = butterfly
show(summary, title=f"{view.id}: {doc.get('underlier', '')} ({doc.get('model', '')})")
bad = summary[~(summary["calendar ok"] & summary["butterfly ok"])]
print("No static arbitrage on the quoted grid" if bad.empty else f"Arbitrage flagged at: {', '.join(bad.index)}")

fig, ax = plt.subplots(1, 2, figsize=(9, 3.2))
for i, e in enumerate(grid.index):
    ax[0].plot(m * 100, vol[i] * 100, "o-", ms=3, label=e)
ax[0].set_xlabel("moneyness %")
ax[0].set_ylabel("implied vol %")
ax[0].set_title("Smile by expiry")
ax[0].legend(fontsize=7)
ax[1].plot(T, summary["ATM %"], "o-", label="ATM")
ax[1].plot(T, grid["m90"], "s--", ms=3, label="90%")
ax[1].plot(T, grid["m110"], "^--", ms=3, label="110%")
ax[1].set_xlabel("years")
ax[1].set_title("Term structure")
ax[1].legend(fontsize=7)
