#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/swaption_cube.py there. Edit that source, not this file.
# title: Swaption premiums from the normal-vol grid
# description: ATM payer swaptions for every expiry and swap tenor of the cube: the forward swap rate and its annuity from the currency's OIS curve (single-curve, annual fixed leg), the Bachelier premium at the grid's normal vol, in bp of notional and per 100m, and vega per bp of vol; the vol grid as a heatmap.
# kinds: ir-vol-cube

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from drishti import quant as q

doc = view.doc
curve = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{doc['currency']}-OIS"))["points"])
grid = pd.DataFrame(doc["grid"]).set_index("expiry")
tenor_cols = [c for c in grid.columns if c.startswith("t")]
NOTIONAL = 100e6

rows = []
for expiry, g in grid.iterrows():
    te = q.tenor_years(expiry)
    for col in tenor_cols:
        n = q.tenor_years(col[1:])
        ann = q.annuity(curve, te + n, 1, start=te)                    # forward-starting annual fixed leg
        fwd = q.par_swap_rate(curve, te + n, 1, start=te)
        vol = g[col] / 1e4                                              # bp a year -> rate units
        prem = ann * q.bachelier(fwd, fwd, te, vol, 1.0, True)          # payer ATM: annuity x Bachelier call on the rate
        vega = ann * np.sqrt(te) * q.norm_pdf(0.0) / 1e4                # per +1 bp of normal vol, per unit notional
        rows.append({"expiry": expiry, "tenor": col[1:], "forward %": fwd * 100, "normal vol bp": g[col],
                     "premium bp": prem * 1e4, "premium per 100m": prem * NOTIONAL, "vega per bp, 100m": vega * NOTIONAL})
out = pd.DataFrame(rows)
show(out, title=f"{view.id}: ATM payer swaptions ({doc.get('model', '')}), on CRV-{doc['currency']}-OIS")
show(out.pivot(index="expiry", columns="tenor", values="premium bp").reindex(index=grid.index, columns=[c[1:] for c in tenor_cols]),
     title="Premium, bp of notional")

fig, ax = plt.subplots(figsize=(6, 3.4))
im = ax.imshow(grid[tenor_cols].to_numpy(), cmap="viridis", aspect="auto")
ax.set_xticks(range(len(tenor_cols)), [c[1:] for c in tenor_cols])
ax.set_yticks(range(len(grid)), grid.index)
for (i, j), v in np.ndenumerate(grid[tenor_cols].to_numpy()):
    ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=7, color="white")
ax.set_xlabel("swap tenor")
ax.set_ylabel("expiry")
ax.set_title(f"{view.id}: ATM normal vol, bp")
fig.colorbar(im, ax=ax, shrink=0.8)
