#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/counterparty-risk/margin_calls.py there. Edit that source, not this file.
# title: Margin calls: status, disputes and ageing
# description: Every margin call in one search: by status, direction and margin type, the amounts called and disputed and the dispute rate, the calls still open with their age in days, the largest disputes, and this netting set's calls; a bar of called and disputed amounts by netting set.
# kinds: margin-call, netting-set, csa

import pandas as pd

calls = await drishti.search_async("MC where amount > -1000bn and status != '' and disputeAmount > -1000bn and nettingSet != '' "
                                   "and direction != '' and callDate != '' limit 1000")
calls["callDate"] = pd.to_datetime(calls["callDate"])
calls["age days"] = (pd.Timestamp(view.business_date or "2026-09-30") - calls["callDate"]).dt.days
calls["disputed"] = calls["disputeAmount"].fillna(0)

summary = calls.groupby(["status", "direction"]).agg(calls=("id", "size"), amount=("amount", "sum"),
                                                     disputed=("disputed", "sum")).reset_index()
summary["dispute rate"] = summary["disputed"] / summary["amount"]
show(summary, title=f"{len(calls)} margin calls, {calls['amount'].sum():,.0f} called, {calls['disputed'].sum():,.0f} disputed")
open_calls = calls[~calls["status"].isin(["Settled", "Cancelled"])].sort_values("age days", ascending=False)
show(open_calls[["id", "nettingSet", "direction", "amount", "disputed", "status", "age days"]].head(20).reset_index(drop=True),
     title=f"{len(open_calls)} calls not settled, oldest first")
show(calls.nlargest(10, "disputed")[["id", "nettingSet", "amount", "disputed", "status"]].reset_index(drop=True), title="Largest disputes")

ns = view.doc.get("nettingSet") if view.kind != "netting-set" else view.id
mine = calls[calls["nettingSet"] == ns] if ns else calls.iloc[0:0]
if len(mine):
    show(mine[["id", "callDate", "direction", "amount", "disputed", "status"]].reset_index(drop=True), title=f"Calls on {ns}")
by_ns = calls.groupby("nettingSet")[["amount", "disputed"]].sum().sort_values("amount", ascending=False).head(15)
chart(by_ns.reset_index(), kind="bar", x="nettingSet", y=["amount", "disputed"], title="Called and disputed by netting set (top 15)")
