#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/counterparty-risk/netting_collateral.py there. Edit that source, not this file.
# title: Netting benefit and collateral under the CSA
# description: The netting set's trades: positive and negative MTM, net MTM, the netting benefit and the net-to-gross ratio; then the CSA's terms (thresholds, minimum transfer amount, independent amount) turned into the collateral either side should hold, the call due today against what is held, and the exposure left after netting and collateral. Uses the trades shown on the netting set (the largest, when it lists only some).
# kinds: netting-set

import pandas as pd

ns = view.doc
trades = pd.DataFrame(ns["trades"])
pos, neg = trades.loc[trades["mtm"] > 0, "mtm"].sum(), trades.loc[trades["mtm"] < 0, "mtm"].sum()
net = trades["mtm"].sum()
ngr = max(net, 0) / pos if pos else float("nan")
show(pd.DataFrame({
    "measure": ["trades listed", "trades in the set", "positive MTM (owed to us)", "negative MTM (we owe)", "net MTM (listed)",
                "net MTM (netting set)", "exposure without netting", "exposure with netting", "netting benefit", "net-to-gross ratio"],
    "value": [len(trades), ns.get("tradeCount"), pos, neg, net, ns.get("netMtm"), pos, max(net, 0), pos - max(net, 0), ngr],
}), title=f"{view.id}: netting ({'enforceable' if ns.get('nettingEnforceable') else 'NOT enforceable'})")

csa = await drishti.get_async("csa", ns["csa"]) if ns.get("csa") else {}
th_them, th_us = csa.get("thresholdThem", 0) or 0, csa.get("thresholdUs", 0) or 0
mta, ia = csa.get("mta", 0) or 0, csa.get("independentAmount", 0) or 0
v = ns.get("netMtm", net)
held = ns.get("collateral", 0) or 0                                    # positive: collateral we hold
required = max(v - th_them, 0) + ia if v > 0 else -max(-v - th_us, 0)  # what we should hold (negative: post)
call = required - held
due = call if abs(call) >= mta else 0.0                                 # below the minimum transfer amount: no call
show(pd.DataFrame({
    "measure": ["threshold (them)", "threshold (us)", "minimum transfer", "independent amount", "net MTM", "collateral held",
                "collateral required", "difference", "call due today", "exposure after collateral"],
    "value": [th_them, th_us, mta, ia, v, held, required, call, due, max(v - held, 0)],
}), title=f"{ns.get('csa', 'no CSA')}: {csa.get('marginType', '')}, {csa.get('frequency', '')}, MPoR {csa.get('mpor', '')}")
print("We call" if due > 0 else "We must post" if due < 0 else "No call: the difference is inside the minimum transfer amount",
      f"{abs(due):,.0f}" if due else "")
chart(trades.sort_values("mtm").reset_index(drop=True), kind="bar", x="tradeId", y="mtm", title="MTM by trade")
