# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""From a plan and drafted Sutras to a pack folder (pack.yaml, Sutras, tests, samples, About text, README) and its bundle.

The drafting itself (a Sutra from sample documents) is done by the Java auto-designer, reached differently by the two callers: the CLI runs
``sutra design --each`` in one JVM, the console asks the server (``POST /api/v1/builder/design``) for each Sutra. Both call ``prepare`` to get
the documents to draft from, draft them, then call ``assemble`` with the drafts."""
from __future__ import annotations

import json
import pathlib
import re
import shutil
from dataclasses import dataclass, field

from . import decorate, synth
from .plan import KindPlan, Plan, SutraPlan, humanize, norm

HEADER_NOTE = "# Generated by drishti schemakit (docs/guides/SCHEMA_TO_PACK.md); now yours to edit.\n"


@dataclass
class Sample:
    name: str                    # file name stem, e.g. sample-1, sample-example-1, sample-synthetic-1
    doc: dict
    source: str                  # real | example | synthetic


@dataclass
class Item:
    """One Sutra to draft: the plan's kind and Sutra, and the documents the draft and its tests are made from."""
    kp: KindPlan
    sp: SutraPlan
    samples: list = field(default_factory=list)

    @property
    def name(self) -> str:
        return self.sp.name

    @property
    def synthetic(self) -> bool:
        return all(s.source == "synthetic" for s in self.samples)


def _matches(doc: dict, sp: SutraPlan) -> bool:
    return all(doc.get(f) == v for f, v in sp.values.items())


def _spaced(docs: list, n: int, key: str | None) -> list:
    ordered = sorted(docs, key=lambda d: str(d.get(key)) if key and d.get(key) is not None else json.dumps(d, sort_keys=True))
    if len(ordered) <= n:
        return ordered
    return [ordered[(i * len(ordered)) // n] for i in range(n)]


def prepare(plan: Plan, n: int | None = None) -> list[Item]:
    """For every Sutra of every kind, its samples: real documents that match first (spread over the key), the schema's own ``examples``,
    then synthetic documents until there are ``n`` (and always at least two when the Sutra has no real match)."""
    n = int(n or plan.settings.get("samples", 5))
    items = []
    for kp in plan.kinds:
        for idx, sp in enumerate(kp.sutras):
            real = [d for d in kp.samples if sp.fallback or _matches(d, sp)]
            picks = [Sample(f"sample-{i}", d, "real") for i, d in enumerate(_spaced(real, n, kp.key), 1)]
            ex = [Sample(f"sample-example-{i}", d, "example") for i, d in enumerate(synth.examples_of(kp, sp), 1)] if kp.node else []
            samples = picks + ex[: max(0, n - len(picks))]
            need = max(0, n - len(samples)) if not picks else (max(0, 2 - len(samples)) if not sp.fallback else 0)
            if need:
                docs = synth.documents(kp, plan, need, sp, offset=idx * n)
                samples += [Sample(f"sample-synthetic-{i}", d, "synthetic") for i, d in enumerate(docs, 1)]
            items.append(Item(kp, sp, samples))
    return items


def catalog_docs(kp: KindPlan, plan: Plan, n: int = 8) -> list:
    """The documents of ``samples/<kind>/``: real ones (up to 25), else synthetic ones whose keys are KEY-0001.. so links between kinds resolve."""
    if kp.real:
        return [(d, "real") for d in _spaced(kp.samples, 25, kp.key)]
    variants = [s for s in kp.sutras if s.variant is not None or s.values]
    s = synth.Synth(plan)
    out = []
    for i in range(max(n, len(variants))):
        sp = variants[i % len(variants)] if variants else None
        out.append((s.document(kp, i, sp), "synthetic"))
    return out


def panel_ids(yaml_text: str) -> list[str]:
    return re.findall(r"^\s+- id: (\S+)", yaml_text, re.M)


def drafts_ok(items: list[Item], drafts: dict) -> list[str]:
    return [i.name for i in items if not drafts.get(i.name)]


# ----------------------------------------------------------------------------------------------- pack.yaml

def connector_block(pack: str, kinds: list, store: str, plan_cols: dict) -> dict:
    """A connector for kinds that share a logical name: the file or delta plugin on the usual root, one layout per kind."""
    if store == "file":
        return {"plugin": "file", "enabled": "${DRISHTI_FILES_ENABLED:true}", "kinds": sorted(k.kind for k in kinds),
                "settings": {"root": "${DRISHTI_FILES_ROOT:./data/files}", "domain": pack, "id-field": "id",
                             "layout": {k.kind: {"columns": plan_cols[k.kind]} for k in kinds}}}
    return {"plugin": "delta", "enabled": "${DRISHTI_LAKE_ENABLED:true}", "kinds": sorted(k.kind for k in kinds),
            "settings": {"root": "${DRISHTI_DELTA_ROOT:./data/delta}", "domain": pack,
                         "layout": {k.kind: {"columns": plan_cols[k.kind], "sort-by": "id", "file-rows": 250000, "row-group-rows": 1000} for k in kinds}}}


def columns_for(kp: KindPlan, n: int = 7) -> list[str]:
    scal = [f.path for f in kp.fields if "." not in f.path and "[" not in f.path and f.path != kp.key and f.role not in ("object", "table", "map", "list")
            and not f.hidden]
    pref = [p for p in kp.strip if p in scal]
    return list(dict.fromkeys(pref + [p for p in scal if p not in pref]))[:n]


def pack_manifest(plan: Plan, kinds_dir_note: str = "") -> dict:
    p = plan.pack
    m: dict = {"pack": p["name"], "version": p.get("version") or "1.0.0", "code": p.get("code") or p["name"][:4].upper(),
               "title": p.get("title") or p["name"], "description": p.get("description") or f"Generated from schemas for {p['name']}.",
               "kinds": [k.kind for k in plan.kinds], "sutras": "sutras", "samples": "samples",
               "mnemonics": {k.mnemonic: {"kind": k.kind, "label": k.title} for k in plan.kinds},
               "columns": {k.kind: columns_for(k) for k in plan.kinds}}
    fields: dict = {}
    for k in plan.kinds:
        for l in k.links:
            name = l.field.split(".")[-1].replace("[]", "")
            if name in fields and fields[name]["kind"] != l.to:
                plan.warnings.append(f"{k.kind}: the link field '{name}' already points at {fields[name]['kind']}; a link field name means one kind, so '{name}' -> {l.to} was left out")
                continue
            fields[name] = {"kind": l.to, "label": humanize(name.removesuffix("Id").removesuffix("_id") or name)}
    if fields:
        m["graph"] = {"fields": fields}
    by_conn: dict[str, list] = {}
    for k in plan.kinds:
        if k.template in ("file", "delta"):
            by_conn.setdefault(k.connector or f"{p['name']}-store", []).append(k)
    if by_conn:
        m["connectors"], m["routes"], ing = {}, {}, {}
        for name, ks in sorted(by_conn.items()):
            store = ks[0].template
            m["connectors"][name] = connector_block(p["name"], ks, store, {k.kind: columns_for(k) + ([k.date] if k.date and k.date not in columns_for(k) else []) for k in ks})
            for k in ks:
                m["routes"][k.kind] = name
                if k.key and k.date:
                    ing[k.kind] = {"key": k.key, "date": k.date}
        if ing:
            m["ingest"] = ing
    if getattr(plan, "controls_note", None):
        m["x-controls"] = plan.controls_note
    return m


# ----------------------------------------------------------------------------------------------- the folder

@dataclass
class Built:
    pack_dir: pathlib.Path
    sutras: list = field(default_factory=list)    # [{name, kind, file, yaml, samples:[{name, source}], shown}]
    shown: dict = field(default_factory=dict)
    synthetic: list = field(default_factory=list)
    todo: int = 0


def assemble(plan: Plan, items: list[Item], drafts: dict, pack_dir: pathlib.Path, license_header: str = "", say=print) -> Built:
    """Writes the pack folder. ``drafts`` maps a Sutra name to the auto-designer's YAML for it."""
    import yaml
    missing = drafts_ok(items, drafts)
    if missing:
        raise ValueError("no draft for: " + ", ".join(missing))
    if pack_dir.exists():
        shutil.rmtree(pack_dir)
    built = Built(pack_dir)
    for it in items:
        text, shown = decorate.finalize(drafts[it.name], it.kp, it.sp)
        built.shown.setdefault(it.kp.kind, set()).update(shown)
        f = pack_dir / "sutras" / it.kp.kind / f"{it.name}.v1.sutra.yaml"
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
        td = pack_dir / "tests" / it.name
        td.mkdir(parents=True, exist_ok=True)
        for s in it.samples:
            (td / f"{s.name}.json").write_text(json.dumps(s.doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        panels = panel_ids(text)
        expect = "noErrors: true\n" + (f"nonEmpty: [{', '.join(p for p in ('details',) if p in panels)}]\n" if "details" in panels and not it.sp.fallback else "")
        (td / "expect.yaml").write_text(expect, encoding="utf-8")
        built.sutras.append({"name": it.name, "kind": it.kp.kind, "file": str(f.relative_to(pack_dir)), "yaml": text, "where": it.sp.where,
                             "samples": [{"name": s.name, "source": s.source, "document": s.doc} for s in it.samples], "synthetic": it.synthetic})
        if it.synthetic:
            built.synthetic.append(it.name)
    # samples/ catalog
    cat = []
    for kp in plan.kinds:
        sd = pack_dir / "samples" / kp.kind
        sd.mkdir(parents=True, exist_ok=True)
        for doc, src in catalog_docs(kp, plan):
            kv = doc.get(kp.key) if kp.key else None
            if kv is None:
                continue
            (sd / f"{kv}.json").write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
            cat.append({"kind": kp.kind, "id": str(kv), "title": str(kv), "subtitle": kp.kind + (" (synthetic sample)" if src == "synthetic" else "")})
    (pack_dir / "samples").mkdir(exist_ok=True)
    (pack_dir / "samples" / "catalog.json").write_text(json.dumps(cat, indent=1) + "\n", encoding="utf-8")
    # pack.yaml and About
    man = pack_manifest(plan)
    note = HEADER_NOTE + "".join(f"# {k.kind}: key $.{k.key}" + (f", business date $.{k.date}" if k.date else "") + "\n" for k in plan.kinds)
    (pack_dir / "pack.yaml").write_text(note + yaml.safe_dump(man, sort_keys=False, width=120, allow_unicode=True), encoding="utf-8")
    (pack_dir / "config").mkdir(exist_ok=True)
    (pack_dir / "config" / "about.yaml").write_text(decorate.about_yaml(plan, built.shown), encoding="utf-8")
    built.todo = decorate.todo_count(plan)
    (pack_dir / "README.md").write_text(readme(plan, items, built), encoding="utf-8")
    if license_header:
        for p in pack_dir.rglob("*"):
            if p.suffix in (".yaml", ".md") and p.is_file() and not p.read_text(encoding="utf-8").startswith(license_header[:20]):
                p.write_text(license_header + p.read_text(encoding="utf-8"), encoding="utf-8")
    return built


def readme(plan: Plan, items: list[Item], built: Built) -> str:
    rows = "\n".join(f"| {k.kind} | `{k.key}` | {k.source or 'sample documents'} | {len(k.sutras)} | {('`' + k.date + '`') if k.date else ''} | "
                     f"{', '.join(f'{l.field} -> {l.to}' for l in k.links)} |" for k in plan.kinds)
    syn = ", ".join(built.synthetic) or "none"
    return f"""# {plan.pack.get('title') or plan.pack['name']}

Generated from JSON Schema by schemakit (`docs/guides/SCHEMA_TO_PACK.md`). Nothing here is final: edit it.

| kind | id field | schema | Sutras | business date | links |
|---|---|---|---|---|---|
{rows}

## What was generated

- `pack.yaml`: kinds, mnemonics, `columns` (pick-list columns), `graph.fields` (links between kinds)"""+(", connectors and routes" if any(k.template in ("file", "delta") for k in plan.kinds) else "")+f""".
- `sutras/<kind>/`: {len(items)} Sutra(s), drafted by auto-design from sample documents and then labelled from the schema (titles, descriptions, formats, links).
- `tests/<sutra>/`: samples named `sample-N.json` (real documents), `sample-example-N.json` (the schema's own examples) or
  `sample-synthetic-N.json` (generated from the schema: **synthetic**), and `expect.yaml`.
  Sutras tested on synthetic samples only: {syn}.
- `samples/`: documents so the pack opens before any data source is connected.
- `config/about.yaml`: the *About this page* text from the schema descriptions; {built.todo} field(s) had no description and say `TODO`.

## Next steps

1. `drishti.py pack check` this folder, then `pack bundle`, `pack verify` and `pack deploy` (or Admin -> Packs -> Deploy archive).
2. Open a document in the console and refine the Sutras in the Build workbench.
3. Fill the `TODO` entries of `config/about.yaml` (add `description` to the schema and generate again to keep them in the schema instead).
"""


# ----------------------------------------------------------------------------------------------- bundle

def make_bundle(pack_dir: pathlib.Path, out_dir: pathlib.Path, packbundle, tool_versions: dict | None = None, required_server: str | None = None) -> dict:
    """Writes <out_dir>/<name>-<version>.tar.gz (+ .sha256, .manifest.json) with tools/packbundle.py: the format of `pack bundle`."""
    return packbundle.bundle(pack_dir, out_dir, tool_versions or {}, required_server)
