/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.rabbitmq;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.SourcePlugin;
import com.ash.drishti.api.tls.TlsContexts;
import com.ash.drishti.api.tls.TlsException;
import com.ash.drishti.api.tls.TlsMaterial;
import com.ash.drishti.api.tls.TlsSettings;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.MessageSourceContract;
import com.ash.drishti.testkit.TestPki;
import com.rabbitmq.client.AMQP;
import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * The whole message-source contract over {@code amqps://} with the client certificate as the log-in (the EXTERNAL mechanism),
 * against RabbitMQ 4.1 in Docker with certificates generated by the test; then user name and password over TLS, and the
 * failure cases. Skipped where Docker or the image is not reachable.
 */
class RabbitMqTlsTest extends MessageSourceContract {

    static final String IMAGE = "rabbitmq:4.1-alpine";
    static GenericContainer<?> broker;
    static Path dir;
    static TestPki.Identity ca;
    static Map<String, String> tls;

    @BeforeAll
    static void startBroker() throws Exception {
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
            if (docker) {
                org.testcontainers.DockerClientFactory.lazyClient().inspectImageCmd(IMAGE).exec();
            }
        } catch (RuntimeException e) {
            docker = false;
        }
        org.junit.jupiter.api.Assumptions.assumeTrue(docker, "Docker and the image " + IMAGE + " are needed");
        dir = Files.createTempDirectory("rabbit-tls");
        ca = TestPki.ca("test-ca");
        TestPki.Identity server = TestPki.issue(ca, "broker", "RSA", 30);
        TestPki.Identity client = TestPki.issue(ca, "drishti", "EC", 30);
        ca.writeCertPem(dir.resolve("ca.pem"));
        server.writeCertPem(dir.resolve("server.pem"));
        server.writeKeyPem(dir.resolve("server.key"), TestPki.KeyFormat.PKCS8, null);
        client.writeCertPem(dir.resolve("client.pem"));
        client.writeKeyPem(dir.resolve("client.key"), TestPki.KeyFormat.PKCS8, null);
        Files.writeString(dir.resolve("rabbitmq.conf"), """
                listeners.tcp = none
                listeners.ssl.default = 5671
                ssl_options.cacertfile = /etc/rabbitmq/certs/ca.pem
                ssl_options.certfile = /etc/rabbitmq/certs/server.pem
                ssl_options.keyfile = /etc/rabbitmq/certs/server.key
                ssl_options.verify = verify_peer
                ssl_options.fail_if_no_peer_cert = true
                auth_mechanisms.1 = PLAIN
                auth_mechanisms.2 = EXTERNAL
                ssl_cert_login_from = common_name
                """);
        Files.writeString(dir.resolve("enabled_plugins"), "[rabbitmq_auth_mechanism_ssl].\n");
        GenericContainer<?> c = new GenericContainer<>(IMAGE).withExposedPorts(5671)
                .waitingFor(Wait.forLogMessage(".*Server startup complete.*", 1).withStartupTimeout(java.time.Duration.ofSeconds(90)));
        c.withCopyFileToContainer(MountableFile.forHostPath(dir.resolve("rabbitmq.conf"), 0644), "/etc/rabbitmq/rabbitmq.conf");
        c.withCopyFileToContainer(MountableFile.forHostPath(dir.resolve("enabled_plugins"), 0644), "/etc/rabbitmq/enabled_plugins");
        for (String f : new String[] {"ca.pem", "server.pem", "server.key"}) {
            c.withCopyFileToContainer(MountableFile.forHostPath(dir.resolve(f), 0644), "/etc/rabbitmq/certs/" + f);
        }
        broker = c;
        broker.start();
        // the user the certificate's common name maps to, and one with a password
        broker.execInContainer("rabbitmqctl", "add_user", "drishti", "unused-for-external");
        broker.execInContainer("rabbitmqctl", "set_permissions", "-p", "/", "drishti", ".*", ".*", ".*");
        broker.execInContainer("rabbitmqctl", "add_user", "bob", "bob-secret");
        broker.execInContainer("rabbitmqctl", "set_permissions", "-p", "/", "bob", ".*", ".*", ".*");
        tls = new HashMap<>();
        tls.put("tls.ca-file", dir.resolve("ca.pem").toString());
        tls.put("tls.cert-file", dir.resolve("client.pem").toString());
        tls.put("tls.key-file", dir.resolve("client.key").toString());
    }

    @AfterAll
    static void stopBroker() throws Exception {
        if (broker != null) {
            broker.stop();
        }
        if (dir != null) {
            try (var files = Files.walk(dir)) {
                files.sorted(java.util.Comparator.reverseOrder()).forEach(p -> p.toFile().delete());
            }
        }
    }

    static String uri(String host, String credentials) {
        return "amqps://" + credentials + host + ":" + broker.getMappedPort(5671) + "/%2f";
    }

    @Override
    protected SourcePlugin start(Path state) throws Exception {
        Map<String, String> s = new HashMap<>(shared(state));
        s.putAll(tls);
        s.put("uri", uri(broker.getHost(), ""));
        s.put("auth-mechanism", "external");
        s.put("queues", TRADES + "," + ENTITIES);
        RabbitMqSourcePlugin p = new RabbitMqSourcePlugin();
        p.start(DatedSourceContract.context(s));
        return p;
    }

    @Override
    protected void send(String destination, String id, String body, boolean deleted) throws Exception {
        TlsMaterial m = TlsContexts.build(TlsSettings.from(tls));
        ConnectionFactory f = new ConnectionFactory();
        f.setUri(uri(broker.getHost(), ""));
        RabbitMqSourcePlugin.secure(f, m, true);
        try (Connection c = f.newConnection(); Channel ch = c.createChannel()) {
            ch.queueDeclare(destination, true, false, false, null);
            Map<String, Object> headers = new HashMap<>();
            if (id != null) {
                headers.put("id", id);
            }
            if (deleted) {
                headers.put("deleted", "true");
            }
            ch.basicPublish("", destination, new AMQP.BasicProperties.Builder().headers(headers).deliveryMode(2).build(),
                    body.getBytes(StandardCharsets.UTF_8));
        }
    }

    // ---------------------------------------------------------------- other log-ins and failures

    /** Starts a plugin with these settings and returns "UP", or every distinct reason it gave within a few seconds. */
    String healthWith(Map<String, String> settings) throws Exception {
        Map<String, String> s = new HashMap<>(shared(Files.createTempDirectory(dir, "state")));
        s.putAll(settings);
        s.put("queues", TRADES);
        RabbitMqSourcePlugin p = new RabbitMqSourcePlugin();
        p.start(DatedSourceContract.context(s));
        try {
            Set<String> seen = new LinkedHashSet<>();
            long until = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
            while (System.nanoTime() < until) {
                String h = p.health();
                if (h.startsWith("UP")) {
                    return h;
                }
                if (!h.startsWith("DOWN: not started")) {
                    seen.add(h);
                }
                Thread.sleep(100);
            }
            return seen.isEmpty() ? "DOWN: no reason given" : String.join(" | ", seen);
        } finally {
            p.close();
        }
    }

    @Test
    void userAndPasswordOverTlsWorkToo() throws Exception {
        Map<String, String> s = new HashMap<>(tls);
        s.put("uri", uri(broker.getHost(), "bob:bob-secret@"));
        assertThat(healthWith(s)).startsWith("UP");
    }

    @Test
    void aWrongPasswordIsRefused() throws Exception {
        Map<String, String> s = new HashMap<>(tls);
        s.put("uri", uri(broker.getHost(), "bob:nope@"));
        assertThat(healthWith(s)).startsWith("DOWN").containsAnyOf("ACCESS_REFUSED", "authentication");
    }

    @Test
    void aBrokerWhoseCaIsNotTrustedIsRefusedWithThePkixReason() throws Exception {
        TestPki.ca("rogue").writeCertPem(dir.resolve("rogue.pem"));
        Map<String, String> s = new HashMap<>(tls);
        s.put("tls.ca-file", dir.resolve("rogue.pem").toString());
        s.put("uri", uri(broker.getHost(), "bob:bob-secret@"));
        assertThat(healthWith(s)).startsWith("DOWN").contains("PKIX path building failed");
    }

    @Test
    void aWrongHostNameIsRefusedUnlessVerificationIsSwitchedOff() throws Exception {
        Map<String, String> s = new HashMap<>(tls);
        s.put("auth-mechanism", "external");
        s.put("uri", uri("127.0.0.2", ""));
        assertThat(healthWith(s)).startsWith("DOWN").containsAnyOf("No subject alternative", "hostname", "host name");
        s.put("tls.verify-hostname", "false");
        assertThat(healthWith(s)).startsWith("UP");
    }

    @Test
    void settingsThatDoNotFitAreRefusedAtStart() throws Exception {
        Map<String, String> plain = new HashMap<>(shared(Files.createTempDirectory(dir, "state2")));
        plain.put("uri", "amqp://localhost:5672");
        plain.put("tls.enabled", "true");
        assertThatThrownBy(() -> new RabbitMqSourcePlugin().start(DatedSourceContract.context(plain))).isInstanceOf(TlsException.class)
                .hasMessageContaining("uri is not amqps://");
        Map<String, String> noCert = new HashMap<>(shared(Files.createTempDirectory(dir, "state3")));
        noCert.put("uri", uri(broker.getHost(), ""));
        noCert.put("auth-mechanism", "external");
        noCert.put("tls.ca-file", dir.resolve("ca.pem").toString());
        assertThatThrownBy(() -> new RabbitMqSourcePlugin().start(DatedSourceContract.context(noCert))).isInstanceOf(TlsException.class)
                .hasMessageContaining("client certificate");
        Map<String, String> bad = new HashMap<>(shared(Files.createTempDirectory(dir, "state4")));
        bad.put("uri", uri(broker.getHost(), ""));
        bad.put("auth-mechanism", "kerberos");
        assertThatThrownBy(() -> new RabbitMqSourcePlugin().start(DatedSourceContract.context(bad))).isInstanceOf(TlsException.class)
                .hasMessageContaining("not plain or external");
    }
}
