#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/bond_scenarios.py there. Edit that source, not this file.
# title: Bond P&L under yield moves: duration, convexity and full repricing
# description: The bond repriced at yields from -200 to +200 bp against two approximations, duration alone and duration with convexity, with the error of each; and the 1-year horizon return (coupon carry plus price change) under each move, the breakeven yield rise that wipes out a year's carry.
# kinds: bond

from datetime import date
import numpy as np
import pandas as pd
from drishti import quant as q

doc = view.doc
FREQ = {"Annual": 1, "Semi-annual": 2, "Quarterly": 4}.get((doc.get("terms") or {}).get("couponFrequency"), 2)
years = (date.fromisoformat(doc["maturity"]) - date.fromisoformat(view.business_date or "2026-09-30")).days / 365.25
c, clean = doc["coupon"], doc["price"]
y0 = q.bond_yield(clean, c, years, FREQ)
r = q.bond_risk(y0, c, years, FREQ)
dirty0 = r["dirty"]

rows = []
for bp in [-200, -100, -50, -25, 0, 25, 50, 100, 200]:
    dy = bp / 1e4
    full = q.bond_price(y0 + dy, c, years, FREQ, clean=False) - dirty0
    dur = -r["modified"] * dirty0 * dy                                   # first order
    conv = dur + 0.5 * r["convexity"] * dirty0 * dy ** 2                 # second order
    horizon = years - 1.0
    price_1y = q.bond_price(y0 + dy, c, horizon, FREQ) if horizon > 0 else 100.0
    total_1y = price_1y + c * 100 - clean                               # clean in a year + coupons received - clean today
    rows.append({"move bp": bp, "full reprice": full, "duration": dur, "duration + convexity": conv,
                 "duration error": dur - full, "convexity error": conv - full, "1Y return % (move now, held)": total_1y / clean * 100})
out = pd.DataFrame(rows).set_index("move bp")
show(out, title=f"{view.id}: per 100 face; yield {y0:.3%}, modified duration {r['modified']:.2f}, convexity {r['convexity']:.1f}")
chart(out.reset_index(), kind="line", x="move bp", y=["full reprice", "duration", "duration + convexity"],
      title="Price change per 100 face")
carry = c * 100 + (q.bond_price(y0, c, years - 1.0, FREQ) - clean if years > 1 else 100 - clean)
print(f"A year's carry and roll at an unchanged yield: {carry:.3f} per 100; it is lost to a yield rise of about "
      f"{carry / (r['modified'] * dirty0) * 1e4:.0f} bp")
