#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/cap_pricer.py there. Edit that source, not this file.
# title: Cap prices from the normal-vol surface
# description: Caps of 1Y to 10Y priced as strips of quarterly caplets with the Bachelier formula: forwards from the currency's projection curve, discounting on its OIS curve, each cap at its own flat normal vol from the surface (ATM at the cap's par rate, and the fixed strikes k2 to k5 read as 2% to 5%); premium in bp of notional and per 100m. Flat cap vols, not stripped caplet vols: a simplification.
# kinds: cap-vol-surface

import numpy as np
import pandas as pd
from drishti import quant as q

doc = view.doc
ccy = doc["currency"]
disc = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{ccy}-OIS"))["points"])
try:
    proj = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{ccy}-PROJ"))["points"])
except drishti.DrishtiError:
    proj = disc                                                    # single curve when there is no projection curve
NOTIONAL, TAU = 100e6, 0.25


def cap(T, K, vol_bp):
    ends = np.arange(2 * TAU, T + 1e-9, TAU)                       # the first period's fixing is known: no optionality
    starts = ends - TAU
    fwd = proj.forward(starts, ends)
    K = fwd.mean() if K is None else K                             # ATM: about the cap's par rate
    caplets = q.bachelier(fwd, K, starts, vol_bp / 1e4, disc.df(ends) * TAU, True)
    return float(np.sum(caplets)), K


strike_cols = [c for c in doc["grid"][0] if c.startswith("k") and c[1:].isdigit()]
rows = []
for g in doc["grid"]:
    T = q.tenor_years(g["maturity"])
    prem, k_atm = cap(T, None, g["atm"])
    row = {"maturity": g["maturity"], "ATM strike %": k_atm * 100, "ATM vol bp": g["atm"], "ATM premium bp": prem * 1e4,
           "ATM per 100m": prem * NOTIONAL}
    for c in strike_cols:
        row[f"{c[1:]}% cap bp"] = cap(T, int(c[1:]) / 100, g[c])[0] * 1e4
    rows.append(row)
out = pd.DataFrame(rows).set_index("maturity")
show(out, title=f"{view.id}: {ccy} caps, quarterly caplets, Bachelier ({doc.get('model', '')})")
chart(out.reset_index(), kind="line", x="maturity", y=["ATM premium bp"] + [f"{c[1:]}% cap bp" for c in strike_cols],
      title="Cap premium by maturity and strike, bp of notional")
