#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/curve_scenarios.py there. Edit that source, not this file.
# title: Parallel, twist and butterfly scenarios
# description: The curve moved in parallel, steepened and flattened (a twist pivoting at 5Y) and bent (a butterfly), and the full-revaluation P&L of receiving 2Y, 5Y, 10Y and 30Y par swaps (100m each) under every scenario, with the shocked curves drawn. Illustrative shapes, not a calibrated scenario set.
# kinds: ir-curve

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from drishti import quant as q

base = q.ZeroCurve.from_points(view.doc["points"])
NOTIONAL = 100e6
SCENARIOS = {                                   # (parallel bp, twist bp, butterfly bp); twist: long end up, short end down
    "+100 parallel": (100, 0, 0), "+25 parallel": (25, 0, 0), "-25 parallel": (-25, 0, 0), "-100 parallel": (-100, 0, 0),
    "steepener 50": (0, 50, 0), "flattener 50": (0, -50, 0), "butterfly +30 (wings up)": (0, 0, 30),
    "bear steepener": (25, 50, 0), "bull flattener": (-25, -50, 0),
}
tenors = [t for t in (2, 5, 10, 30) if t <= base.times[-1]]
swaps = {t: q.par_swap_rate(base, t, 1) for t in tenors}          # receive each at today's par: PV 0 today

rows = []
for name, (bp, twist, fly) in SCENARIOS.items():
    shocked = base.shifted(bp, twist, fly)
    row = {"scenario": name}
    for t in tenors:
        row[f"rec {t}Y"] = q.swap_pv(shocked, swaps[t], NOTIONAL, t, 1, receive_fixed=True)
    row["total"] = sum(row[f"rec {t}Y"] for t in tenors)
    row["2s10s move bp"] = ((shocked.zero(10) - shocked.zero(2)) - (base.zero(10) - base.zero(2))) * 1e4
    rows.append(row)
pnl = pd.DataFrame(rows).set_index("scenario")
show(pnl, title=f"{view.id}: P&L of receiving par swaps, {NOTIONAL / 1e6:,.0f}m each")
chart(pnl.reset_index(), kind="bar", x="scenario", y="total", title="Total P&L by scenario")

grid = np.linspace(0.25, base.times[-1], 120)
fig, ax = plt.subplots(figsize=(7.5, 3.4))
ax.plot(grid, base.zero(grid) * 100, color="black", lw=2, label="today")
for name in ("+25 parallel", "steepener 50", "flattener 50", "butterfly +30 (wings up)"):
    ax.plot(grid, base.shifted(*SCENARIOS[name]).zero(grid) * 100, lw=1, label=name)
ax.set_xlabel("years")
ax.set_ylabel("zero rate %")
ax.set_title(f"{view.id}: scenario curves")
ax.legend(fontsize=7)
