#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/curve_compare_ccy.py there. Edit that source, not this file.
# title: OIS curves across currencies, and swap spreads
# description: Every OIS discount curve (drishti.search_async, then each curve's pillars): 2Y, 5Y, 10Y and 30Y zero rates, 2s10s and 5s30s in bp, drawn together; and for this curve's currency, the OIS curve against the government curve (the swap spread by tenor).
# kinds: ir-curve

import numpy as np
import pandas as pd
from drishti import quant as q

ccy = view.doc["currency"]
found = await drishti.search_async("CRV where curveType = 'Discount (OIS)' and currency != '' limit 100")
curves = {}
for cid, c in zip(found["id"], found["currency"]):
    curves[c] = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", cid))["points"])

rows = []
for c, curve in sorted(curves.items()):
    z = {t: curve.zero(t) * 100 for t in (2, 5, 10, 30)}
    rows.append({"currency": c, "2Y %": z[2], "5Y %": z[5], "10Y %": z[10], "30Y %": z[30],
                 "2s10s bp": (z[10] - z[2]) * 100, "5s30s bp": (z[30] - z[5]) * 100})
table = pd.DataFrame(rows).set_index("currency")
show(table, title=f"OIS zero rates by currency ({len(table)} curves)")

grid = np.round(np.linspace(0.5, 30, 60), 2)
chart(pd.DataFrame({c: curve.zero(grid) * 100 for c, curve in curves.items()}, index=pd.Index(grid, name="years")),
      kind="line", title="OIS zero curves, %")

# swap spread: OIS against the government curve of the same currency, where there is one
try:
    govt = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{ccy}-GOVT"))["points"])
except drishti.DrishtiError as e:
    print(f"no government curve for {ccy}: {e.detail}")
else:
    ois = curves.get(ccy) or q.ZeroCurve.from_points(view.doc["points"])
    tenors = [1, 2, 3, 5, 7, 10, 15, 20, 30]
    spread = pd.DataFrame({"years": tenors, "OIS %": ois.zero(tenors) * 100, "government %": govt.zero(tenors) * 100})
    spread["swap spread bp"] = (spread["OIS %"] - spread["government %"]) * 100
    show(spread, title=f"{ccy}: OIS against government (zero rates)")
    chart(spread, kind="bar", x="years", y="swap spread bp", title=f"{ccy} swap spread by tenor, bp")
