#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/eq_beta_returns.py there. Edit that source, not this file.
# title: Beta, correlation and return distribution against the index
# description: Daily log returns of the stock and of its index from their price histories, aligned by date: an OLS regression with statsmodels (beta, alpha, R squared, the summary), the correlation, set beside the beta the security master holds, and the returns' skew, excess kurtosis and Jarque-Bera normality test (scipy).
# kinds: equity

import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy import stats

doc = view.doc
index_id = doc.get("equityIndex")
if not index_id:
    raise ValueError(f"{view.id} names no equityIndex to regress on")
idx = await drishti.get_async("equity-index", index_id)

px = pd.DataFrame({
    view.id: pd.Series({p["date"]: p["close"] for p in doc["history"]}),
    index_id: pd.Series({p["date"]: p["close"] for p in idx["history"]}),
}).sort_index().dropna()
rets = np.log(px).diff().dropna()                        # one row a day both have a close
y, x = rets[view.id], rets[index_id]

model = sm.OLS(y, sm.add_constant(x)).fit()
beta, alpha = model.params[index_id], model.params["const"]
show(pd.DataFrame({
    "measure": ["beta (OLS)", "beta (security master)", "alpha, daily", "R squared", "correlation", "days",
                f"{view.id} vol, annual", f"{index_id} vol, annual"],
    "value": [beta, doc.get("beta"), alpha, model.rsquared, y.corr(x), len(rets),
              y.std(ddof=1) * np.sqrt(252), x.std(ddof=1) * np.sqrt(252)],
}), title=f"{view.id} against {index_id} ({idx.get('name', '')}), daily log returns")
print(model.summary(title=f"OLS: {view.id} returns on {index_id} returns"))

jb = stats.jarque_bera(y)
show(pd.DataFrame({
    "measure": ["mean daily", "std daily", "skew", "excess kurtosis", "Jarque-Bera", "JB p-value", "worst day", "best day"],
    "value": [y.mean(), y.std(ddof=1), stats.skew(y), stats.kurtosis(y), jb.statistic, jb.pvalue, y.min(), y.max()],
}), title=f"{view.id}: distribution of daily returns")
chart(pd.DataFrame({"index return": x, "stock return": y}), kind="scatter", x="index return", y="stock return",
      title=f"{view.id} against {index_id}: beta {beta:.2f}")
