#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/fixing_compounding.py there. Edit that source, not this file.
# title: Overnight rate compounded in arrears
# description: The overnight fixings compounded in arrears (each rate weighted by the calendar days it applies, ACT/360, as SOFR and ESTR swaps and the published averages do) against their simple average, the annualised compounded rate over the window, the interest on 100m, and the rate and volume drawn.
# kinds: rate-fixing

import pandas as pd

doc = view.doc
fx = pd.DataFrame(doc["fixings"])
fx["date"] = pd.to_datetime(fx["date"])
fx = fx.sort_values("date").reset_index(drop=True)
rate = fx["rate"] if "rate" in fx else fx["ratePct"] / 100
# a rate set on a Friday applies over the weekend: its weight is the days until the next fixing (1 for the last one)
fx["days"] = fx["date"].diff().shift(-1).dt.days.fillna(1).astype(int)
BASIS = 365 if doc.get("currency") in ("GBP", "AUD", "CAD") else 360          # SONIA, AONIA, CORRA: ACT/365F
growth = (1 + rate * fx["days"] / BASIS).prod()
days = int(fx["days"].sum())
compounded = (growth - 1) * BASIS / days
simple = (rate * fx["days"]).sum() / days
NOTIONAL = 100e6

show(pd.DataFrame({
    "measure": ["from", "to", "calendar days", "compounded in arrears (annualised)", "simple day-weighted average",
                "compounding effect bp", f"interest on {NOTIONAL / 1e6:,.0f}m", "latest fixing", "change over window bp"],
    "value": [fx["date"].iloc[0].date(), fx["date"].iloc[-1].date(), days, f"{compounded:.5%}", f"{simple:.5%}",
              f"{(compounded - simple) * 1e4:.3f}", f"{(growth - 1) * NOTIONAL:,.0f}", f"{rate.iloc[-1]:.4%}",
              f"{(rate.iloc[-1] - rate.iloc[0]) * 1e4:+.1f}"],
}), title=f"{view.id}: {doc.get('name', '')} ({doc.get('administrator', '')}), ACT/{BASIS}")
series = pd.DataFrame({"rate %": rate.to_numpy() * 100}, index=fx["date"].dt.strftime("%Y-%m-%d"))
chart(series, kind="line", title=f"{doc.get('name', view.id)} fixings, %")
if "volumeBn" in fx:
    chart(pd.DataFrame({"volume bn": fx["volumeBn"].to_numpy()}, index=series.index), kind="bar", title="Volume, bn")
