#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-data/fx_smile.py there. Edit that source, not this file.
# title: FX smile: strikes from deltas, RR and BF checks
# description: Each expiry's 10 and 25 delta vols turned into strikes (spot delta, premium unadjusted, Garman-Kohlhagen) with forwards from the forward curve and rates from the OIS curves, the quoted 25D risk reversal and butterfly checked against the vols, the ATM term structure and a calendar check on total variance; the smiles drawn against strike.
# kinds: fx-vol-surface

import math
import pandas as pd
import matplotlib.pyplot as plt
from drishti import quant as q

doc = view.doc
spot_doc = await drishti.get_async("fx-spot", doc.get("fxSpot") or f"FX-{doc['pair']}")
fwd_doc = await drishti.get_async("fx-forward-curve", spot_doc.get("fxForwardCurve") or f"FXF-{doc['pair']}")
c = spot_doc["conventions"]
S, pip = spot_doc["mid"], c.get("pipFactor", 10000)
pts = [(q.tenor_years(p["tenor"]), math.log((S + p["pips"] / pip) / S) / q.tenor_years(p["tenor"])) for p in fwd_doc["points"]]
try:
    rd_curve = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{c['quote']}-OIS"))["points"])
except drishti.DrishtiError:
    rd_curve = q.ZeroCurve([1, 30], [0.03, 0.03])                    # no OIS curve for the quote currency: 3% flat
    print(f"no OIS curve for {c['quote']}: domestic rate 3% flat")

rows, fig, ax = [], *plt.subplots(figsize=(7, 3.4))
for g in doc["grid"]:
    T = q.tenor_years(g["expiry"])
    diff = min(pts, key=lambda p: abs(p[0] - T))[1]                  # the nearest forward tenor's yield differential
    rd = rd_curve.zero(T)
    rf, F = rd - diff, S * math.exp(diff * T)
    vols = {"10D put": g["p10"], "25D put": g["p25"], "ATM": g["atm"], "25D call": g["c25"], "10D call": g["c10"]}
    strikes = {"10D put": q.fx_strike_from_delta(S, T, rd, rf, g["p10"] / 100, 0.10, call=False),
               "25D put": q.fx_strike_from_delta(S, T, rd, rf, g["p25"] / 100, 0.25, call=False),
               "ATM": F * math.exp(0.5 * (g["atm"] / 100) ** 2 * T),     # delta-neutral straddle strike
               "25D call": q.fx_strike_from_delta(S, T, rd, rf, g["c25"] / 100, 0.25, call=True),
               "10D call": q.fx_strike_from_delta(S, T, rd, rf, g["c10"] / 100, 0.10, call=True)}
    rows.append({"expiry": g["expiry"], "forward": F, **{f"K {k}": v for k, v in strikes.items()},
                 "RR25 quoted": g["rr25"], "RR25 from vols": g["c25"] - g["p25"],
                 "BF25 quoted": g["bf25"], "BF25 from vols": (g["c25"] + g["p25"]) / 2 - g["atm"],
                 "ATM total variance": (g["atm"] / 100) ** 2 * T})
    ax.plot([strikes[k] / F for k in vols], list(vols.values()), "o-", ms=3, label=g["expiry"])
out = pd.DataFrame(rows).set_index("expiry")
out["calendar ok"] = out["ATM total variance"].diff().fillna(1) > 0   # total variance must rise with expiry
show(out, title=f"{doc['pair']}: smile by expiry (spot {S}, {c['quote']} rates from its OIS curve)")
chart(pd.DataFrame({"ATM vol %": [g["atm"] for g in doc["grid"]]}, index=[g["expiry"] for g in doc["grid"]]),
      kind="line", title="ATM volatility term structure")
ax.set_xlabel("strike / forward")
ax.set_ylabel("vol %")
ax.set_title(f"{doc['pair']} smile by expiry ({doc.get('model', '')})")
ax.legend(fontsize=7)
