#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/counterparty-risk/saccr_recompute.py there. Edit that source, not this file.
# title: SA-CCR exposure at default, recomputed
# description: The SA-CCR calculation rebuilt from its parts: each hedging set's add-on as supervisory factor x effective notional, summed by asset class (no correlation inside a hedging set, a simplification for commodities and equities), the PFE multiplier min(1, 5% + 95% exp((V - C) / (2 x 95% x AddOn))), and EAD = alpha x (RC + multiplier x AddOn), set beside the engine's figures; the add-on by asset class drawn.
# kinds: sa-ccr

import math
import pandas as pd

doc = view.doc
hs = pd.DataFrame(doc["hedgingSets"])
hs["add-on"] = (hs["sf"] * hs["effectiveNotional"]).abs()                 # |SF x effective notional| per hedging set
by_class = hs.groupby("assetClass", as_index=False)["add-on"].sum()
engine = {a["assetClass"]: a["addOn"] for a in doc.get("addOns") or []}
by_class["engine add-on"] = by_class["assetClass"].map(engine)
show(hs, title=f"{view.id}: hedging sets")
show(by_class, title="Add-on by asset class")

ns = await drishti.get_async("netting-set", doc["nettingSet"])
V, C = ns.get("netMtm", 0.0), ns.get("collateral", 0.0)                  # value of the trades, collateral held
addon = by_class["add-on"].sum()
alpha = doc.get("alpha", 1.4)
rc = max(V - C, 0.0)                                                      # unmargined replacement cost (a simplification)
mult = min(1.0, 0.05 + 0.95 * math.exp((V - C) / (2 * 0.95 * addon))) if addon else 1.0
ead = alpha * (rc + mult * addon)
show(pd.DataFrame({
    "measure": ["V (net MTM)", "C (collateral)", "replacement cost", "aggregate add-on", "multiplier", "EAD", "risk weight implied"],
    "recomputed": [V, C, rc, addon, mult, ead, None],
    "engine": [None, None, doc.get("replacementCost"), doc.get("addOn"), doc.get("multiplier"), doc.get("ead"),
               doc.get("rwa", 0) / doc["ead"] if doc.get("ead") else None],
}), title=f"EAD = {alpha} x (RC + multiplier x AddOn)")
chart(by_class, kind="bar", x="assetClass", y=["add-on", "engine add-on"], title="Add-on by asset class")
print(f"EAD recomputed {ead:,.0f} against the engine's {doc.get('ead'):,.0f}: "
      f"{'within 1%' if abs(ead / doc['ead'] - 1) < 0.01 else 'different inputs (maturity factors, supervisory deltas, correlation)'}")
