#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/counterparty-risk/simm_aggregation.py there. Edit that source, not this file.
# title: SIMM: initial margin across risk classes
# description: The SIMM result's initial margin by risk class, the simple sum against the reported total, the total aggregated across risk classes with a correlation matrix in the shape of ISDA SIMM's (illustrative values: use the published table of the version in force), the single flat correlation the reported total implies, the diversification benefit, and margin posted against received.
# kinds: simm

import numpy as np
import pandas as pd

doc = view.doc
im = pd.Series({r["riskClass"]: r["im"] for r in doc["riskClasses"]}, dtype=float).rename_axis("risk class")
CLASSES = ["Interest rate", "Credit qualifying", "Credit non-qualifying", "Equity", "Commodity", "FX"]
PSI = np.array([                                  # illustrative cross-risk-class correlations (the shape of SIMM's table)
    [1.00, 0.04, 0.04, 0.07, 0.37, 0.14],
    [0.04, 1.00, 0.54, 0.70, 0.27, 0.37],
    [0.04, 0.54, 1.00, 0.46, 0.24, 0.15],
    [0.07, 0.70, 0.46, 1.00, 0.35, 0.39],
    [0.37, 0.27, 0.24, 0.35, 1.00, 0.35],
    [0.14, 0.37, 0.15, 0.39, 0.35, 1.00]])
x = np.array([im.get(c, 0.0) for c in CLASSES])
with_psi = float(np.sqrt(x @ PSI @ x))
simple, total = im.sum(), doc["total"]
cross = x.sum() ** 2 - np.sum(x ** 2)                                   # sum over r != s of IM_r IM_s
implied = (total ** 2 - np.sum(x ** 2)) / cross if cross else float("nan")

show(im.to_frame("IM").assign(share=lambda d: d["IM"] / d["IM"].sum()), title=f"{view.id}: {doc.get('version', '')}, {doc.get('nettingSet', '')}")
show(pd.DataFrame({
    "measure": ["simple sum of risk classes", "reported total", "aggregated with the correlation matrix", "diversification (matrix)",
                "implied flat correlation", "posted", "received", "net (received - posted)"],
    "value": [simple, total, with_psi, simple - with_psi, implied, doc.get("posted"), doc.get("received"),
              (doc.get("received") or 0) - (doc.get("posted") or 0)],
}), title="Aggregation across risk classes: sqrt(sum_r sum_s psi_rs IM_r IM_s)")
chart(im.rename("IM").reset_index(), kind="bar", x="risk class", y="IM", title="IM by risk class")
print("The reported total is the simple sum: no diversification across risk classes is taken" if abs(total - simple) < 10 else
      f"The reported total implies a flat cross-class correlation of {implied:.2f}")
