# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Builds a generated domain pack from its kinds and its documents: pack.yaml (kinds, mnemonics, identifier patterns,
link fields, data-domain connectors and routes, example commands), one Markdown Sutra per kind, the samples and
catalogue, an overview guide for the help centre, and optionally the Delta Lake. The banking packs have their own
generators; later packs (liquidity, climate, …) describe themselves with a PackSpec and call build().

Checks before writing: every id field matches its document, every link resolves (to this pack's documents or the
packs it requires), every path a Sutra's header reads is present.
"""
from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[3]
PACKS = ROOT / "packs"
sys.path.insert(0, str(ROOT / "tools" / "packgen" / "banking"))
sys.path.insert(0, str(ROOT / "tools"))
import make_docs as MD  # noqa: E402  (the banking guides' shared sections)
import make_sutras as MS  # noqa: E402  (the Rachana writer the banking packs use)
from risk_model import Kind  # noqa: E402

DOC_HEADER = "\n".join((ROOT / "docs" / "guides" / "RACHANA_REFERENCE.md").read_text(encoding="utf-8").splitlines()[:15])
YAML_HEADER = "\n".join("#" + (" " + x if x.strip() else "") for x in DOC_HEADER.splitlines()[1:14])
PATH = re.compile(r"\$\.([A-Za-z_][A-Za-z0-9_]*)")


@dataclass
class PackSpec:
    name: str
    title: str
    description: str
    requires: list[str]
    domains: dict[str, list[Kind]]                  # data domain -> kinds it holds
    examples: list[tuple[str, str]]
    generator: str                                  # e.g. tools/packgen/liquidity/make.py
    effective_domains: set[str] = field(default_factory=set)
    roles: dict = field(default_factory=dict)
    columns: dict[str, list[str]] = field(default_factory=dict)
    sample: bool = False                            # a demonstration pack (pack.yaml sample: true): see drishti.packs.samples
    code: str = ""                                  # typed alone, opens the pack's overview (pack.yaml code:)   # kind -> key fields shown in pick lists (pack.yaml columns:)
    impact: dict | None = None
    overview: str = ""                              # prose for the overview guide
    external_ids: dict[str, set[str]] = field(default_factory=dict)   # kind -> ids that live in required packs

    @property
    def kinds(self) -> list[Kind]:
        return [k for ks in self.domains.values() for k in ks]


def _generated(spec: PackSpec, what: str) -> str:
    return f"Generated by {spec.generator}. Edit the generator, not this {what}."


def manifest(spec: PackSpec, known_fields: dict[str, tuple[str, str]]) -> dict:
    kinds = spec.kinds
    fields = {}
    for k in kinds:
        for f, (target, label) in k.links.items():
            if f not in known_fields:
                fields[f] = {"kind": target, "label": label}
            elif known_fields[f][0] != target:   # the field already means another kind: its links would go astray
                raise SystemExit(f"{spec.name}: link field '{f}' of {k.kind} points at {target}, but the banking packs map it to "
                                 f"{known_fields[f][0]}; use another field name")
    m = {"pack": spec.name, **({"sample": True} if spec.sample else {}), "version": "1.0.0", **({"code": spec.code} if spec.code else {}), "title": spec.title, "description": spec.description, "extends": spec.requires,
         "kinds": [k.kind for k in kinds], "sutras": "sutras",
         "mnemonics": {k.mnemonic: {"kind": k.kind, "label": k.label} for k in kinds},
         "graph": {"id-patterns": [{"pattern": "^" + k.prefix, "kind": k.kind} for k in kinds], "fields": dict(sorted(fields.items()))},
         "connectors": {}, "routes": {},
         "console": {"examples": [list(e) for e in spec.examples], "help": "config/help.yaml"}}
    badges = {k.kind: k.badge for k in kinds if k.badge}
    if badges:
        m["graph"]["badges"] = badges
    if spec.impact:
        m["graph"]["impact"] = spec.impact
    for d, ks in spec.domains.items():
        settings = {"root": "${DRISHTI_DELTA_ROOT:./data/delta}", "domain": d}
        if d in spec.effective_domains:
            settings.update({f"mode.{k.kind}": "effective" for k in ks})
        m["connectors"][f"{d}-store"] = {"plugin": "delta", "enabled": "${DRISHTI_LAKE_ENABLED:true}", "kinds": [k.kind for k in ks],
                                         "settings": settings}
        m["routes"].update({k.kind: f"{d}-store" for k in ks})
    if spec.columns:
        m["columns"] = spec.columns
    if spec.roles:
        m["roles"] = spec.roles
    return m


def sutra(spec: PackSpec, k: Kind) -> str:
    return MS.kind_doc(k).replace(MS.GENERATED, "# " + _generated(spec, "file"))


def overview(spec: PackSpec, docs: dict) -> str:
    t = MS.md_table
    lines = [DOC_HEADER, "<!-- " + _generated(spec, "file") + " -->", f"# {spec.title} pack", "", spec.description, ""]
    if spec.overview:
        lines += [spec.overview.strip(), ""]
    lines += [f"**Extends:** {', '.join(f'`{r}`' for r in spec.requires) or 'nothing'} · **Kinds:** {len(spec.kinds)}", "",
              f"Enable it with `DRISHTI_PACKS={spec.name}` (the packs it extends come with it).", ""]
    first = spec.kinds[0]
    lines += MD.finding(first.mnemonic, first.label, first.prefix)
    lines += ["## Where the data comes from", ""]
    lines += t(["Connector", "Folder", "Kinds"], [[f"`{d}-store`", f"`data/delta/{d}/`", ", ".join(f"`{k.kind}`" for k in ks)]
                                                  for d, ks in spec.domains.items()])
    lines += ["## Kinds", ""]
    lines += t(["Kind", "Name", "Mnemonic", "Identifiers", "What it is"],
               [[f"`{k.kind}`", k.label, f"`{k.mnemonic}`", f"`{k.prefix}…`", k.desc] for k in spec.kinds])
    for k in spec.kinds:
        fs = list(dict.fromkeys(PATH.findall(" ".join(s[1] for s in k.strip) + " " + " ".join(p.rows or "" for p in k.panels))))
        lines += [f"### {k.label} (`{k.kind}`)", "", k.desc, "", "**Fields its Sutra reads:** " + ", ".join(f"`{f}`" for f in fs) + ".", ""]
        if k.links:
            lines += ["**Links:** " + ", ".join(f"`{f}` → {lab} (`{kind}`)" for f, (kind, lab) in k.links.items()) + ".", ""]
    return "\n".join(lines).rstrip() + "\n"


def check(spec: PackSpec, docs: dict) -> list[str]:
    problems = []
    for k in spec.kinds:
        need = set(PATH.findall(" ".join(s[1] for s in k.strip))) | {m for p in k.panels if p.rows for m in PATH.findall(p.rows)}
        for id_, d in docs.get(k.kind, {}).items():
            if d.get(k.id_field) != id_:
                problems.append(f"{k.kind}/{id_}: id field {k.id_field} is {d.get(k.id_field)!r}")
            missing = sorted(f for f in need if f not in d)
            if missing:
                problems.append(f"{k.kind}/{id_}: missing {missing}")
            for f, (target, _) in k.links.items():
                v = d.get(f)
                vals = [v] if isinstance(v, str) else [x for x in v if isinstance(x, str)] if isinstance(v, list) else []
                for x in vals:
                    if x not in docs.get(target, {}) and x not in spec.external_ids.get(target, set()):
                        problems.append(f"{k.kind}/{id_}: {f} -> {target}/{x} does not exist")
    return problems


def files(spec: PackSpec, docs: dict, known_fields: dict) -> dict[Path, str]:
    base = PACKS / spec.name
    out: dict[Path, str] = {}
    out[base / "pack.yaml"] = (f"{YAML_HEADER}\n\n# {_generated(spec, 'file')}\n# {spec.title} pack for Drishti.\n"
                               + yaml.safe_dump(manifest(spec, known_fields), sort_keys=False, allow_unicode=True, width=140))
    for k in spec.kinds:
        out[base / "sutras" / MS.slug(k.group) / f"{k.kind}.v1.sutra.yaml"] = sutra(spec, k)
    catalog = []
    for k in spec.kinds:
        for id_, d in sorted(docs.get(k.kind, {}).items()):
            out[base / "samples" / k.kind / f"{id_}.json"] = json.dumps(d, indent=1, ensure_ascii=False) + "\n"
            sub = next((d[f] for f in ("name", "legalEntityName", "scenarioName", "counterpartyName", "security") if isinstance(d.get(f), str)), "")
            catalog.append({"kind": k.kind, "id": id_, "title": id_, "subtitle": f"{k.label}" + (f" · {sub}" if sub else "")})
    out[base / "samples" / "catalog.json"] = json.dumps(catalog, indent=1, ensure_ascii=False) + "\n"
    out[base / "guides" / f"{spec.name}.md"] = overview(spec, docs)
    help_yaml = yaml.safe_dump({"guides": [{"slug": spec.name, "category": "packs", "title": f"{spec.title} pack", "icon": "box-seam",
                                            "file": f"guides/{spec.name}.md", "summary": spec.description}]}, sort_keys=False, allow_unicode=True)
    out[base / "config" / "help.yaml"] = f"{YAML_HEADER}\n\n# {_generated(spec, 'file')}\n{help_yaml}"
    gen_dir = (ROOT / spec.generator).parent                  # hand-written about text: see docs/architecture/CONTEXT_HELP.md
    for src in sorted(gen_dir.glob("about.yaml")) + sorted(gen_dir.glob("about.*.yaml")):
        lang = src.name[len("about."):-len(".yaml")] if src.name != "about.yaml" else ""
        what = "what the pack's kinds mean" if not lang else f"the {lang} translation overlay of about.yaml"
        lines = src.read_text(encoding="utf-8").split("\n")
        while lines and (lines[0].startswith("#") or not lines[0].strip()):
            lines.pop(0)                                       # the source's own licence header: the generator writes one
        out[base / "config" / src.name] = f"{YAML_HEADER}\n\n# {_generated(spec, 'file')}\n# About this page: {what}.\n" + "\n".join(lines)
    return out


def main(spec: PackSpec, docs: dict, known_fields: dict, lake_kinds_by_domain=None) -> None:
    problems = check(spec, docs)
    if problems:
        raise SystemExit(f"{spec.name} data is inconsistent:\n  " + "\n  ".join(problems[:30]))
    want = files(spec, docs, known_fields)
    base = PACKS / spec.name
    existing = {f for sub in ("samples", "sutras") if (base / sub).exists() for f in (base / sub).rglob("*") if f.is_file()}
    if "--check" in sys.argv:
        stale = [str(f) for f, t in want.items() if not f.exists() or f.read_text(encoding="utf-8") != t]
        extra = [str(f) for f in existing - set(want)]
        if stale or extra:
            raise SystemExit(f"{spec.name} pack out of date; run {spec.generator}. stale={stale[:3]} extra={extra[:3]}")
        print(f"{spec.name}: {len(want)} files up to date")
        return
    for f in existing - set(want):
        f.unlink()
    for f, t in want.items():
        f.parent.mkdir(parents=True, exist_ok=True)
        if not f.exists() or f.read_text(encoding="utf-8") != t:
            f.write_text(t, encoding="utf-8")
    print(f"{spec.name}: wrote {len(want)} files ({sum(len(v) for v in docs.values())} documents, {len(spec.kinds)} kinds)")
    if "--lake" in sys.argv:
        from samplegen.dates import Calendar
        from samplegen.lake import write_tables
        from samplegen.layout import layouts_for_domain

        root = Path(sys.argv[sys.argv.index("--lake") + 1])
        from datetime import date
        end = date(2026, 9, 30)
        for d, ks in spec.domains.items():
            write_tables(root / d, {k.kind: docs.get(k.kind, {}) for k in ks}, end, 10, Calendar.of("USNY"), layouts_for_domain(d))
