#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-risk/stress_heatmap.py there. Edit that source, not this file.
# title: Stress results: scenarios by desk, limits and the worst case
# description: Every stress result in one search, pivoted scenario by desk with totals; each desk's worst scenario and its use of the stress limit (results read in full for their limits), the scenarios ranked by firm-wide loss, and a heatmap of the matrix (matplotlib).
# kinds: stress-result, stress-scenario

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

res = await drishti.search_async("STR where pnl < 1000bn and scenario != '' and desk != '' limit 1000")
matrix = res.pivot_table(index="scenario", columns="desk", values="pnl", aggfunc="sum")
matrix["firm"] = matrix.sum(axis=1)
matrix = matrix.sort_values("firm")
show(matrix, title=f"Stress P&L by scenario and desk ({len(res)} results)")

worst = res.loc[res.groupby("desk")["pnl"].idxmin()].set_index("desk")
limits = {}
for rid in worst["id"]:
    d = await drishti.get_async("stress-result", rid)
    limits[d["desk"]] = d.get("limit")
worst["limit"] = worst.index.map(limits)
worst["limit use"] = worst["pnl"] / worst["limit"]                    # both negative: the share of the loss limit used
worst["status"] = np.where(worst["limit use"] >= 1, "breach", np.where(worst["limit use"] >= 0.8, "early warning", "ok"))
show(worst[["scenario", "pnl", "limit", "limit use", "status"]].sort_values("limit use", ascending=False),
     title="Each desk's worst scenario against its stress limit")
print(f"Worst firm-wide scenario: {matrix.index[0]} ({matrix['firm'].iloc[0]:,.0f}); "
      f"{(worst['status'] == 'breach').sum()} desks breach their stress limit in their worst scenario")

m = matrix.drop(columns="firm") / 1e6
lim = np.nanmax(np.abs(m.to_numpy()))
fig, ax = plt.subplots(figsize=(8, 3.8))
im = ax.imshow(m.to_numpy(), cmap="RdYlGn", vmin=-lim, vmax=lim, aspect="auto")
ax.set_xticks(range(len(m.columns)), [c.replace("DESK-", "") for c in m.columns], rotation=30, ha="right", fontsize=7)
ax.set_yticks(range(len(m.index)), [s.replace("SCN-", "") for s in m.index], fontsize=7)
for (i, j), v in np.ndenumerate(m.to_numpy()):
    ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6)
ax.set_title("Stress P&L, millions")
fig.colorbar(im, ax=ax, shrink=0.8)
