#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/market-risk/var_factor_regression.py there. Edit that source, not this file.
# title: Desk P&L regressed on market factors (statsmodels)
# description: The desk's daily P&L series regressed with statsmodels OLS on daily returns of market factors taken from the daily bars Drishti holds (oil, gold, copper and two equities as proxies; edit FACTORS), aligned by date: the summary, the factor betas in P&L per 1% move with confidence intervals, R squared and the residual volatility, and the factor that explains most.
# kinds: var

import numpy as np
import pandas as pd
import statsmodels.api as sm

FACTORS = {"oil": ("commodity", "CMD-WTI"), "gold": ("commodity", "CMD-GOLD"), "copper": ("commodity", "CMD-COPPER"),
           "equity NVTK": ("equity", "EQ-NVTK"), "equity GRNT": ("equity", "EQ-GRNT")}
pnl = pd.DataFrame(view.doc["pnlSeries"]).set_index("date")["pnl"].astype(float)
rets = {}
for name, (kind, fid) in FACTORS.items():
    bars = (await drishti.get_async(kind, fid)).get("ohlc") or []
    close = pd.Series({b["date"]: b["close"] for b in bars}, dtype=float).sort_index()
    rets[name] = np.log(close).diff() * 100                       # daily log return in %
X = pd.DataFrame(rets)
data = pd.concat([pnl.rename("pnl"), X], axis=1, join="inner").dropna()
if len(data) < len(FACTORS) + 5:
    raise ValueError(f"only {len(data)} days line up between the P&L and the factors")

model = sm.OLS(data["pnl"], sm.add_constant(data[list(FACTORS)])).fit()
print(model.summary(title=f"{view.doc.get('desk', view.id)} daily P&L on factor returns (%), {len(data)} days"))
ci = model.conf_int()
betas = pd.DataFrame({"P&L per 1% move": model.params, "95% low": ci[0], "95% high": ci[1], "p-value": model.pvalues}).drop("const").rename_axis("factor")
betas["significant (5%)"] = betas["p-value"] < 0.05
show(betas, title=f"Factor betas (R squared {model.rsquared:.2f}, adjusted {model.rsquared_adj:.2f})")
contrib = ((data[list(FACTORS)] * model.params[list(FACTORS)]).var() / data["pnl"].var()).rename_axis("factor")
show(contrib.sort_values(ascending=False).to_frame("share of P&L variance (no covariances)"), title="Which factor explains most")
print(f"Residual volatility {np.sqrt(model.scale):,.0f} a day against P&L volatility {data['pnl'].std(ddof=1):,.0f}: "
      f"{'the factors explain little; look elsewhere (book-level risk, idiosyncratic moves)' if model.rsquared < 0.3 else 'a usable factor model'}")
chart(pd.DataFrame({"actual": data["pnl"], "fitted": model.fittedvalues}), kind="line", title="Actual against fitted daily P&L")
