/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.kafka;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.EntityRef;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.TestPki;
import com.github.dockerjava.api.model.ExposedPort;
import com.github.dockerjava.api.model.PortBinding;
import com.github.dockerjava.api.model.Ports;
import java.net.ServerSocket;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.TimeUnit;
import java.util.function.BooleanSupplier;
import org.apache.kafka.clients.admin.Admin;
import org.apache.kafka.clients.admin.ScramCredentialInfo;
import org.apache.kafka.clients.admin.ScramMechanism;
import org.apache.kafka.clients.admin.UserScramCredentialUpsertion;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * The Kafka connector against a real Apache Kafka 3.9 broker in Docker with two secured listeners: {@code TLS}
 * (SSL, client certificate required) and {@code SASL} (SASL_SSL, SCRAM). The certificates are generated by the test; the
 * broker is bound to 127.0.0.1 on two free ports and removed afterwards. Skipped where Docker or the image is not available.
 */
class KafkaSecureBrokerTest {

    static final String IMAGE = "apache/kafka:3.9.1";
    static GenericContainer<?> broker;
    static int tlsPort;
    static int saslPort;
    static Path dir;
    static TestPki.Identity ca;
    static TestPki.Identity drishti;

    @BeforeAll
    static void start() throws Exception {
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
            if (docker) {
                org.testcontainers.DockerClientFactory.lazyClient().inspectImageCmd(IMAGE).exec();
            }
        } catch (RuntimeException e) {
            docker = false;
        }
        org.junit.jupiter.api.Assumptions.assumeTrue(docker, "Docker and the image " + IMAGE + " are needed");
        dir = Files.createTempDirectory("kafka-tls");
        ca = TestPki.ca("test-ca");
        TestPki.Identity server = TestPki.issue(ca, "broker", "RSA", 30);
        drishti = TestPki.issue(ca, "drishti", "EC", 30);
        server.writeKeystore(dir.resolve("broker.p12"), "PKCS12", "changeit", "broker", "changeit");
        TestPki.writeTruststore(dir.resolve("truststore.p12"), "PKCS12", "changeit", ca.cert());
        ca.writeCertPem(dir.resolve("ca.pem"));
        drishti.writeCertPem(dir.resolve("client.pem"));
        drishti.writeKeyPem(dir.resolve("client.key"), TestPki.KeyFormat.PKCS8, null);
        drishti.writeKeystore(dir.resolve("client.p12"), "PKCS12", "clientpw", "drishti", "clientpw");
        TestPki.writeTruststore(dir.resolve("client-trust.jks"), "JKS", "trustpw", ca.cert());
        Files.writeString(dir.resolve("jaas.conf"), "KafkaServer {\n  org.apache.kafka.common.security.scram.ScramLoginModule required;\n};\n");
        tlsPort = freePort();
        saslPort = freePort();

        GenericContainer<?> c = new GenericContainer<>(IMAGE)
                .withNetworkAliases("kafka")
                .withEnv("KAFKA_NODE_ID", "1")
                .withEnv("KAFKA_PROCESS_ROLES", "broker,controller")
                .withEnv("KAFKA_LISTENERS", "TLS://:9093,SASL://:9094,CONTROLLER://:9095,INTERNAL://:9096")
                .withEnv("KAFKA_ADVERTISED_LISTENERS", "TLS://localhost:" + tlsPort + ",SASL://localhost:" + saslPort + ",INTERNAL://localhost:9096")
                .withEnv("KAFKA_LISTENER_SECURITY_PROTOCOL_MAP", "TLS:SSL,SASL:SASL_SSL,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT")
                .withEnv("KAFKA_INTER_BROKER_LISTENER_NAME", "INTERNAL")
                .withEnv("KAFKA_CONTROLLER_LISTENER_NAMES", "CONTROLLER")
                .withEnv("KAFKA_CONTROLLER_QUORUM_VOTERS", "1@localhost:9095")
                .withEnv("KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR", "1")
                .withEnv("KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR", "1")
                .withEnv("KAFKA_TRANSACTION_STATE_LOG_MIN_ISR", "1")
                .withEnv("KAFKA_HEAP_OPTS", "-Xmx512m -Xms256m")
                .withEnv("KAFKA_SSL_KEYSTORE_LOCATION", "/etc/kafka/secrets/broker.p12")
                .withEnv("KAFKA_SSL_KEYSTORE_PASSWORD", "changeit")
                .withEnv("KAFKA_SSL_KEY_PASSWORD", "changeit")
                .withEnv("KAFKA_SSL_KEYSTORE_TYPE", "PKCS12")
                .withEnv("KAFKA_SSL_TRUSTSTORE_LOCATION", "/etc/kafka/secrets/truststore.p12")
                .withEnv("KAFKA_SSL_TRUSTSTORE_PASSWORD", "changeit")
                .withEnv("KAFKA_SSL_TRUSTSTORE_TYPE", "PKCS12")
                .withEnv("KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM", "")
                .withEnv("KAFKA_LISTENER_NAME_TLS_SSL_CLIENT_AUTH", "required")
                .withEnv("KAFKA_SASL_ENABLED_MECHANISMS", "SCRAM-SHA-256,SCRAM-SHA-512")
                .withEnv("KAFKA_OPTS", "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf")
                .withCreateContainerCmdModifier(cmd -> cmd.getHostConfig().withPortBindings(
                        new PortBinding(Ports.Binding.bindIpAndPort("127.0.0.1", tlsPort), new ExposedPort(9093)),
                        new PortBinding(Ports.Binding.bindIpAndPort("127.0.0.1", saslPort), new ExposedPort(9094))))
                .withExposedPorts(9093, 9094)
                .waitingFor(Wait.forLogMessage(".*Kafka Server started.*", 1).withStartupTimeout(Duration.ofSeconds(120)));
        for (String f : List.of("broker.p12", "truststore.p12", "jaas.conf")) {
            c.withCopyFileToContainer(MountableFile.forHostPath(dir.resolve(f), 0644), "/etc/kafka/secrets/" + f);
        }
        broker = c;
        broker.start();
        // the SCRAM user is created over the mutual-TLS listener
        try (Admin admin = Admin.create(adminProps(tlsSettings("pem")))) {
            admin.alterUserScramCredentials(List.of(new UserScramCredentialUpsertion("alice",
                    new ScramCredentialInfo(ScramMechanism.SCRAM_SHA_512, 4096), "alice-secret"))).all().get(30, TimeUnit.SECONDS);
        }
    }

    @AfterAll
    static void stop() throws Exception {
        if (broker != null) {
            broker.stop();
        }
        if (dir != null) {
            try (var files = Files.walk(dir)) {
                files.sorted(java.util.Comparator.reverseOrder()).forEach(p -> p.toFile().delete());
            }
        }
    }

    static int freePort() throws Exception {
        try (ServerSocket s = new ServerSocket(0)) {
            return s.getLocalPort();
        }
    }

    /** Settings for the mutual-TLS listener, with the identity and trust in the given form: pem, pkcs12 or merged. */
    static Map<String, String> tlsSettings(String form) {
        Map<String, String> s = new HashMap<>();
        s.put("bootstrap-servers", "localhost:" + tlsPort);
        s.put("security.protocol", "SSL");
        switch (form) {
            case "pem" -> {
                s.put("tls.ca-file", dir.resolve("ca.pem").toString());
                s.put("tls.cert-file", dir.resolve("client.pem").toString());
                s.put("tls.key-file", dir.resolve("client.key").toString());
            }
            case "pkcs12" -> {
                s.put("tls.truststore", dir.resolve("client-trust.jks").toString());
                s.put("tls.truststore-password", "trustpw");
                s.put("tls.keystore", dir.resolve("client.p12").toString());
                s.put("tls.keystore-password", "clientpw");
            }
            default -> {                      // PEM CA merged with a JKS truststore, PKCS12 identity, one alias
                s.put("tls.ca-file", dir.resolve("ca.pem").toString());
                s.put("tls.truststore", dir.resolve("client-trust.jks").toString());
                s.put("tls.truststore-password", "trustpw");
                s.put("tls.keystore", dir.resolve("client.p12").toString());
                s.put("tls.keystore-password", "clientpw");
                s.put("tls.key-alias", "drishti");
            }
        }
        return s;
    }

    static Map<String, String> saslSettings(String user, String password, String mechanism) {
        Map<String, String> s = new HashMap<>();
        s.put("bootstrap-servers", "localhost:" + saslPort);
        s.put("security.protocol", "SASL_SSL");
        s.put("sasl.mechanism", mechanism);
        s.put("sasl.username", user);
        s.put("sasl.password", password);
        s.put("tls.ca-file", dir.resolve("ca.pem").toString());
        return s;
    }

    static Properties adminProps(Map<String, String> settings) {
        Properties p = KafkaSourcePlugin.consumerProperties(settings, "test", KafkaSecurity.translate(settings));
        p.keySet().removeIf(k -> k.toString().contains("deserializer") || k.equals("enable.auto.commit") || k.equals("group.id"));
        p.put("request.timeout.ms", "8000");
        p.put("default.api.timeout.ms", "10000");
        return p;
    }

    static void produce(Map<String, String> settings, String topic, String key, String value) throws Exception {
        Properties p = adminProps(settings);
        p.put("key.serializer", StringSerializer.class.getName());
        p.put("value.serializer", StringSerializer.class.getName());
        try (KafkaProducer<String, String> producer = new KafkaProducer<>(p)) {
            producer.send(new ProducerRecord<>(topic, key, value)).get(30, TimeUnit.SECONDS);
        }
    }

    /** Connects the connector with these settings, produces a trade, and waits until the connector has read it. */
    void roundTrip(Map<String, String> settings, String topic) throws Exception {
        Map<String, String> s = new HashMap<>(settings);
        s.put("topics", topic);
        s.put("kind." + topic, "trade");
        s.put("id-field." + topic, "tradeId");
        s.put("poll-ms", "50");
        s.put("source-name", topic);
        produce(settings, topic, "T-1", "{\"tradeId\":\"T-1\",\"mtm\":42}");
        KafkaSourcePlugin plugin = new KafkaSourcePlugin();
        plugin.start(DatedSourceContract.context(s));
        try {
            waitFor(() -> plugin.fetch(EntityRef.of("trade", "T-1")).isPresent(), 60);
            assertThat(plugin.fetch(EntityRef.of("trade", "T-1")).orElseThrow().data().get("mtm").asDouble()).isEqualTo(42);
            assertThat(plugin.health()).startsWith("UP");
        } finally {
            plugin.close();
        }
    }

    static void waitFor(BooleanSupplier ok, int seconds) throws InterruptedException {
        long until = System.nanoTime() + TimeUnit.SECONDS.toNanos(seconds);
        while (!ok.getAsBoolean() && System.nanoTime() < until) {
            Thread.sleep(100);
        }
        assertThat(ok.getAsBoolean()).as("condition within " + seconds + " s").isTrue();
    }

    @Test
    void mutualTlsWithPemFiles() throws Exception {
        roundTrip(tlsSettings("pem"), "pem-trades");
    }

    @Test
    void mutualTlsWithPkcs12KeystoreAndJksTruststore() throws Exception {
        roundTrip(tlsSettings("pkcs12"), "p12-trades");
    }

    @Test
    void mutualTlsWithMergedTrustAndAKeystoreAlias() throws Exception {
        roundTrip(tlsSettings("merged"), "merged-trades");
    }

    @Test
    void saslSslWithScram512() throws Exception {
        roundTrip(saslSettings("alice", "alice-secret", "SCRAM-SHA-512"), "scram-trades");
    }

    @Test
    void aWrongScramPasswordIsRefused() {
        Map<String, String> s = saslSettings("alice", "wrong", "SCRAM-SHA-512");
        assertThatThrownBy(() -> {
            try (Admin admin = Admin.create(adminProps(s))) {
                admin.listTopics().names().get(15, TimeUnit.SECONDS);
            }
        }).hasMessageContaining("Authentication failed");
    }

    @Test
    void theMutualTlsListenerRefusesAClientWithoutACertificate() {
        Map<String, String> s = tlsSettings("pem");
        s.remove("tls.cert-file");
        s.remove("tls.key-file");
        assertThatThrownBy(() -> {
            try (Admin admin = Admin.create(adminProps(s))) {
                admin.listTopics().names().get(15, TimeUnit.SECONDS);
            }
        }).isInstanceOf(Exception.class);
    }

    @Test
    void aClientThatDoesNotTrustTheBrokersCaIsRefused() throws Exception {
        Map<String, String> s = tlsSettings("pem");
        TestPki.ca("rogue-ca").writeCertPem(dir.resolve("rogue.pem"));
        s.put("tls.ca-file", dir.resolve("rogue.pem").toString());      // trusts another authority, not the broker's
        assertThatThrownBy(() -> {
            try (Admin admin = Admin.create(adminProps(s))) {
                admin.listTopics().names().get(15, TimeUnit.SECONDS);
            }
        }).isInstanceOf(Exception.class);
    }
}
