#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/trading/fx_forward_mtm.py there. Edit that source, not this file.
# title: FX forward: mark to market from the forward curve
# description: The FX forward (or NDF) marked against today's forward outright at its value date, interpolated on the forward curve's points (linear in time), discounted on the quote currency's OIS curve: forward points, the MTM in the quote currency and in USD, the implied yield differential, and the P&L for spot moves of -5% to +5% with the points held (first order).
# kinds: trade

from datetime import date
import math
import numpy as np
import pandas as pd
from drishti import quant as q

doc, t = view.doc, view.doc.get("terms") or {}
if "rate" not in t or not doc.get("fxSpot"):
    raise ValueError(f"{view.id} ({doc.get('productType')}) is not an FX forward or NDF")
spot = await drishti.get_async("fx-spot", doc["fxSpot"])
fwd = await drishti.get_async("fx-forward-curve", doc.get("fxForwardCurve") or spot["fxForwardCurve"])
c = spot["conventions"]
S, pip, K = spot["mid"], c.get("pipFactor", 10000), t["rate"]
value_date = t.get("valueDate") or t.get("fixingDate") or doc["maturityDate"]
T = max((date.fromisoformat(value_date) - date.fromisoformat(view.business_date or "2026-09-30")).days / 365, 0.0)
pts = sorted((q.tenor_years(p["tenor"]), p["pips"]) for p in fwd["points"])
points = float(np.interp(T, [0.0] + [p[0] for p in pts], [0.0] + [p[1] for p in pts]))
F = S + points / pip
try:
    df = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", f"CRV-{c['quote']}-OIS"))["points"]).df(T)
except drishti.DrishtiError:
    df = 1.0
sign = 1 if doc["direction"] in ("Buy", "Long", "Receive fixed") else -1          # long the base currency forward
units = doc["notional"] * sign                                                      # notional read as base-currency units
mtm_quote = units * (F - K) * df
to_usd = 1.0 if c["quote"] == "USD" else (1 / S if c["base"] == "USD" else None)
show(pd.DataFrame({
    "measure": ["spot", "value date", "years", "forward points (interpolated)", "market forward", "contract rate",
                "discount factor", f"MTM ({c['quote']})", "MTM (USD)", "booked MTM (USD)", "implied r_quote - r_base"],
    "value": [S, value_date, T, points, F, K, df, mtm_quote, mtm_quote * to_usd if to_usd else None, doc["mtm"],
              f"{math.log(F / S) / T:.3%}" if T > 0 else None],
}), title=f"{view.id}: {doc['direction']} {abs(units):,.0f} {c['base']}/{c['quote']} at {K}")
if not 0.5 < K / S < 2:
    print(f"The contract rate {K} is far from spot {S} (sample data), so the MTM is large and not comparable with the booking")
ladder = pd.DataFrame({"spot move %": np.arange(-5, 5.1, 1.0)})
ladder[f"MTM ({c['quote']})"] = [units * (F * (1 + m / 100) - K) * df for m in ladder["spot move %"]]
chart(ladder, kind="line", x="spot move %", y=f"MTM ({c['quote']})", title="MTM against a spot move, points unchanged")
