#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from calc_snippets.py. Edit the generator, not this file.
# title: MTM under parallel rate moves
# description: The trade's MTM after parallel moves of -100 to +100 bp from its DV01 (first order), and the tenors that drive it.
# kinds: trade

import pandas as pd

doc = view.doc
mtm = doc["mtm"]
dv01 = (doc.get("risk") or {}).get("dv01")
if not dv01:
    raise ValueError(f"{view.id} has no risk.dv01: this snippet is for rate-sensitive trades")

moves = pd.DataFrame({"shift_bp": [-100, -50, -25, -10, -1, 0, 1, 10, 25, 50, 100]})
moves["pnl"] = moves["shift_bp"] * dv01          # DV01: the change in value for +1 bp
moves["mtm"] = mtm + moves["pnl"]
show(moves, title=f"{view.id}: MTM {mtm:,.0f}, DV01 {dv01:,.0f} per bp")
chart(moves, kind="line", x="shift_bp", y="mtm", title="MTM after a parallel move (bp)")

buckets = pd.DataFrame(doc.get("sensitivities") or [])
if len(buckets):
    buckets["share"] = buckets["dv01"] / buckets["dv01"].sum()
    show(buckets, title="DV01 by tenor")
    chart(buckets, kind="bar", x="bucket", y="dv01", title="DV01 by tenor")
