#   Project Drishti · Any data. Any domain. One grammar.
#
#   Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
#   All rights reserved.
#
#   PROPRIETARY AND CONFIDENTIAL.
#
#   This file is the confidential and proprietary property of Ashutosh Sinha.
#   Unauthorised copying, use, modification, distribution or disclosure of this
#   file, via any medium, is strictly prohibited except with the express prior
#   written permission of the copyright holder.
#
#   See the LICENSE file in the root of this repository for the full terms.

# Generated by tools/packgen/banking/make_packs.py from snippets/trading/swap_reprice.py there. Edit that source, not this file.
# title: Swap legs repriced off the curves
# description: Every unsettled cashflow of the swap's legs: fixed amounts as booked, floating amounts re-projected from the forward curve (simple forwards over each accrual period plus the spread; a period already fixing keeps its booked amount), all discounted on the discount curve; each leg's PV against the booked PV, and a cashflow ladder by year.
# kinds: trade

from datetime import date
import pandas as pd
from drishti import quant as q

doc = view.doc
if not doc.get("legs"):
    raise ValueError(f"{view.id} ({doc.get('productType')}) has no legs: this snippet is for swaps")
as_of = date.fromisoformat(view.business_date or doc.get("valuation", {}).get("asOf", "2026-09-30"))
yrs = lambda d: (date.fromisoformat(d) - as_of).days / 365.0                       # noqa: E731 - ACT/365F from today
disc = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", doc["discountCurve"]))["points"])
proj = disc
if doc.get("forwardCurve"):
    proj = q.ZeroCurve.from_points((await drishti.get_async("ir-curve", doc["forwardCurve"]))["points"])

flows, legs = [], []
for leg in doc["legs"]:
    sign = -1 if leg.get("payer") else 1
    for cf in leg["cashflows"]:
        if cf.get("status") == "Settled" or yrs(cf["payDate"]) <= 0:
            continue
        amount = cf["amount"]
        if leg["type"] == "FLOAT" and yrs(cf["accrualStart"]) > 0:                # not fixed yet: project it
            fwd = proj.forward(yrs(cf["accrualStart"]), yrs(cf["accrualEnd"]))
            amount = sign * cf["notional"] * (fwd + (cf.get("spread") or 0)) * cf["yearFraction"]
        t = yrs(cf["payDate"])
        flows.append({"leg": leg["leg"], "type": leg["type"], "payDate": cf["payDate"], "years": t, "booked": cf["amount"],
                      "repriced": amount, "df": disc.df(t), "pv": amount * disc.df(t), "booked pv": cf.get("pv")})
cf = pd.DataFrame(flows)
by_leg = cf.groupby(["leg", "type"]).agg(flows=("pv", "size"), pv=("pv", "sum"), booked_pv=("booked pv", "sum")).reset_index()
by_leg["leg pv (booked)"] = [next(l["pv"] for l in doc["legs"] if l["leg"] == n) for n in by_leg["leg"]]
by_leg["difference"] = by_leg["pv"] - by_leg["leg pv (booked)"]
show(by_leg, title=f"{view.id}: legs repriced on {doc['discountCurve']} / {doc.get('forwardCurve', doc['discountCurve'])}")
print(f"Net PV repriced {cf['pv'].sum():,.0f} against the booked legs {sum(l['pv'] for l in doc['legs']):,.0f} "
      f"(trade MTM {doc['mtm']:,.0f} {doc.get('mtmCurrency', '')})")
show(cf, title="Unsettled cashflows")
cf["year"] = cf["payDate"].str[:4]
ladder = cf.pivot_table(index="year", columns="type", values="repriced", aggfunc="sum", fill_value=0)
chart(ladder, kind="bar", title="Cashflows by year (repriced, undiscounted)")
