# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Writes the banking packs' documentation (packs/<pack>/guides/*.md and config/help.yaml) from the taxonomy, the
layout and the generated data, so it cannot drift from what the packs contain: an overview per pack, the product
catalogue, the market-data catalogue and the cross-pack data model. The help centre shows them under Domain packs.

    python3 tools/packgen/banking/make_docs.py            write the guides
    python3 tools/packgen/banking/make_docs.py --check    fail if they differ from what would be written
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import yaml

import layout
import make_data
import make_packs
import taxonomy as T
import trade_shape as S

ROOT = Path(__file__).resolve().parents[3]
PACKS = ROOT / "packs"
HEADER = "\n".join((ROOT / "docs" / "RACHANA_REFERENCE.md").read_text(encoding="utf-8").splitlines()[:15])
GENERATED = "<!-- Generated by tools/packgen/banking/make_docs.py. Edit the generator or the taxonomy, not this file. -->"
SPEC = {k.kind: k for k in T.KINDS + [T.TRADE]}


def table(head: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ") for c in r) + " |" for r in rows]
    return out + [""]


def fields_of(k) -> list[str]:
    import re
    names = []
    for s in k.strip:
        names += re.findall(r"\$\.([A-Za-z0-9_]+)", s[1])
    for p in k.panels:
        if p.rows:
            names += re.findall(r"\$\.([A-Za-z0-9_]+)", p.rows)
    return list(dict.fromkeys(names))


def shown_prefix(spec) -> str:
    """How a kind's identifiers begin, for the guides: trades carry their booking system's prefix (booking.py)."""
    return "MX-…`, `CLY-…`, `END-…`, `IMG-…`, `BBG-…`, `WSS-" if spec.kind == "trade" else spec.prefix


def finding(mnemonic: str, label: str, prefix: str, field_example: str = "") -> list[str]:
    """How to open and search a pack's documents, with placeholders rather than sample ids: the guides describe the
    pack, and the documents a site holds are its own."""
    what = label if any(c.isupper() for c in label.split()[0][1:]) else label[:1].lower() + label[1:]
    whats = what[:-1] + "ies" if what.endswith("y") and what[-2:-1] not in "aeiou" else what + "es" if what.endswith(("s", "x", "ch", "sh")) else what + "s"
    by_field = "Lists by field value" + (f", for example `{mnemonic} {field_example}`" if field_example else "") + \
        ". Compare with `<` and `>`, combine with `and`, sort with `order by <field> desc`."
    return ["## Finding things", "",
            f"Every kind has a mnemonic (see *Kinds*). Type it with an identifier, the start of one, or a search, then `<GO>`. "
            f"Shown here for {whats}; the same works for every mnemonic.", ""] + table(["Command", "Does"], [
        [f"`{mnemonic} <id> <GO>`", f"Opens that {what}. A bare identifier works too: its prefix (`{prefix}…`) tells Drishti the kind."],
        [f"`{mnemonic} <start of an id> <GO>`", "A pick list: one match opens, several give a table with the kind's key fields. "
                                                 "`*` is a wildcard, and case never matters."],
        [f"`{mnemonic} <field>=<value> <GO>`", by_field],
        [f"`{mnemonic} <GO>`", f"Lists every {what}."]])


def overview(name: str, docs: dict) -> str:
    p = layout.PACKS[name]
    kinds = [k for ks in p["kinds"].values() for k in ks]
    lines = [HEADER, GENERATED, f"# {p['title']} pack", "", p["description"], ""]
    req = p["requires"]
    needed_by = [n for n, q in layout.PACKS.items() if name in q["requires"]]
    lines += [f"**Extends:** {', '.join(f'`{r}`' for r in req) if req else 'nothing (it is the base)'} · "
              f"**Extended by:** {', '.join(f'`{r}`' for r in needed_by) or 'none'} · "
              f"**Kinds:** {len(kinds)}", "",
              "Enable it with `DRISHTI_PACKS=" + name + "` (the packs it extends come with it; where they differ, the more specific wins).", ""]
    first = SPEC["trade"] if "trade" in kinds else SPEC[kinds[0]]
    lines += finding(first.mnemonic, first.label, shown_prefix(first), "productType=IRS_FIXFLOAT" if first.kind == "trade" else "")
    lines += ["## Where the data comes from", "",
              "Each kind is read from the Delta Lake folder of its **data domain** (`data/delta/<domain>/<kind>/`, partitioned by "
              "business date). Pick a date in the top bar to see that day; **Live** reads the streaming source first.", ""]
    rows = []
    for d, ks in p["kinds"].items():
        mode = "effective (a row when an entity changes)" if d in make_packs.EFFECTIVE_DOMAINS else "snapshot (every business date)"
        rows.append([f"`{d}-store`", f"`data/delta/{d}/`", layout.DOMAINS[d], mode, ", ".join(f"`{k}`" for k in ks)])
    lines += table(["Connector", "Folder", "Domain", "Tables", "Kinds"], rows)
    if name == "market-data":
        lines += ["### Public data feeds", "", "Real market data from public sources, each its own connector and **off by default**. Switch one "
                  "on with its environment variable (or `drishti.sources.connectors.<name>.enabled: true` in the site configuration). "
                  "Feed data has its own identifiers, so it never collides with the bank's own, and it keeps its history, so a picked "
                  "date shows that day's value.", ""]
        lines += table(["Connector", "Switch", "Kind", "What"], [[f"`{f}-feed`", f"`{sw}=true`", ", ".join(f"`{k}`" for k in ks), what]
                                                                 for f, (sw, ks, _, what) in make_packs.FEEDS.items()])
    lines += ["Load real data into each domain's folder, or point a domain at a database instead by overriding its connector in the "
              "site configuration. For a demonstration lake built from the generated samples, run "
              "`uv run --with deltalake --with pyarrow python tools/packgen/banking/make_data.py --lake data/delta`.", ""]
    lines += ["## Kinds", ""]
    rows = []
    for k in kinds:
        s = SPEC[k]
        rows.append([f"`{k}`", s.label, f"`{s.mnemonic}`", f"`{shown_prefix(s)}…`", f"`{s.id_field}`", s.desc])
    lines += table(["Kind", "Name", "Mnemonic", "Identifiers", "Id field", "What it is"], rows)
    for k in kinds:
        s = SPEC[k]
        if k == "trade":
            continue
        lines += [f"### {s.label} (`{k}`)", "", s.desc, ""]
        fs = fields_of(s)
        if fs:
            lines += ["**Fields its Sutra reads:** " + ", ".join(f"`{f}`" for f in fs) + ".", ""]
        if s.links:
            lines += ["**Links:** " + ", ".join(f"`{f}` → {lab} (`{kind}`)" for f, (kind, lab) in s.links.items()) + ".", ""]
    if name == "trading":
        lines += ["### Trade (`trade`)", "", T.TRADE.desc, "", "Every trade shares the fields below; `productType` chooses its Sutra "
                  "(one per product, see *Trading products*).", "", "```text", S.__doc__.split("\n\n")[1].strip(), "```", ""]
    lines += ["## Who can see it", ""]
    roles = make_packs.ROLES.get(name)
    lines += ([f"Role `{r}`: kinds {', '.join(f'`{x}`' for x in v['kinds'])}{', raw JSON' if v.get('raw') else ''}." for r, v in roles.items()]
              if roles else ["No extra roles: any user assigned the pack (or a pack that extends it) can open its kinds."]) + [""]
    impact = make_packs.IMPACT.get(name)
    if impact:
        lines += ["## F8 impact", "", "Amounts at stake: " + ", ".join(f"`{k}` by `{v}`" for k, v in impact["measures"].items())
                  + (". Dependents roll up through " + ", ".join(f"`{f}`" for f in impact.get("follow", [])) if impact.get("follow") else "") + ".", ""]
    return "\n".join(lines)


def products(docs: dict) -> str:
    lines = [HEADER, GENERATED, "# Trading products", "",
             f"The trading pack covers **{len(T.PRODUCTS)} products** in ten asset classes. Each has its own Sutra, matched on the trade's "
             "`productType`, with the product's terms, legs or schedule, the market data it is valued with, and its risk measures. "
             "`TRD productType=<productType> <GO>` lists the trades in one product.", ""]
    by = defaultdict(list)
    for p in T.PRODUCTS:
        by[p.asset].append(p)
    lines += table(["Asset class", "Products"], [[a, len(ps)] for a, ps in by.items()])
    for a, ps in by.items():
        lines += [f"## {a}", ""]
        rows = []
        for p in ps:
            rows.append([p.name, f"`{p.code}`", p.family, p.schedule or "—", ", ".join(f"`{k}`" for _, k, _ in p.md) or "—",
                         ", ".join(S.RISK_LABELS[r] for r in p.risk) or "—"])
        lines += table(["Product", "productType", "Family", "Schedule", "Market data", "Risk"], rows)
        for p in ps:
            lines += [f"**{p.name}** (`{p.code}`): {p.desc} Terms: " + ", ".join(f"`{f.name}` ({f.label})" for f in p.terms) + ".", ""]
    return "\n".join(lines)


def market(docs: dict) -> str:
    lines = [HEADER, GENERATED, "# Market-data catalogue", "",
             "The market-data kinds and how trades use them. Trades link to market data through their market-data fields "
             "(`discountCurve`, `fxVolSurface`, …), which is how F8 impact on a curve finds every trade valued with it. "
             "`<mnemonic> <GO>` lists every object of a kind, and `<mnemonic> <id> <GO>` opens one.", ""]
    for k in layout.PACKS["market-data"]["kinds"]["market"]:
        s = SPEC[k]
        lines += [f"## {s.label} (`{k}`)", "", s.desc, "", f"**Mnemonic:** `{s.mnemonic}` · **Identifiers:** `{shown_prefix(s)}…` · **Id field:** `{s.id_field}`", ""]
        fs = fields_of(s)
        if fs:
            lines += ["**Fields its Sutra reads:** " + ", ".join(f"`{f}`" for f in fs) + ".", ""]
    lines += ["## How products select market data", ""]
    rows = sorted({(f, k, sel) for p in T.PRODUCTS for f, k, sel in p.md})
    lines += table(["Trade field", "Kind", "Selected by"], [[f"`{f}`", f"`{k}`", f"`{sel}`"] for f, k, sel in rows])
    return "\n".join(lines)


def model() -> str:
    lines = [HEADER, GENERATED, "# The banking data model", "",
             "How the five banking packs' entities refer to each other. Every arrow is a reference field in a document, so each is a "
             "link in the view, a hop for F7, and a path for F8 impact.", "",
             "```text",
             "legal entity ─► desk ─► book ─► trade ◄─ trader",
             "                                 │",
             "counterparty ─► agreement ─► CSA  ├─► netting set ─► exposure profile, CVA, SA-CCR, collateral, margin calls",
             "      │                          │        └─► credit limit (per counterparty), SIMM",
             "      └─► group, credit curve    └─► market data: curves, surfaces, spots, equities, credit, inflation, commodities",
             "desk ─► VaR ─► stress results ◄─ stress scenario        book ─► FRTB sensitivities, P&L explain",
             "```", "", "## Every reference field", ""]
    rows = []
    for f, (kind, label) in sorted(T.graph_fields().items()):
        rows.append([f"`{f}`", label, f"`{kind}`", f"`{layout.pack_of(kind)}`", f"`{layout.domain_of(kind)}`"])
    lines += table(["Field", "Label", "Opens kind", "Pack", "Data domain"], rows)
    lines += ["## Packs and data domains", ""]
    rows = [[f"`{n}`", ", ".join(f"`{r}`" for r in p["requires"]) or "—", ", ".join(f"`{d}`" for d in p["kinds"])] for n, p in layout.PACKS.items()]
    lines += table(["Pack", "Extends", "Reads domains"], rows)
    return "\n".join(lines)


GUIDES = {
    "banking-core": [("banking-core", "Banking core pack", "The base: parties, organisation, agreements and calendars, and how to use them.", "building", overview),
                     ("banking-data-model", "The banking data model", "How counterparties, trades, netting sets, market data and risk results refer to each other.", "diagram-3", None)],
    "market-data": [("market-data", "Market data pack", "Curves, surfaces, prices and fixings: kinds, connectors and examples.", "graph-up", overview),
                    ("market-data-catalogue", "Market-data catalogue", "Every curve, surface, spot and fixing the pack defines, and how products select them.", "list-ul", None)],
    "trading": [("trading", "Trading pack", "Trades in 125 products: what a trade holds, its connectors and examples.", "arrow-left-right", overview),
                ("trading-products", "Trading products", "All 125 products by asset class: terms, schedules, market data and risk.", "collection", None)],
    "market-risk": [("market-risk", "Market risk pack", "VaR, stress testing, FRTB and P&L explain: kinds, connectors and examples.", "activity", overview)],
    "counterparty-risk": [("counterparty-risk", "Counterparty credit risk pack", "Netting sets, exposure, CVA, SA-CCR, collateral and margin.", "shield-check", overview)],
}


def files() -> dict[Path, str]:
    docs = make_data.build()
    out = {}
    for pack, guides in GUIDES.items():
        entries = []
        for slug, title, summary, icon, fn in guides:
            body = fn(pack, docs) if fn else {"banking-data-model": model, "market-data-catalogue": lambda: market(docs),
                                              "trading-products": lambda: products(docs)}[slug]()
            out[PACKS / pack / "guides" / f"{slug}.md"] = body.rstrip() + "\n"
            entries.append({"slug": slug, "category": "packs", "title": title, "icon": icon, "file": f"guides/{slug}.md", "summary": summary})
        help_yaml = yaml.safe_dump({"guides": entries}, sort_keys=False, allow_unicode=True, width=160)
        out[PACKS / pack / "config" / "help.yaml"] = "\n".join("#" + (" " + x if x.strip() else "") for x in HEADER.splitlines()[1:14]) + \
            f"\n\n# {GENERATED[5:-4]}\n{help_yaml}"
    return out


def main() -> None:
    want = files()
    if "--check" in sys.argv:
        stale = [str(f) for f, t in want.items() if not f.exists() or f.read_text(encoding="utf-8") != t]
        if stale:
            raise SystemExit(f"banking pack docs out of date; run make_docs.py: {stale[:3]}")
        print(f"{len(want)} banking doc files up to date")
        return
    for f, t in want.items():
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(t, encoding="utf-8")
    print(f"wrote {len(want)} files: {sum(1 for f in want if f.suffix == '.md')} guides for {len(GUIDES)} packs")


if __name__ == "__main__":
    main()
