# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Writes the banking packs' manifests (packs/<pack>/pack.yaml) and shared formats from the taxonomy and layout.py:
kinds, mnemonics, identifier patterns, link fields, badges, F8 impact, roles, requires, and the connectors and
routes that say which data domain (Delta Lake folder) answers each kind.

    python3 tools/packgen/banking/make_packs.py            write the manifests
    python3 tools/packgen/banking/make_packs.py --check    fail if they differ from what would be written
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

import booking as BK
import calc_snippets
import layout
import taxonomy as T

ROOT = Path(__file__).resolve().parents[3]
PACKS = ROOT / "packs"
HEADER = "\n".join("#" + (" " + line if line.strip() else "") for line in
                   (ROOT / "docs" / "guides" / "RACHANA_REFERENCE.md").read_text(encoding="utf-8").splitlines()[1:14])
GENERATED = "# Generated by tools/packgen/banking/make_packs.py from the taxonomy. Edit the generator, not this file."
FORMATS = {"pct4": {"type": "number", "decimals": 4, "scale": 100, "suffix": "%"}, "rate5": {"type": "number", "decimals": 5, "grouping": False},
           "pips1": {"type": "number", "decimals": 1, "sign": "always"}, "df4": {"type": "number", "decimals": 4},
           "bp1": {"type": "number", "decimals": 1, "sign": "always", "suffix": " bp"}}
ACRONYMS = ["MTM", "PV", "NPV", "DV01", "PV01", "CS01", "IE01", "PFE", "EE", "ENE", "EPE", "EEPE", "EAD", "RWA", "CVA", "DVA", "FVA", "KVA", "VaR",
            "ES", "SVaR", "FRTB", "SIMM", "IM", "VM", "CSA", "ISDA", "GMRA", "CCP", "LEI", "UTI", "UPI", "ISIN", "CUSIP", "FIGI", "RIC", "BIC",
            "SSI", "MIC", "CFI", "FpML", "KYC", "EMIR", "FX", "OIS", "RFR", "SOFR", "ESTR", "SONIA", "TONA", "USD", "EUR", "GBP", "JPY", "CHF",
            "AUD", "CAD", "MPoR", "MTA", "CLS", "ATM", "RR", "BF", "PD", "LGD", "JTD", "SA", "CCR", "SA-CCR", "SBM", "GIRR", "CSR", "NDF", "TRS"]
# Public data feeds: each its own connector, each off unless its switch (an environment variable, or the site
# configuration drishti.sources.connectors.<name>.enabled) turns it on.
FEEDS = {"nyfed-sofr": ("DRISHTI_FEED_NYFED_SOFR", ["rate-fixing"], {}, "SOFR from the New York Fed: FIX-SOFR-NYFED"),
         "ecb-estr": ("DRISHTI_FEED_ECB_ESTR", ["rate-fixing"], {}, "Euro short-term rate from the ECB: FIX-ESTR-ECB"),
         "ecb-fx": ("DRISHTI_FEED_ECB_FX", ["fx-spot"], {}, "ECB euro reference rates, with USD crosses: FX-EURUSD-ECB, FX-USDJPY-ECB, …"),
         "us-treasury": ("DRISHTI_FEED_US_TREASURY", ["ir-curve"], {}, "US Treasury daily par yield curve: CRV-USD-UST"),
         "fred": ("DRISHTI_FEED_FRED", ["rate-fixing"], {"api-key": "${FRED_API_KEY:}", "series": "${DRISHTI_FRED_SERIES:DGS10,DFF}"},
                  "FRED series (needs FRED_API_KEY): FIX-FRED-DGS10, FIX-FRED-DFF")}
# Reference data changes rarely: its tables keep a row only when an entity changes (effective dating).
EFFECTIVE_DOMAINS = {"reference"}
IMPACT = {"trading": {"measures": {"trade": "$.mtm"}, "formats": {"trade": "signed0"}},
          "counterparty-risk": {"follow": ["nettingSet", "creditLimit"], "measures": {"netting-set": "$.netMtm", "credit-limit": "$.limit"},
                                "formats": {"netting-set": "signed0", "credit-limit": "compact"}}}
EXAMPLES = {  # command, what it shows (ids from make_data.py's deterministic data)
    "banking-core": [("CPTY CP-NORTHBRIDGE", "Counterparty · netting sets, KYC, rating"), ("AGR AGR-NORTHBRIDGE-ISDA", "ISDA master agreement · elections"),
                     ("BOOK BOOK-RATES-1", "Book · top trades, MTM, DV01"), ("DESK DESK-RATES", "Desk · books, VaR")],
    "market-data": [("CRV CRV-USD-OIS", "SOFR discount curve · zero rates, pillars, forwards"), ("FXV FXV-EURUSD", "EUR/USD vol surface · smile by expiry"),
                    ("EQ EQ-NVTK", "Equity · price history, identifiers"), ("CDS CDS-SOLARIS", "Credit curve · spreads, hazard rates"),
                    ("CMDC CMDC-WTI", "WTI futures curve · backwardation")],
    "trading": [("TRD MX-20000001", "Interest rate swap · legs and every cashflow"), ("TRD WSS-1500025", "FX option"), ("TRD CLY-3000001", "Single-name CDS"),
                ("TRD IMG-400031", "OTC equity option"), ("TRD IMG-400067", "Autocallable note · observation schedule")],
    "market-risk": [("VAR VAR-RATES", "Rates desk VaR · P&L series, contributions"), ("STR STR-GFC2008-RATES", "Stress · 2008 crisis on the rates desk"),
                    ("PNL PNL-RATES-1", "P&L explain"), ("FRTB FRTB-RATES-1", "FRTB sensitivities and charges")],
    "counterparty-risk": [("NSET NS-SUMMIT-NY", "Netting set · 108 trades, exposure, CVA"), ("LIM LIM-SUMMIT", "Credit limit · utilisation by tenor"),
                          ("CVA CVA-SUMMIT-NY", "CVA / XVA"), ("SACCR SACCR-SUMMIT-NY", "SA-CCR exposure at default")],
}
TRADER_KINDS = ["trade", *layout.PACKS["market-data"]["kinds"]["market"], "counterparty", "counterparty-group", "issuer", "book", "desk",
                "trader", "legal-entity", "calendar", "agreement", "csa", "ccp", "clearing-account", "desk-pnl"]
# the pack's own code: typed alone it opens the pack's overview (its kinds, mnemonics and counts)
CODES = {"banking-core": "BNK", "market-data": "MKT", "trading": "TRDS", "market-risk": "MRSK", "counterparty-risk": "CCR"}

# key fields shown beside each entity in pick lists (TRD MX-200000, CPTY north) and searches
COLUMNS = {"trading": {"trade": ["productType", "direction", "currency", "notional", "mtm", "maturityDate", "book"]},
           "banking-core": {"counterparty": ["name", "rating", "sector", "country", "netMtm"],
                            "book": ["name", "deskName", "tradeCount", "mtm", "dv01"]}}

# a Pivot tab on the results and pick lists of these kinds (USER_GUIDE.md, The Pivot tab): fields the trade table keeps as
# columns (LAYOUTS below), so the server pivots a whole book of the day from them; opens on MTM by book and currency
PIVOTS = {"trading": {"trade": {"fields": ["book", "desk", "currency", "assetClass", "productType", "direction", "status", "counterparty.name",
                                           "nettingSet", "sourceSystem", "maturityDate", "notional", "mtm", "pnl1d", "risk.dv01"],
                                "rows": ["book"], "columns": ["currency"], "values": [{"field": "mtm", "agg": "sum"}],
                                "filters": ["assetClass", "status"]}}}

# calc: may use Calc, Python in the browser on what the role opens (PYTHON_CALC.md)
ROLES = {"trading": {"trader": {"kinds": TRADER_KINDS, "calc": True}}, "market-risk": {"market-risk": {"kinds": ["*"], "raw": True, "calc": True}},
         "counterparty-risk": {"credit-risk": {"kinds": ["*"], "raw": True, "calc": True}}}


# how the Delta connector's tables are laid out (tools/samplegen/layout.py): the trade table holds a million trades
# a business day, so the fields its pick lists, searches and screens filter on get columns of their own
LAYOUTS = {"trading": {"trade": {"columns": ["tradeId", "productType", "productName", "direction", "currency", "notional", "mtm", "pnl1d", "maturityDate",
                                             "tradeDate", "book", "desk", "status", "assetClass", "counterparty.id", "counterparty.name",
                                             "nettingSet", "risk.dv01", "sourceSystem"],
                                 "sort-by": "id", "file-rows": 250000, "row-group-rows": 1000}}}


def domain_kinds(domain: str) -> list[str]:
    return [k for p in layout.PACKS.values() for d, ks in p["kinds"].items() if d == domain for k in ks]


def connector(domain: str) -> dict:
    settings = {"root": "${DRISHTI_DELTA_ROOT:./data/delta}", "domain": domain}
    if domain in EFFECTIVE_DOMAINS:
        settings.update({f"mode.{k}": "effective" for k in domain_kinds(domain)})
    if domain in LAYOUTS:
        settings["layout"] = LAYOUTS[domain]
    return {"plugin": "delta", "enabled": "${DRISHTI_LAKE_ENABLED:true}", "kinds": domain_kinds(domain), "settings": settings}


def manifest(name: str) -> dict:
    p = layout.PACKS[name]
    kinds = [k for ks in p["kinds"].values() for k in ks]
    specs = {k.kind: k for k in T.KINDS + [T.TRADE]}
    fields = {f: {"kind": kind, "label": label} for f, (kind, label) in T.graph_fields().items() if kind in kinds}
    m = {"pack": name, "version": "1.0.0", "code": CODES[name], "title": p["title"], "description": p["description"], "extends": p["requires"],
         "kinds": kinds, "sutras": "sutras", "formats": "config/formats.yaml",
         **({"semantics": "config/semantics.yaml"} if name == "banking-core" else {}),
         "mnemonics": {specs[k].mnemonic: {"kind": k, "label": specs[k].label} for k in kinds},
         "graph": {"id-patterns": [{"pattern": BK.ID_PATTERN if k == "trade" else "^" + specs[k].prefix, "kind": k} for k in kinds],
                   "fields": dict(sorted(fields.items())),
                   "badges": {k: specs[k].badge for k in kinds if specs[k].badge}},
         "connectors": {f"{d}-store": connector(d) for d in p["kinds"]},
         "routes": {k: f"{d}-store" for d, ks in p["kinds"].items() for k in ks}}
    if name == "trading":
        m["connectors"]["trading-stream"] = {"plugin": "kafka", "enabled": "${DRISHTI_STREAM_TRADING:false}", "kinds": ["trade"],
                                             "settings": {"bootstrap-servers": "${DRISHTI_KAFKA_BOOTSTRAP:localhost:9092}",
                                                          "topics": "${DRISHTI_TRADING_TOPIC:drishti.trading.trades}",
                                                          "kind": "trade", "id-field": "tradeId",
                                                          # a live stream with no new trade for this long is shown as behind
                                                          "stale-after": "${DRISHTI_STREAM_STALE_AFTER:15m}",
                                                          # the day's live trades on local disk, in this connector's own RocksDB store
                                                          "disk-cache.enabled": "${DRISHTI_STREAM_DISK_CACHE:true}",
                                                          "disk-cache.root": "${DRISHTI_CACHE_ROOT:./data/cache}",
                                                          "disk-cache.max-gb": "${DRISHTI_STREAM_CACHE_GB:10}",
                                                          "disk-cache.reset-at": "${DRISHTI_CACHE_RESET_AT:02:00}",
                                                          "disk-cache.zone": "America/New_York"}}
        # a derived kind: each desk's P&L, computed from the trades wherever they come from (PACKS.md, Derived kinds)
        m["kinds"].append("desk-pnl")
        m["mnemonics"]["DPNL"] = {"kind": "desk-pnl", "label": "Desk P&L (derived from trades)"}
        m["graph"]["fields"]["tradeIds"] = {"kind": "trade", "label": "Trade"}
        m["connectors"]["desk-totals"] = {"plugin": "derived", "kinds": ["desk-pnl"], "settings": {
            "refresh": "60s",
            "desk-pnl": {"from": "trade", "group-by": "$.desk", "id-field": "desk", "members": "tradeIds", "max-members": 250,
                         "fields": {"tradeCount": "count", "mtm": "sum $.mtm", "pnl1d": "sum $.pnl1d", "dv01": "sum $.risk.dv01",
                                    "worstMtm": "min $.mtm", "books": "distinct $.book", "currencies": "distinct $.currency"},
                         "rows": {"trade": "$.tradeId", "product": "$.productName", "book": "$.book", "currency": "$.currency",
                                  "mtm": "$.mtm", "pnl1d": "$.pnl1d"}}}}
        m["routes"]["desk-pnl"] = "desk-totals"
    if name == "market-data":
        for feed, (switch, kinds_, extra, _) in FEEDS.items():
            m["connectors"][f"{feed}-feed"] = {"plugin": "feed", "enabled": "${" + switch + ":false}", "kinds": kinds_,
                                               "settings": {"feed": feed,
                                                            "user-agent": "${drishti.branding.product:feed} public data feed connector",
                                                            "stale-after": "4d",   # daily feeds: covers a weekend and a holiday
                                                            "refresh-minutes": 60, **extra}}
    if name in COLUMNS:
        m["columns"] = COLUMNS[name]
    if name in PIVOTS:
        m["pivot"] = PIVOTS[name]
    m["console"] = {"examples": [list(e) for e in EXAMPLES[name]], "help": "config/help.yaml"}
    if calc_snippets.SNIPPETS.get(name):    # Calc on the pack's kinds, with its snippets under python/ (calc_snippets.py)
        m["python"] = {"enabled": True}
    if name in IMPACT:
        m["graph"]["impact"] = IMPACT[name]
    if name in ROLES:
        m["roles"] = ROLES[name]
    if not m["graph"]["badges"]:
        del m["graph"]["badges"]
    return m


def files() -> dict[Path, str]:
    out = {}
    for name in layout.PACKS:
        body = yaml.safe_dump(manifest(name), sort_keys=False, allow_unicode=True, width=140)
        out[PACKS / name / "pack.yaml"] = f"{HEADER}\n\n{GENERATED}\n# {layout.PACKS[name]['title']} pack for Drishti.\n{body}"
        out[PACKS / name / "config" / "formats.yaml"] = (f"{HEADER}\n\n{GENERATED}\n# Number formats the banking packs share.\n"
                                                         + yaml.safe_dump({"formats": FORMATS}, sort_keys=False))
        for file, title, description, kinds, code in calc_snippets.SNIPPETS.get(name, []):
            meta = f"# title: {title}\n# description: {description}\n# kinds: {', '.join(kinds)}\n"
            out[PACKS / name / "python" / file] = f"{HEADER}\n\n{GENERATED.replace('from the taxonomy', 'from calc_snippets.py')}\n{meta}\n{code}"
        if name == "banking-core":   # every banking pack requires banking-core, so its vocabulary covers them all
            out[PACKS / name / "config" / "semantics.yaml"] = (f"{HEADER}\n\n{GENERATED}\n# How banking field names read as labels.\n"
                                                               + yaml.safe_dump({"acronyms": ACRONYMS, "labels": {"tradeId": "Trade", "mtm": "MTM (USD)"}},
                                                                                sort_keys=False, width=140))
    return out


def main() -> None:
    layout.check([k.kind for k in T.KINDS] + ["trade"])
    want = files()
    if "--check" in sys.argv:
        stale = [str(f) for f, t in want.items() if not f.exists() or f.read_text(encoding="utf-8") != t]
        if stale:
            raise SystemExit(f"pack manifests out of date; run make_packs.py: {stale[:5]}")
        print(f"{len(layout.PACKS)} pack manifests up to date")
        return
    for f, t in want.items():
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(t, encoding="utf-8")
    print(f"wrote {len(layout.PACKS)} pack manifests: {', '.join(layout.PACKS)}")


if __name__ == "__main__":
    main()
