# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Writes the banking packs' manifests (packs/<pack>/pack.yaml) and shared formats from the taxonomy and layout.py:
kinds, mnemonics, identifier patterns, link fields, badges, F8 impact, roles, requires, and the connectors and
routes that say which data domain (Delta Lake folder) answers each kind.

    python3 tools/packgen/banking/make_packs.py            write the manifests
    python3 tools/packgen/banking/make_packs.py --check    fail if they differ from what would be written
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

import layout
import taxonomy as T

ROOT = Path(__file__).resolve().parents[3]
PACKS = ROOT / "packs"
HEADER = "\n".join("#" + (" " + line if line.strip() else "") for line in
                   (ROOT / "docs" / "RACHANA_REFERENCE.md").read_text(encoding="utf-8").splitlines()[1:14])
GENERATED = "# Generated by tools/packgen/banking/make_packs.py from the taxonomy. Edit the generator, not this file."
FORMATS = {"pct4": {"type": "number", "decimals": 4, "scale": 100, "suffix": "%"}, "rate5": {"type": "number", "decimals": 5, "grouping": False},
           "pips1": {"type": "number", "decimals": 1, "sign": "always"}, "df4": {"type": "number", "decimals": 4},
           "bp1": {"type": "number", "decimals": 1, "sign": "always", "suffix": " bp"}}
# Reference data changes rarely: its tables keep a row only when an entity changes (effective dating).
EFFECTIVE_DOMAINS = {"reference"}
IMPACT = {"trading": {"measures": {"trade": "$.mtm"}, "formats": {"trade": "signed0"}},
          "counterparty-risk": {"follow": ["nettingSet", "creditLimit"], "measures": {"netting-set": "$.netMtm", "credit-limit": "$.limit"},
                                "formats": {"netting-set": "signed0", "credit-limit": "compact"}}}
ROLES = {"trading": {"trader": {"kinds": ["trade"]}}, "market-risk": {"market-risk": {"kinds": ["*"], "raw": True}},
         "counterparty-risk": {"credit-risk": {"kinds": ["*"], "raw": True}}}


def domain_kinds(domain: str) -> list[str]:
    return [k for p in layout.PACKS.values() for d, ks in p["kinds"].items() if d == domain for k in ks]


def connector(domain: str) -> dict:
    settings = {"root": "${DRISHTI_DELTA_ROOT:./data/delta}", "domain": domain}
    if domain in EFFECTIVE_DOMAINS:
        settings.update({f"mode.{k}": "effective" for k in domain_kinds(domain)})
    return {"plugin": "delta", "enabled": "${DRISHTI_LAKE_ENABLED:true}", "kinds": domain_kinds(domain), "settings": settings}


def manifest(name: str) -> dict:
    p = layout.PACKS[name]
    kinds = [k for ks in p["kinds"].values() for k in ks]
    specs = {k.kind: k for k in T.KINDS + [T.TRADE]}
    fields = {f: {"kind": kind, "label": label} for f, (kind, label) in T.graph_fields().items() if kind in kinds}
    m = {"pack": name, "version": "1.0.0", "title": p["title"], "description": p["description"], "requires": p["requires"],
         "kinds": kinds, "sutras": "sutras", "formats": "config/formats.yaml",
         "mnemonics": {specs[k].mnemonic: {"kind": k, "label": specs[k].label} for k in kinds},
         "graph": {"id-patterns": [{"pattern": "^" + specs[k].prefix, "kind": k} for k in kinds],
                   "fields": dict(sorted(fields.items())),
                   "badges": {k: specs[k].badge for k in kinds if specs[k].badge}},
         "connectors": {f"{d}-lake": connector(d) for d in p["kinds"]},
         "routes": {k: f"{d}-lake" for d, ks in p["kinds"].items() for k in ks}}
    if name in IMPACT:
        m["graph"]["impact"] = IMPACT[name]
    if name in ROLES:
        m["roles"] = ROLES[name]
    if not m["graph"]["badges"]:
        del m["graph"]["badges"]
    return m


def files() -> dict[Path, str]:
    out = {}
    for name in layout.PACKS:
        body = yaml.safe_dump(manifest(name), sort_keys=False, allow_unicode=True, width=140)
        out[PACKS / name / "pack.yaml"] = f"{HEADER}\n\n{GENERATED}\n# {layout.PACKS[name]['title']} pack for Drishti.\n{body}"
        out[PACKS / name / "config" / "formats.yaml"] = (f"{HEADER}\n\n{GENERATED}\n# Number formats the banking packs share.\n"
                                                         + yaml.safe_dump({"formats": FORMATS}, sort_keys=False))
    return out


def main() -> None:
    layout.check([k.kind for k in T.KINDS] + ["trade"])
    want = files()
    if "--check" in sys.argv:
        stale = [str(f) for f, t in want.items() if not f.exists() or f.read_text(encoding="utf-8") != t]
        if stale:
            raise SystemExit(f"pack manifests out of date; run make_packs.py: {stale[:5]}")
        print(f"{len(layout.PACKS)} pack manifests up to date")
        return
    for f, t in want.items():
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(t, encoding="utf-8")
    print(f"wrote {len(layout.PACKS)} pack manifests: {', '.join(layout.PACKS)}")


if __name__ == "__main__":
    main()
