# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Counterparty, collateral, exposure, capital, market-risk and organisation kinds for the risk pack taxonomy."""
from risk_model import Kind, Panel as P

CP, COL, EXP, MR, ORG = "Counterparty and legal", "Collateral and margin", "Exposure and capital", "Market risk", "Organisation"
TRADE_COLS = [("Trade", "@.tradeId", None, None, False), ("Product", "@.product", None, None, False), ("Notional", "@.notional", "compact", None, False),
              ("Maturity", "@.maturity", "date", None, False), ("MTM", "@.mtm", "signed0", "sign", True)]

KINDS = [
    Kind("counterparty", "CPTY", "CP-", "Counterparty", CP, "A legal entity the bank trades with: identifiers, rating, sector, country and parent group.", "counterpartyId",
         [("Name", "$.name", None, None, False), ("LEI", "$.lei", None, None, False), ("Rating", "$.rating", None, None, True), ("Sector", "$.sector", None, None, False), ("Country", "$.country", None, None, False), ("Type", "$.type", None, None, False), ("Net MTM", "$.netMtm", "signed0", "sign", False), ("PFE peak", "$.pfePeak", "compact", None, False)],
         [P("table", "nettingSets", "Netting sets", "$.nettingSets", [("Netting set", "@.id", None, None, False), ("Agreement", "@.agreement", None, None, False), ("Trades", "@.trades", "amount0", None, True), ("Net MTM", "@.netMtm", "signed0", "sign", True)], key="F2"),
          P("kv", "kyc", "KYC and classification", "$.kyc", area="right"),
          P("graph", "hierarchy", "Group hierarchy, agreements and netting sets", key="F3", code="HIER",
            opts={"nodes": "$.hierarchy.nodes", "edges": "$.hierarchy.edges", "label": "label", "group": "type", "layout": "tree"})],
         links={"group": ("counterparty-group", "Group"), "creditLimit": ("credit-limit", "Credit limit"), "creditCurve": ("credit-curve", "Credit curve")}, badge="$.rating"),
    Kind("counterparty-group", "GRP", "GRP-", "Counterparty group", CP, "Economic group of related counterparties (obligor group).", "groupId",
         [("Name", "$.name", None, None, False), ("Members", "size($.members)", None, None, False), ("Group limit", "$.limit", "compact", None, False), ("Utilisation", "$.utilisation", "pct0", None, True)],
         [P("table", "members", "Members", "$.members", [("Counterparty", "@.id", None, None, False), ("Name", "@.name", None, None, False), ("Rating", "@.rating", None, None, False)], key="F2")]),
    Kind("issuer", "ISS", "ISS-", "Issuer", CP, "Issuer of bonds and reference entity for CDS.", "issuerId",
         [("Name", "$.name", None, None, False), ("Rating", "$.rating", None, None, True), ("Sector", "$.sector", None, None, False), ("Country", "$.country", None, None, False)],
         [P("table", "bonds", "Bonds outstanding", "$.bonds", [("ISIN", "@.isin", None, None, False), ("Coupon", "@.coupon", "pct2", None, False), ("Maturity", "@.maturity", "date", None, False)], key="F2")],
         links={"creditCurve": ("credit-curve", "Credit curve"), "equity": ("equity", "Equity")}, badge="$.rating"),
    Kind("legal-entity", "LE", "LE-", "Bank legal entity", ORG, "The bank's own booking entity.", "entityId",
         [("Name", "$.name", None, None, False), ("LEI", "$.lei", None, None, False), ("Jurisdiction", "$.jurisdiction", None, None, False), ("Regulator", "$.regulator", None, None, True)],
         [P("table", "desks", "Desks", "$.desks", [("Desk", "@.id", None, None, False), ("Name", "@.name", None, None, False)], key="F2"),
          P("scatter", "riskReturn", "Books: VaR against today's P&L (USD)", "$.books", x="var", y="pnl", label="book", fmt="signed0", key="F3",
            code="RR", opts={"size": "trades", "group": "desk", "xFmt": "compact", "xLabel": "VaR 99% 1D (USD)", "yLabel": "P&L 1D (USD)"})]),
    Kind("agreement", "AGR", "AGR-", "Master agreement", CP, "ISDA, GMRA or GMSLA master agreement with its key elections.", "agreementId",
         [("Type", "$.type", None, None, False), ("Counterparty", "$.counterpartyName", None, None, False), ("Governing law", "$.governingLaw", None, None, False), ("Signed", "$.signed", "date", None, False), ("Close-out netting", "$.closeOutNetting", None, None, True)],
         [P("kv", "elections", "Elections", "$.elections", key="F2")], links={"counterparty": ("counterparty", "Counterparty"), "csa": ("csa", "CSA")}),
    Kind("csa", "CSA", "CSA-", "Credit support annex", COL, "Collateral terms: thresholds, minimum transfer, eligible collateral and haircuts.", "csaId",
         [("Margin", "$.marginType", None, None, False), ("Threshold (us)", "$.thresholdUs", "compact", None, False), ("Threshold (them)", "$.thresholdThem", "compact", None, False), ("MTA", "$.mta", "compact", None, False), ("IA", "$.independentAmount", "compact", None, False), ("Frequency", "$.frequency", None, None, False), ("MPoR", "$.mpor", None, None, True)],
         [P("table", "eligible", "Eligible collateral and haircuts", "$.eligible", [("Asset", "@.asset", None, None, False), ("Haircut", "@.haircut", "pct2", None, False)], key="F2")],
         links={"agreement": ("agreement", "Agreement"), "counterparty": ("counterparty", "Counterparty")}, badge="'threshold ' + fmt($.thresholdThem, 'compact')"),
    Kind("netting-set", "NSET", "NS-", "Netting set", EXP, "Trades that net on close-out under one agreement and CSA, with exposure and collateral.", "nettingSetId",
         [("Trades", "$.tradeCount", None, None, False), ("Net MTM", "$.netMtm", "signed0", "sign", False), ("Collateral", "$.collateral", "signed0", None, False), ("EE peak", "$.eePeak", "compact", None, False), ("PFE 95 peak", "$.pfePeak", "compact", None, True), ("Limit", "$.limit", "compact", None, False), ("Utilisation", "$.utilisation", "pct0", None, False), ("CVA", "$.cva", "signed0", "sign", False)],
         [P("area", "exposure", "Exposure profile", "$.profile", x="tenor", series=[("Expected exposure", "ee", "link"), ("PFE 95", "pfe", "accent")], limit="$.limit", key="F2", code="EXP"),
          P("table", "trades", "Member trades", "$.trades", TRADE_COLS, key="F3", code="TRD"),
          P("hbar", "byAsset", "Net MTM by asset class", "$.byAsset", label="asset", value="mtm", fmt="signed0", tone="sign", area="right")],
         links={"counterparty": ("counterparty", "Counterparty"), "agreement": ("agreement", "Agreement"), "csa": ("csa", "CSA"), "creditLimit": ("credit-limit", "Credit limit"),
                "exposureProfile": ("exposure-profile", "Exposure profile"), "cvaResult": ("cva", "CVA"), "saccr": ("sa-ccr", "SA-CCR"), "simm": ("simm", "SIMM"), "collateralBalance": ("collateral-balance", "Collateral")},
         badge="'PFE ' + fmt($.pfePeak, 'compact')", live={"netMtm": 25000}),
    Kind("collateral-balance", "COLL", "COLL-", "Collateral balance", COL, "Collateral held and posted under a CSA, by asset, after haircuts.", "balanceId",
         [("Held", "$.held", "compact", None, False), ("Posted", "$.posted", "compact", None, False), ("Net", "$.net", "signed0", "sign", True), ("As of", "$.asOf", "date", None, False)],
         [P("table", "positions", "Positions", "$.positions", [("Asset", "@.asset", None, None, False), ("Direction", "@.direction", None, None, False), ("Market value", "@.marketValue", "amount0", None, True), ("Haircut", "@.haircut", "pct2", None, False), ("Collateral value", "@.value", "amount0", None, True)], key="F2")],
         links={"csa": ("csa", "CSA"), "nettingSet": ("netting-set", "Netting set")}),
    Kind("margin-call", "MC", "MC-", "Margin call", COL, "A variation or initial margin call and its settlement status.", "callId",
         [("Date", "$.callDate", "date", None, False), ("Type", "$.marginType", None, None, False), ("Direction", "$.direction", None, None, False), ("Amount", "$.amount", "amount0", None, True), ("Status", "$.status", None, "status", False), ("Dispute", "$.disputeAmount", "amount0", None, False)],
         [P("ladder", "events", "Workflow", "$.events", [("Time", "@.at", None, None, False), ("Event", "@.event", None, None, False), ("By", "@.by", None, None, False)], key="F2")],
         links={"nettingSet": ("netting-set", "Netting set"), "csa": ("csa", "CSA")}),
    Kind("credit-limit", "LIM", "LIM-", "Credit limit", EXP, "PFE limit by tenor bucket for a counterparty, with utilisation.", "limitId",
         [("Counterparty", "$.counterpartyName", None, None, False), ("Measure", "$.measure", None, None, False), ("Limit", "$.limit", "compact", None, False), ("Used", "$.used", "compact", None, False), ("Utilisation", "$.utilisation", "pct0", None, True), ("Status", "$.status", None, "status", False)],
         [P("table", "buckets", "By tenor bucket", "$.buckets", [("Bucket", "@.bucket", None, None, False), ("Limit", "@.limit", "compact", None, False), ("Used", "@.used", "compact", None, False), ("Utilisation", "@.utilisation", "pct0", None, False)], key="F2"),
          P("hbar", "util", "Utilisation", "$.buckets", label="bucket", value="utilisation", fmt="pct0", area="right")],
         links={"counterparty": ("counterparty", "Counterparty")}, badge="fmt($.utilisation, 'pct0') + ' used'"),
    Kind("exposure-profile", "EXP", "EXP-", "Exposure profile", EXP, "Simulated EE, EPE, ENE and PFE by time bucket for a netting set.", "profileId",
         [("EPE", "$.epe", "compact", None, False), ("EEPE", "$.eepe", "compact", None, False), ("PFE 95 peak", "$.pfePeak", "compact", None, True), ("Paths", "$.paths", "amount0", None, False), ("Run", "$.runDate", "date", None, False)],
         [P("area", "profile", "Exposure (USD)", "$.buckets", x="tenor", series=[("EE", "ee", "link"), ("PFE 95", "pfe95", "accent"), ("ENE", "ene", "neg")], key="F2"),
          P("table", "buckets", "Buckets", "$.buckets", [("Tenor", "@.tenor", None, None, False), ("EE", "@.ee", "compact", None, False), ("ENE", "@.ene", "compact", None, False), ("PFE 95", "@.pfe95", "compact", None, False), ("PFE 99", "@.pfe99", "compact", None, False)])],
         links={"nettingSet": ("netting-set", "Netting set")}),
    Kind("cva", "CVA", "CVA-", "CVA / XVA", EXP, "Credit, debit and funding valuation adjustments with sensitivities.", "resultId",
         [("CVA", "$.cva", "signed0", "sign", True), ("DVA", "$.dva", "signed0", "sign", False), ("FVA", "$.fva", "signed0", "sign", False), ("KVA", "$.kva", "signed0", "sign", False), ("CS01 (cpty)", "$.cs01", "signed0", "sign", False)],
         [P("hbar", "components", "Adjustments", "$.components", label="name", value="amount", fmt="signed0", tone="sign", key="F2"),
          P("table", "sens", "Sensitivities", "$.sensitivities", [("Risk factor", "@.factor", None, None, False), ("Bump", "@.bump", None, None, False), ("Δ CVA", "@.delta", "signed0", "sign", False)])],
         links={"nettingSet": ("netting-set", "Netting set"), "creditCurve": ("credit-curve", "Counterparty curve")}),
    Kind("sa-ccr", "SACCR", "SACCR-", "SA-CCR exposure", EXP, "Regulatory EAD: replacement cost, PFE add-ons by asset class, multiplier.", "calcId",
         [("RC", "$.replacementCost", "compact", None, False), ("Add-on", "$.addOn", "compact", None, False), ("Multiplier", "$.multiplier", "df4", None, False), ("EAD", "$.ead", "compact", None, True), ("RWA", "$.rwa", "compact", None, False)],
         [P("hbar", "addons", "Add-on by asset class", "$.addOns", label="assetClass", value="addOn", fmt="compact", key="F2"),
          P("table", "hedging", "Hedging sets", "$.hedgingSets", [("Asset class", "@.assetClass", None, None, False), ("Hedging set", "@.hedgingSet", None, None, False), ("Effective notional", "@.effectiveNotional", "compact", None, False), ("SF", "@.sf", "pct2", None, False)])],
         links={"nettingSet": ("netting-set", "Netting set")}),
    Kind("simm", "SIMM", "SIMM-", "ISDA SIMM initial margin", COL, "Initial margin by risk class and product class.", "calcId",
         [("Total IM", "$.total", "compact", None, True), ("Posted", "$.posted", "compact", None, False), ("Received", "$.received", "compact", None, False), ("Version", "$.version", None, None, False)],
         [P("hbar", "classes", "IM by risk class", "$.riskClasses", label="riskClass", value="im", fmt="compact", key="F2")], links={"nettingSet": ("netting-set", "Netting set")}),
    Kind("var", "VAR", "VAR-", "VaR / expected shortfall", MR, "Historical VaR and ES for a desk or portfolio, with backtesting.", "resultId",
         [("VaR 99% 1D", "$.var99", "compact", None, True), ("ES 97.5%", "$.es975", "compact", None, False), ("Stressed VaR", "$.svar", "compact", None, False), ("Limit", "$.limit", "compact", None, False), ("Exceptions (250d)", "$.exceptions", None, None, False)],
         [P("line", "pnl", "Hypothetical P&L, last 60 days", "$.pnlSeries", x="date", y="pnl", fmt="signed0", key="F2"),
          P("hbar", "contrib", "VaR contribution by book", "$.contributions", label="book", value="var", fmt="compact", area="right"),
          P("histogram", "scenarios", "Scenario P&L distribution, 500 days (USD)", "$.scenarioPnl", fmt="compact", key="F3", code="DIST",
            opts={"unit": "USD", "markers": [{"label": "VaR 99%", "value": "-$.var99", "tone": "neg"},
                                              {"label": "ES 97.5%", "value": "-$.es975", "tone": "bad"},
                                              {"label": "Mean", "value": "$.meanPnl", "tone": "link"}]})],
         links={"desk": ("desk", "Desk")}, badge="fmt($.var99, 'compact')", live={"var99": 20000}),
    Kind("stress-scenario", "SCN", "SCN-", "Stress scenario", MR, "A named historical or hypothetical shock set.", "scenarioId",
         [("Name", "$.name", None, None, False), ("Type", "$.type", None, None, False), ("Severity", "$.severity", None, None, True)],
         [P("table", "shocks", "Shocks", "$.shocks", [("Risk factor", "@.factor", None, None, False), ("Shock", "@.shock", None, None, False)], key="F2")]),
    Kind("stress-result", "STR", "STR-", "Stress result", MR, "P&L of a desk under a scenario, by book.", "resultId",
         [("Scenario", "$.scenarioName", None, None, False), ("P&L", "$.pnl", "signed0", "sign", True), ("Limit", "$.limit", "compact", None, False)],
         [P("hbar", "books", "P&L by book", "$.byBook", label="book", value="pnl", fmt="signed0", tone="sign", key="F2")],
         links={"scenario": ("stress-scenario", "Scenario"), "desk": ("desk", "Desk")}),
    Kind("frtb-sensitivity", "FRTB", "FRTB-", "FRTB sensitivities", MR, "Delta, vega and curvature by risk class and bucket (SBM).", "resultId",
         [("Book", "$.book", None, None, False), ("Delta charge", "$.deltaCharge", "compact", None, False), ("Vega charge", "$.vegaCharge", "compact", None, False), ("Curvature", "$.curvatureCharge", "compact", None, False), ("SBM total", "$.total", "compact", None, True)],
         [P("table", "buckets", "Sensitivities", "$.sensitivities", [("Risk class", "@.riskClass", None, None, False), ("Bucket", "@.bucket", None, None, False), ("Measure", "@.measure", None, None, False), ("Value", "@.value", "signed0", "sign", False)], key="F2"),
          P("hbar", "classes", "Charge by risk class", "$.byClass", label="riskClass", value="charge", fmt="compact", area="right")],
         links={"book": ("book", "Book")}),
    Kind("pnl-explain", "PNL", "PNL-", "P&L explain", MR, "Daily P&L attributed to risk factors, new trades and residual.", "resultId",
         [("Date", "$.date", "date", None, False), ("Actual", "$.actual", "signed0", "sign", True), ("Explained", "$.explained", "signed0", "sign", False), ("Unexplained", "$.unexplained", "signed0", "sign", False)],
         [P("hbar", "attribution", "Attribution", "$.attribution", label="factor", value="pnl", fmt="signed0", tone="sign", key="F2"),
          P("waterfall", "explain", "From risk factors to actual P&L (USD)", "$.explainSteps", label="step", value="pnl", fmt="signed0", key="F3",
            code="PNLX", opts={"sum": "Actual", "unit": "USD"})], links={"book": ("book", "Book")}),
    Kind("book", "BOOK", "BOOK-", "Book", ORG, "A trading book: owner desk, trades and risk.", "bookId",
         [("Name", "$.name", None, None, False), ("Desk", "$.deskName", None, None, False), ("Trades", "$.tradeCount", None, None, False), ("MTM", "$.mtm", "signed0", "sign", True), ("DV01", "$.dv01", "signed0", "sign", False)],
         [P("table", "trades", "Largest trades", "$.topTrades", TRADE_COLS, key="F2")], links={"desk": ("desk", "Desk")}),
    Kind("desk", "DESK", "DESK-", "Desk", ORG, "A trading desk: books, limits and risk results.", "deskId",
         [("Name", "$.name", None, None, False), ("Head", "$.head", None, None, False), ("Books", "size($.books)", None, None, False), ("VaR", "$.var99", "compact", None, True), ("MTM", "$.mtm", "signed0", "sign", False)],
         [P("table", "books", "Books", "$.books", [("Book", "@.id", None, None, False), ("Trades", "@.trades", "amount0", None, True), ("MTM", "@.mtm", "signed0", "sign", True)], key="F2"),
          P("pivot", "mtmGrid", "MTM by book and currency (USD)", "$.positions", fmt="compact", tone="sign", key="F3", code="PIV",
            opts={"by": "book", "across": "currency", "value": "mtm", "agg": "sum", "heat": True}),
          P("pivot", "tradeCount", "Trades by book and product family", "$.positions",
            opts={"by": "book", "across": "family", "agg": "count"})],
         links={"legalEntity": ("legal-entity", "Legal entity"), "varResult": ("var", "VaR")}),
    Kind("trader", "TRDR", "TRDR-", "Trader", ORG, "A trader and their books.", "traderId",
         [("Name", "$.name", None, None, False), ("Desk", "$.deskName", None, None, False), ("Trades", "$.tradeCount", None, None, True)],
         [P("table", "books", "Books", "$.books", [("Book", "@.id", None, None, False)], key="F2")], links={"desk": ("desk", "Desk")}),
    Kind("ccp", "CCP", "CCP-", "Central counterparty", CP, "A clearing house with its default fund and margin model.", "ccpId",
         [("Name", "$.name", None, None, False), ("Default fund", "$.defaultFund", "compact", None, False), ("IM posted", "$.imPosted", "compact", None, True), ("Model", "$.marginModel", None, None, False)],
         [P("table", "accounts", "Clearing accounts", "$.accounts", [("Account", "@.id", None, None, False), ("IM", "@.im", "compact", None, True)], key="F2")]),
    Kind("clearing-account", "CLR", "CLR-", "Clearing account", COL, "An account at a CCP holding cleared trades and margin.", "accountId",
         [("CCP", "$.ccpName", None, None, False), ("IM", "$.im", "compact", None, True), ("VM today", "$.vmToday", "signed0", "sign", False), ("Excess", "$.excess", "compact", None, False)],
         [P("table", "trades", "Cleared trades", "$.trades", TRADE_COLS, key="F2")], links={"ccp": ("ccp", "CCP")}, badge="'IM ' + fmt($.im, 'compact')"),
]
