/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.redis;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.tls.TlsException;
import com.ash.drishti.api.tls.TlsMaterial;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.TlsFixture;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * Redis over TLS with the shared {@code tls.*} settings: the wiring (no Docker needed), then a real Redis 8 started with
 * {@code --tls-auth-clients yes} and certificates generated by the test: a client certificate is accepted, a missing one, a
 * wrong CA and a wrong host name are refused. Skipped where Docker is not reachable.
 */
class RedisTlsTest {

    private static final String IMAGE = "redis:8.2";
    private static TlsFixture pki;
    private static GenericContainer<?> redis;

    @BeforeAll
    static void start() {
        pki = new TlsFixture();
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
        } catch (RuntimeException e) {
            docker = false;
        }
        if (!docker) {
            return;
        }
        GenericContainer<?> c = new GenericContainer<>(IMAGE).withExposedPorts(6379)
                .withCommand("redis-server", "--port", "0", "--tls-port", "6379", "--tls-cert-file", "/tls/server.pem", "--tls-key-file",
                        "/tls/server.key", "--tls-ca-cert-file", "/tls/ca.pem", "--tls-auth-clients", "yes")
                .waitingFor(Wait.forLogMessage(".*Ready to accept connections.*", 1).withStartupTimeout(Duration.ofMinutes(1)));
        for (String f : new String[] {"ca.pem", "server.pem", "server.key"}) {
            c.withCopyFileToContainer(MountableFile.forHostPath(pki.path(f), 0644), "/tls/" + f);
        }
        redis = c;
        redis.start();
    }

    @AfterAll
    static void stop() {
        if (redis != null) {
            redis.stop();
        }
        pki.delete();
    }

    private static String uri(String host) {
        return "rediss://" + host + ":" + redis.getMappedPort(6379);
    }

    private static TlsMaterial material(Map<String, String> tls, String uri) {
        return RedisTls.material(tls, uri, System::getenv);
    }

    // ---- wiring, without a server

    @Test
    void tlsSettingsAgainstAPlainUriAreRefusedNotIgnored() {
        assertThatThrownBy(() -> material(Map.of("tls.enabled", "true"), "redis://h:6379"))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.enabled is true but uri is not rediss://");
        assertThatThrownBy(() -> material(Map.of("tls.ca-file", "/x.pem"), "redis://h:6379"))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.* is set but uri is not rediss://");
        assertThat(material(Map.of(), "redis://h:6379")).isNull();
    }

    @Test
    void aMissingCaFileFailsTheStartNamingTheSettingAndTheFile() {
        assertThatThrownBy(() -> material(Map.of("tls.ca-file", "/etc/drishti/nope.pem"), "rediss://h:6380"))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.ca-file '/etc/drishti/nope.pem'").hasMessageContaining("not found");
        assertThatThrownBy(() -> new RedisSourcePlugin().start(DatedSourceContract.context(Map.of("uri", "rediss://h:6380", "tls.ca-file", "/etc/drishti/nope.pem"))))
                .isInstanceOf(TlsException.class);
    }

    @Test
    void aRedissUriAloneTrustsTheJvmAuthoritiesAndTheSecureSchemeIsFoundInAClusterList() {
        assertThat(material(Map.of(), "rediss://h:6380").usesJvmDefaultTrust()).isTrue();
        assertThat(RedisTls.secureScheme("redis://a:1, rediss://b:2")).isTrue();
        assertThat(RedisTls.secureScheme("redis://a:1")).isFalse();
    }

    @Test
    void theDeprecatedVerifyPeerOptionInTheUriStillWorks() {
        TlsMaterial m = material(pki.trustOnlySettings(), "rediss://h:6380?verifyPeer=CA");
        io.lettuce.core.RedisURI u = io.lettuce.core.RedisURI.create("rediss://h:6380?verifyPeer=CA");
        RedisTls.apply(u, m);
        assertThat(u.getVerifyMode()).isEqualTo(io.lettuce.core.SslVerifyMode.CA);          // the URI asked for less and keeps it
        io.lettuce.core.RedisURI v = io.lettuce.core.RedisURI.create("rediss://h:6380");
        RedisTls.apply(v, m);
        assertThat(v.getVerifyMode()).isEqualTo(io.lettuce.core.SslVerifyMode.FULL);
    }

    // ---- a real Redis with TLS and client certificates

    private static void assumeRedis() {
        org.junit.jupiter.api.Assumptions.assumeTrue(redis != null, "Docker is needed");
    }

    private static String ping(String uri, Map<String, String> tls) {
        TlsMaterial m = material(tls, uri);
        try (RedisConnection c = RedisConnection.open(uri, false, null, null, Duration.ofSeconds(5), m)) {
            c.async().set("k".getBytes(StandardCharsets.UTF_8), "v".getBytes(StandardCharsets.UTF_8)).toCompletableFuture().join();
            return new String(c.async().get("k".getBytes(StandardCharsets.UTF_8)).toCompletableFuture().join(), StandardCharsets.UTF_8);
        }
    }

    @Test
    void aClientCertificateSignedByTheTrustedCaIsAccepted() {
        assumeRedis();
        assertThat(ping(uri("localhost"), pki.clientSettings())).isEqualTo("v");
    }

    @Test
    void aPkcs12KeystoreAndTruststoreWorkToo() {
        assumeRedis();
        Map<String, String> s = new LinkedHashMap<>();
        s.put("tls.truststore", pki.path("ca.p12").toString());
        s.put("tls.truststore-password", "changeit");
        s.put("tls.keystore", pki.path("client.p12").toString());
        s.put("tls.keystore-password", "changeit");
        assertThat(ping(uri("localhost"), s)).isEqualTo("v");
    }

    @Test
    void withoutAClientCertificateTheServerRefuses() {
        assumeRedis();
        assertThatThrownBy(() -> ping(uri("localhost"), pki.trustOnlySettings())).isInstanceOf(RuntimeException.class);
    }

    @Test
    void aServerFromAnUntrustedCaIsRefused() {
        assumeRedis();
        Map<String, String> s = new LinkedHashMap<>(pki.clientSettings());
        s.putAll(pki.wrongCaSettings());
        assertThatThrownBy(() -> ping(uri("localhost"), s)).isInstanceOf(RuntimeException.class)
                .hasStackTraceContaining("PKIX path building failed");
    }

    @Test
    void theHostNameIsCheckedUnlessTurnedOff() {
        assumeRedis();
        // the certificate names localhost and 127.0.0.1, not this alias of the loopback address
        String alias = "rediss://127.0.0.2:" + redis.getMappedPort(6379);
        assumeLoopbackAlias();
        assertThatThrownBy(() -> ping(alias, pki.clientSettings())).isInstanceOf(RuntimeException.class);
        Map<String, String> lax = new LinkedHashMap<>(pki.clientSettings());
        lax.put("tls.verify-hostname", "false");
        assertThat(ping(alias, lax)).isEqualTo("v");
    }

    private static void assumeLoopbackAlias() {
        try (var s = new java.net.Socket()) {
            s.connect(new java.net.InetSocketAddress("127.0.0.2", redis.getMappedPort(6379)), 500);
        } catch (java.io.IOException e) {
            org.junit.jupiter.api.Assumptions.assumeTrue(false, "127.0.0.2 does not reach the container port on this host");
        }
    }

    @Test
    void thePluginReadsOverTlsAndItsHealthCarriesTheCertificateExpiry() throws Exception {
        assumeRedis();
        Map<String, String> s = new LinkedHashMap<>(pki.clientSettings());
        s.put("uri", uri("localhost"));
        s.put("domain", "tls");
        s.put("refresh-seconds", "3600");
        RedisSourcePlugin p = new RedisSourcePlugin();
        p.start(DatedSourceContract.context(s));
        try {
            assertThat(p.health()).startsWith("UP").containsPattern("TLS certificate CN=drishti \\(tls.cert-file\\) expires in \\d+ days");
        } finally {
            p.close();
        }
    }
}
