# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Writes the risk pack's Sutras from the taxonomy: one Markdown Sutra per product (trade layouts matched on
productType) and one per market-data, risk and reference kind. Each file explains itself: what the product or
kind is, the fields it reads, the market data it depends on and the risk it carries, so the Sutras double as
the pack's data dictionary.

    python3 packs/risk/tools/make_sutras.py            write packs/risk/sutras (replacing generated files)
    python3 packs/risk/tools/make_sutras.py --check    fail if the files on disk differ from what would be written
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import taxonomy as T
import trade_shape as S
from risk_model import Kind, Panel, Product

PACK = Path(__file__).resolve().parent.parent
OUT = PACK / "sutras"
ROOT = PACK.parent.parent
HEADER = "\n".join((ROOT / "docs" / "RACHANA_REFERENCE.md").read_text(encoding="utf-8").splitlines()[:15])
GENERATED = "<!-- Generated by packs/risk/tools/make_sutras.py from the taxonomy. Edit the taxonomy, not this file. -->"
PLAIN = re.compile(r"^[A-Za-z0-9$][A-Za-z0-9 $@._()·/%×-]*$")


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def q(v) -> str:
    """A YAML scalar: bare when unambiguous, otherwise a JSON (= YAML double-quoted) string."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if PLAIN.match(s) and not re.match(r"^(true|false|null|yes|no|on|off|y|n|~)$|^-?\d", s, re.I) and ": " not in s:
        return s
    return json.dumps(s, ensure_ascii=False)


def flow(d: dict) -> str:
    return "{ " + ", ".join(f"{k}: {q(v)}" for k, v in d.items() if v not in (None, False) or k == "emphasis" and v) + " }"


def col(label, bind, fmt=None, tone=None, total=False) -> str:
    return flow({"label": label, "bind": bind, "fmt": fmt, "tone": tone, "total": total or None})


class Writer:
    """Builds one Sutra's YAML block line by line."""

    def __init__(self):
        self.lines: list[str] = []

    def add(self, text: str = "") -> None:
        self.lines.append(text)

    def panel(self, p: Panel, relative_rows: bool = False) -> None:
        a = self.add
        a(f"  - id: {p.id}")
        a(f"    kind: {p.kind}")
        a(f"    title: {q(p.title)}")
        for k in ("code", "key"):
            if getattr(p, k):
                a(f"    {k}: {getattr(p, k)}")
        if p.area != "main":
            a(f"    area: {p.area}")
        if p.rows:
            a(f"    rows: {q(p.rows)}")
        for k in ("x", "y", "label", "value", "fmt", "tone", "limit"):
            if getattr(p, k):
                a(f"    {k}: {q(getattr(p, k))}")
        if p.series:
            a("    series:")
            for label, fld, tone in p.series:
                a(f"      - {flow({'label': label, 'value': fld, 'tone': tone})}")
        if p.columns and p.kind != "kv":
            a("    columns:")
            for c in p.columns:
                a(f"      - {col(*c)}")
        elif p.columns:
            a("    columns:")
            for c in p.columns:
                a(f"      - {col(*c)}")

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


def md_table(head: list[str], rows: list[list[str]]) -> list[str]:
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |" for r in rows]
    return out + [""]


# ---- products ------------------------------------------------------------------------------------------------
def product_name(p: Product) -> str:
    n = slug(p.code)
    return n + "-trade" if n in T.KIND else n


def chart_from_market_data(p: Product) -> Panel | None:
    """A line chart read from the first linked market-data entity that has one (curve, surface term structure)."""
    for fld, kind, _ in p.md:
        k = T.KIND.get(kind)
        line = next((x for x in k.panels if x.kind == "line"), None) if k else None
        if line:
            return Panel("line", "marketData", f"{k.label}: {line.title}", None, x=line.x, y=line.y, fmt=line.fmt, area="right",
                         code=k.mnemonic, key="F4")
    return None


def product_yaml(p: Product) -> str:
    w, a = Writer(), None
    a = w.add
    risks = p.risk[:2]
    a(f"sutra: {product_name(p)}")
    a("version: 1")
    a(f"description: {q(p.desc)}")
    a(f"match: {{ kind: trade, where: {q(chr(36) + '.productType == ' + repr(p.code))}, priority: 10 }}")
    a(f"title: {{ pill: {q(p.asset + ' · ' + p.name)}, id: $.tradeId, with: \"link($.counterparty.id, 'counterparty', $.counterparty.name)\" }}")
    a("strip:")
    strip = [("Notional", "$.currency + ' ' + fmt($.notional, 'amount0')", None, None, False),
             ("Direction", "$.direction", None, None, False),
             ("Trade date", "$.tradeDate", "date", None, False),
             ("Maturity", "$.maturityDate", "date", None, False),
             ("MTM (USD)", "$.mtm", "signed0", "sign", True)]
    strip += [(S.RISK_LABELS[r] + " (USD)", f"$.risk.{r}", "signed0", "sign", False) for r in risks]
    strip += [("Status", "$.status", None, "status", False), ("Book", "link($.book, 'book')", None, None, False)]
    for label, bind, fmt, tone, emph in strip[:8]:
        a(f"  - {flow({'label': label, 'bind': bind, 'fmt': fmt, 'tone': tone, 'emphasis': emph or None})}")
    a("panels:")
    a("  - id: terms")
    a("    kind: kv")
    a("    title: Terms")
    a("    code: TRM")
    a("    key: F2")
    a("    columns:")
    for f in p.terms:
        a(f"      - {col(f.label, '$.terms.' + f.name, f.fmt)}")
    a(f"      - {col('Effective', '$.effectiveDate', 'date')}")
    a(f"      - {col('Counterparty', '$.counterparty.name')}")
    if p.legs:
        a("  - id: legs")
        a("    kind: tabs")
        a("    title: Legs")
        a("    each: $.legs")
        a("    layout: columns")
        a("    tabTitle: \"'Leg ' + @.leg + ' · ' + @.label\"")
        a("    body:")
        a("      kind: kv")
        a("      columns:")
        for label, bind, fmt, tone in S.LEG_COLUMNS:
            a(f"        - {col(label, bind, fmt, tone)}")
    if p.schedule:
        kind, title, code, cols = S.SCHEDULES[p.schedule]
        a("  - id: schedule")
        a(f"    kind: {kind}")
        a(f"    title: {q(title)}")
        a(f"    code: {code}")
        a("    key: F3")
        a("    rows: $.schedule")
        if kind == "ladder":
            a("    highlight: \"#index == $.nextIndex\"")
        a("    columns:")
        for label, fld, fmt, tone, total in cols:
            a(f"      - {col(label, '@.' + fld, fmt, tone, total)}")
    a("  - { id: built, kind: provenance, title: How this view was built }")
    chart = chart_from_market_data(p)
    if chart:
        kind_of = next(k for f, k, _ in p.md if T.KIND.get(k) and any(x.kind == "line" for x in T.KIND[k].panels))
        fld = next(f for f, k, _ in p.md if k == kind_of)
        line = next(x for x in T.KIND[kind_of].panels if x.kind == "line")
        a("  - id: marketData")
        a("    kind: line")
        a(f"    title: {q(chart.title)}")
        a(f"    code: {chart.code}")
        a("    key: F4")
        a("    area: right")
        a(f"    source: \"link($.{fld}, '{kind_of}')\"")
        a(f"    rows: {q(line.rows[2:] if line.rows and line.rows.startswith('$.') else line.rows)}")
        a(f"    x: {line.x}")
        a(f"    y: {line.y}")
        if line.fmt:
            a(f"    fmt: {line.fmt}")
    if p.risk:
        r = p.risk[0]
        a("  - id: sensitivities")
        a("    kind: hbar")
        a(f"    title: {q(S.RISK_LABELS[r] + ' by bucket (USD)')}")
        a("    code: SENS")
        a("    area: right")
        a("    rows: $.sensitivities")
        a("    label: bucket")
        a(f"    value: {r}")
        a("    fmt: signed0")
        a("    tone: sign")
    a("  - id: pnl")
    a("    kind: line")
    a("    title: Daily P&L, last 20 days (USD)")
    a("    code: PNL")
    a("    area: right")
    a("    rows: $.pnlHistory")
    a("    x: date")
    a("    y: pnl")
    a("    fmt: signed0")
    a("  - { id: refs, kind: links, title: Linked entities, code: REFS, area: right }")
    a("keys: { F7: \"link($.nettingSet, 'netting-set')\", F8: impact, F9: raw }")
    return w.text()


def product_doc(p: Product) -> str:
    name = product_name(p)
    body = [HEADER, GENERATED, f"# {p.name} (`{name}` v1)", "", p.desc, "",
            f"**Asset class:** {p.asset} · **Family:** {p.family} · **Product type:** `{p.code}`"
            + (" · **Exchange-traded**" if p.listed else "") + "", "",
            f"Applies to trades whose `productType` is `{p.code}`. Open one with `TRD <tradeId>`.", "",
            "```sutra", product_yaml(p).rstrip(), "```", "", "## Terms", "",
            "Product-specific terms live under `terms` in the trade document.", ""]
    body += md_table(["Field", "Label", "Format"], [[f"`terms.{f.name}`", f.label, f"`{f.fmt}`" if f.fmt else "text"] for f in p.terms])
    if p.md:
        body += ["## Market data", "", "Reference fields on the trade point at the market data it is valued with. They show under "
                 "*Linked entities* and drive F8 impact (\"which trades use this curve?\").", ""]
        body += md_table(["Field", "Kind", "Selected by"], [[f"`{f}`", f"`{k}` ({T.KIND[k].label})", f"`{sel}`"] for f, k, sel in p.md])
    if p.risk:
        body += ["## Risk", ""]
        body += md_table(["Measure", "Field", "Meaning"], [[S.RISK_LABELS[r], f"`risk.{r}`", S.RISK_MEANING[r]] for r in p.risk])
        body += [f"The *{S.RISK_LABELS[p.risk[0]]} by bucket* chart reads `sensitivities[].{p.risk[0]}`.", ""]
    if p.legs:
        body += ["## Legs", "", f"{p.legs} legs under `legs`, shown side by side: " + ", ".join(c[0].lower() for c in S.LEG_COLUMNS) + ".", ""]
    if p.schedule:
        kind, title, _, cols = S.SCHEDULES[p.schedule]
        body += [f"## {title}", "", f"`schedule` rows ({kind}), F3: " + ", ".join(f"`{c[1]}`" for c in cols) + "."
                 + (" The next event is highlighted (`nextIndex`)." if kind == "ladder" else ""), ""]
    body += ["## Layout notes", "",
             "- The strip leads with size and dates, then MTM (emphasised) and the product's main risk measures.",
             "- F2 is the terms, F3 the schedule, F4 the market data it is most sensitive to; F7 opens the netting set,"
             " F8 shows impact and F9 the raw document.",
             "- Common fields (counterparty, netting set, book, trader, MTM, P&L) are described in the pack guide.", ""]
    return "\n".join(body)


# ---- kinds ---------------------------------------------------------------------------------------------------
def kind_yaml(k: Kind) -> str:
    w = Writer()
    a = w.add
    a(f"sutra: {k.kind}")
    a("version: 1")
    a(f"description: {q(k.desc)}")
    a(f"match: {{ kind: {k.kind}, priority: 10 }}")
    title = {"pill": k.pill or f"{k.group} · {k.label}", "id": f"$.{k.id_field}"}
    if k.with_:
        title["with"] = k.with_
    a(f"title: {flow(title)}")
    if k.strip:
        a("strip:")
        for label, bind, fmt, tone, emph in k.strip[:8]:
            a(f"  - {flow({'label': label, 'bind': bind, 'fmt': fmt, 'tone': tone, 'emphasis': emph or None})}")
    a("panels:")
    for p in k.panels:
        w.panel(p)
    a("  - { id: built, kind: provenance, title: How this view was built }")
    a("  - { id: refs, kind: links, title: Linked entities, code: REFS, area: right }")
    first_link = next(iter(k.links), None)
    keys = {"F8": "impact", "F9": "raw"}
    if first_link:
        keys = {"F7": f"link($.{first_link}, '{k.links[first_link][0]}')", **keys}
    a("keys: " + flow(keys))
    return w.text()


def kind_doc(k: Kind) -> str:
    body = [HEADER, GENERATED, f"# {k.label} (`{k.kind}` v1)", "", k.desc, "",
            f"**Group:** {k.group} · **Mnemonic:** `{k.mnemonic}` · **Identifiers:** `{k.prefix}…` in `{k.id_field}`", "",
            f"Open one with `{k.mnemonic} <id>`.", "", "```sutra", kind_yaml(k).rstrip(), "```", "", "## Header fields", ""]
    body += md_table(["Label", "Bound to", "Format"], [[s[0], f"`{s[1]}`", f"`{s[2]}`" if s[2] else "text"] for s in k.strip])
    body += ["## Panels", ""]
    body += md_table(["Panel", "Kind", "Rows"], [[p.title, p.kind, f"`{p.rows}`" if p.rows else "—"] for p in k.panels])
    if k.links:
        body += ["## Links", "", "Reference fields that open other entities (and feed F8 impact).", ""]
        body += md_table(["Field", "Opens"], [[f"`{f}`", f"{lab} (`{kind}`)"] for f, (kind, lab) in k.links.items()])
    if k.live:
        body += ["## Live", "", "Sample data ticks these fields: " + ", ".join(f"`{f}`" for f in k.live) + ".", ""]
    return "\n".join(body)


# ---- output --------------------------------------------------------------------------------------------------
def files() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for p in T.PRODUCTS:
        out[OUT / "products" / slug(p.asset) / f"{product_name(p)}.v1.sutra.md"] = product_doc(p)
    for k in T.KINDS:
        out[OUT / slug(k.group) / f"{k.kind}.v1.sutra.md"] = kind_doc(k)
    names = [f.name for f in out]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise SystemExit(f"duplicate Sutra names: {dupes}")
    return out


def main() -> None:
    T.check()
    want = files()
    if "--check" in sys.argv:
        stale = [str(f) for f, text in want.items() if not f.exists() or f.read_text(encoding="utf-8") != text]
        extra = [str(f) for f in OUT.rglob("*.sutra.md") if f not in want] if OUT.exists() else []
        if stale or extra:
            raise SystemExit(f"Sutras out of date; run make_sutras.py. stale={stale[:5]} extra={extra[:5]}")
        print(f"{len(want)} Sutras up to date")
        return
    for f in OUT.rglob("*.sutra.md") if OUT.exists() else []:
        if f not in want and GENERATED in f.read_text(encoding="utf-8"):
            f.unlink()
    for f, text in want.items():
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
    print(f"wrote {len(want)} Sutras ({len(T.PRODUCTS)} products, {len(T.KINDS)} kinds) to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
