# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Credit, equity and commodity products for the risk pack taxonomy."""
from risk_model import MD, Product, fields

C, E, K = "Credit", "Equity", "Commodity"
OPT = "optionType:Option type::choice(Call|Put); exerciseStyle:Exercise::choice(European|American); expiryDate:Expiry:date:date(0.1,3); strike:Strike:price2:num(20,5000,2)"

PRODUCTS = [
    # ---- credit --------------------------------------------------------------------------------------------------
    Product("CDS_SINGLE", "Single-name CDS", "cds", C, "Protection on one reference entity against a running coupon.", fields("protection:Protection::choice(Bought|Sold); coupon:Coupon:bp1:choice(100|500); seniority:Seniority::choice(Senior unsecured|Subordinated); docClause:Doc clause::choice(XR14|MR14|CR14|MM14); upfront:Upfront:pct2:rate(-0.04,0.08)"), "cashflows", MD("cds", "ois"), ["cs01", "jtd"], underlier="issuer", notional=(5e6, 50e6)),
    Product("CDS_INDEX", "CDS index (CDX / iTraxx)", "cds", C, "Protection on a standard index of names.", fields("protection:Protection::choice(Bought|Sold); index:Index::choice(CDX.NA.IG S47|CDX.NA.HY S47|iTraxx Europe S46|iTraxx Crossover S46); coupon:Coupon:bp1:choice(100|500); version:Version:amount0:int(1,3)"), "cashflows", MD("cds", "ois"), ["cs01", "jtd"], underlier="issuer", notional=(10e6, 250e6)),
    Product("CDS_TRANCHE", "Index tranche", "cds", C, "Protection on a slice of index losses between attachment points.", fields("index:Index::choice(CDX.NA.IG S47|iTraxx Europe S46); attachment:Attachment:pct0:choice(0|0.03|0.07|0.15); detachment:Detachment:pct0:choice(0.03|0.07|0.15|1); protection:Protection::choice(Bought|Sold)"), "cashflows", MD("cds", "ois", "corr"), ["cs01", "jtd"], underlier="issuer"),
    Product("CDS_SWAPTION", "CDS index option", "option", C, "Option to buy (payer) or sell (receiver) index protection.", fields("payerReceiver:Payer / receiver::choice(Payer|Receiver); strikeSpread:Strike spread:bp1:num(50,120,1); expiryDate:Expiry:date:date(0.1,0.5)"), None, MD("cds", "ois"), ["cs01", "vega"], underlier="issuer"),
    Product("FIRST_TO_DEFAULT", "First-to-default basket", "cds", C, "Pays on the first default among a small basket of names.", fields("basketSize:Names:amount0:int(3,10); spread:Spread:bp1:num(150,900,1)"), "constituents", MD("cds", "ois", "corr"), ["cs01", "jtd"], underlier="issuer"),
    Product("TRS_BOND", "Total return swap on a bond", "swap", C, "Pays the bond's total return against funding.", fields("fundingSpread:Funding spread:bp1:num(20,200,1); resetFrequency:Reset::choice(Monthly|Quarterly)"), "cashflows", MD("bond", "ois", "repo"), ["cs01", "dv01"], legs=2, underlier="bond"),
    Product("TRS_LOAN_INDEX", "Total return swap on a loan index", "swap", C, "Total return of a leveraged-loan index against SOFR.", fields("index:Index::choice(LSTA LL100|iBoxx USD Liquid Leveraged Loans); fundingSpread:Funding spread:bp1:num(100,350,1)"), "cashflows", MD("ois", "proj"), ["cs01"], legs=2),
    Product("CLN", "Credit-linked note", "note", C, "Note whose principal is reduced by a credit event on a reference entity.", fields("coupon:Coupon:pct4:rate(0.04,0.11); issuePrice:Issue price:price2:num(98,101,2)"), "coupons", MD("cds", "ois"), ["cs01", "jtd", "dv01"], underlier="issuer"),
    Product("TERM_LOAN", "Term loan", "loan", C, "Drawn loan amortising or bullet, floating over SOFR.", fields("margin:Margin:bp1:num(150,600,1); facilityType:Facility::choice(Term Loan A|Term Loan B); amortisation:Amortisation::choice(Bullet|1% p.a.|Linear)"), "amortization", MD("ois", "proj", "cds"), ["cs01", "dv01"], underlier="issuer"),
    Product("REVOLVER", "Revolving credit facility", "loan", C, "Committed facility drawn and repaid at will.", fields("commitment:Commitment:amount0:num(50000000,800000000,0); drawn:Drawn:pct0:rate(0,0.8); commitmentFee:Commitment fee:bp1:num(20,60,1); margin:Margin:bp1:num(100,300,1)"), None, MD("ois", "proj", "cds"), ["cs01"], underlier="issuer"),
    Product("CREDIT_SPREAD_OPT", "Credit spread option", "option", C, "Option on a bond's spread over its benchmark.", fields("strikeSpread:Strike spread:bp1:num(80,400,1); optionType:Type::choice(Call|Put); expiryDate:Expiry:date:date(0.25,1)"), None, MD("bond", "cds", "ois"), ["cs01", "vega"], underlier="bond"),
    Product("RISK_PARTICIPATION", "Unfunded risk participation", "cds", C, "Takes a share of the default risk on a loan for a fee.", fields("participation:Participation:pct0:rate(0.1,0.5); fee:Fee:bp1:num(50,250,1)"), None, MD("cds", "ois"), ["cs01", "jtd"], underlier="issuer"),
    # ---- equity --------------------------------------------------------------------------------------------------
    Product("EQ_CASH", "Equity position", "position", E, "Long or short shares in a listed stock.", fields("quantity:Quantity:amount0:int(1000,500000); averagePrice:Average price:price2:num(10,900,2)"), None, MD("eq", "div"), ["delta"], underlier="equity", listed=True),
    Product("EQ_FORWARD", "Equity forward", "linear", E, "Buy or sell shares at a fixed price on a future date.", fields("forwardPrice:Forward price:price2:num(10,900,2); quantity:Quantity:amount0:int(1000,300000); settlementDate:Settlement:date:date(0.25,2)"), None, MD("eq", "div", "ois"), ["delta"], underlier="equity"),
    Product("EQ_FUTURE_SINGLE", "Single-stock future", "future", E, "Exchange-traded future on one stock.", fields("contract:Contract::choice(AAPL Z6|MSFT Z6|SAP Z6); lots:Lots:amount0:int(10,1000)"), None, MD("eq", "div"), ["delta"], underlier="equity", listed=True),
    Product("EQ_INDEX_FUTURE", "Equity index future", "future", E, "Exchange-traded future on an equity index (ES, NQ, FESX…).", fields("contract:Contract::choice(ES Z6|NQ Z6|FESX Z6|NKD Z6|Z Z6); lots:Lots:amount0:int(10,3000); tradePrice:Trade price:price2:num(4000,21000,2)"), None, MD("idx", "div"), ["delta"], underlier="index", listed=True),
    Product("EQ_OPTION_LISTED", "Listed equity option", "option", E, "Exchange-traded option on a stock.", fields(OPT + "; lots:Contracts:amount0:int(10,2000)"), None, MD("eq", "eqvol", "div"), ["delta", "gamma", "vega", "theta"], underlier="equity", listed=True),
    Product("EQ_OPTION_OTC", "OTC equity option", "option", E, "Bilateral option on a stock.", fields(OPT + "; quantity:Quantity:amount0:int(1000,200000)"), None, MD("eq", "eqvol", "div", "ois"), ["delta", "gamma", "vega", "theta"], underlier="equity"),
    Product("EQ_INDEX_OPTION", "Index option", "option", E, "Option on an equity index (SPX, SX5E, NKY…).", fields(OPT + "; contracts:Contracts:amount0:int(10,2000)"), None, MD("idx", "idxvol"), ["delta", "gamma", "vega", "theta"], underlier="index"),
    Product("EQ_BARRIER", "Equity barrier option", "exotic", E, "Option activated or extinguished at a barrier.", fields(OPT + "; barrierType:Barrier::choice(Down-and-in|Down-and-out|Up-and-out); barrier:Barrier level:pct0:rate(0.6,1.3)"), "observations", MD("eq", "eqvol", "div"), ["delta", "gamma", "vega"], underlier="equity"),
    Product("EQ_ASIAN", "Equity Asian option", "exotic", E, "Payoff on the average of observed prices.", fields(OPT + "; averaging:Averaging::choice(Arithmetic|Geometric)"), "observations", MD("eq", "eqvol", "div"), ["delta", "vega"], underlier="equity"),
    Product("EQ_DIGITAL", "Equity digital option", "option", E, "Fixed payout if the stock finishes beyond the strike.", fields("optionType:Type::choice(Call|Put); strike:Strike:price2:num(20,900,2); payout:Payout:amount0:num(100000,2000000,0); expiryDate:Expiry:date:date(0.1,2)"), None, MD("eq", "eqvol", "div"), ["delta", "vega"], underlier="equity"),
    Product("EQ_CLIQUET", "Cliquet (ratchet)", "exotic", E, "Sum of capped and floored periodic returns.", fields("localCap:Local cap:pct0:rate(0.03,0.08); localFloor:Local floor:pct0:rate(-0.05,0); globalFloor:Global floor:pct0:rate(0,0.03)"), "observations", MD("idx", "idxvol"), ["delta", "vega"], underlier="index"),
    Product("AUTOCALLABLE", "Autocallable note", "exotic", E, "Redeems early when the underlier is above a trigger on an observation date.", fields("autocallTrigger:Autocall trigger:pct0:rate(0.95,1.05); couponRate:Coupon:pct2:rate(0.06,0.14); knockInBarrier:Knock-in barrier:pct0:rate(0.5,0.7); memory:Memory coupon::choice(Yes|No)"), "observations", MD("idx", "idxvol", "corr"), ["delta", "vega", "gamma"], underlier="index"),
    Product("REVERSE_CONVERTIBLE", "Reverse convertible", "note", E, "High coupon; redeems in shares if the stock falls below a barrier.", fields("coupon:Coupon:pct2:rate(0.06,0.15); barrier:Barrier:pct0:rate(0.55,0.8)"), "coupons", MD("eq", "eqvol", "div"), ["delta", "vega"], underlier="equity"),
    Product("EQ_VARIANCE_SWAP", "Variance swap", "exotic", E, "Exchanges realised variance for a strike.", fields("varianceStrike:Variance strike (vol pts):price2:num(14,32,2); vegaNotional:Vega notional:amount0:num(50000,1000000,0)"), "observations", MD("idx", "idxvol"), ["vega"], underlier="index", notional=(5e5, 1e7)),
    Product("EQ_VOL_SWAP", "Volatility swap", "exotic", E, "Exchanges realised volatility for a strike.", fields("volStrike:Vol strike:price2:num(12,30,2); vegaNotional:Vega notional:amount0:num(50000,800000,0)"), "observations", MD("idx", "idxvol"), ["vega"], underlier="index", notional=(5e5, 1e7)),
    Product("DIVIDEND_SWAP", "Dividend swap", "swap", E, "Pays realised index dividends against a fixed strike.", fields("dividendStrike:Dividend strike:price2:num(50,180,2); period:Period::choice(2026|2027|2028)"), None, MD("idx", "div"), ["delta"], underlier="index"),
    Product("EQ_TRS", "Equity total return swap", "swap", E, "Pays a stock's total return against funding.", fields("fundingSpread:Funding spread:bp1:num(20,150,1); resetFrequency:Reset::choice(Monthly|Quarterly); quantity:Quantity:amount0:int(10000,1000000)"), "cashflows", MD("eq", "div", "ois"), ["delta", "dv01"], legs=2, underlier="equity"),
    Product("PORTFOLIO_SWAP", "Portfolio (basket) swap", "swap", E, "Total return on a custom basket of stocks.", fields("constituents:Constituents:amount0:int(10,60); fundingSpread:Funding spread:bp1:num(30,120,1)"), "constituents", MD("idx", "div", "ois"), ["delta", "dv01"], legs=2, underlier="index"),
    Product("CFD", "Contract for difference", "linear", E, "Cash-settled exposure to a stock's price move.", fields("quantity:Quantity:amount0:int(1000,200000); openPrice:Open price:price2:num(10,900,2)"), None, MD("eq", "div"), ["delta"], underlier="equity"),
    Product("WARRANT", "Equity warrant", "option", E, "Issuer-listed long-dated call or put.", fields(OPT + "; ratio:Ratio:df4:num(0.1,1,2)"), None, MD("eq", "eqvol"), ["delta", "vega"], underlier="equity", listed=True),
    Product("CONVERTIBLE_BOND", "Convertible bond", "bond", E, "Bond convertible into the issuer's shares.", fields("coupon:Coupon:pct2:rate(0,0.04); conversionRatio:Conversion ratio:price2:num(5,40,2); conversionPrice:Conversion price:price2:num(20,400,2)"), "coupons", MD("eq", "eqvol", "cds", "ois"), ["delta", "cs01", "vega"], underlier="equity"),
    Product("EQ_BASKET_OPTION", "Basket option", "exotic", E, "Option on a weighted basket of stocks.", fields(OPT + "; basketSize:Stocks:amount0:int(3,10)"), "constituents", MD("idx", "idxvol", "corr"), ["delta", "vega"], underlier="index"),
    # ---- commodity -------------------------------------------------------------------------------------------------
    Product("CMD_FUTURE", "Commodity future", "future", K, "Exchange-traded future (CL, NG, GC, HG, C, W…).", fields("contract:Contract::choice(CL Z6|NG F7|GC Z6|HG H7|C Z6|W H7|BRN F7); lots:Lots:amount0:int(10,1500); tradePrice:Trade price:price2:num(3,2500,2)"), None, MD("cmd"), ["delta"], underlier="commodity", listed=True),
    Product("CMD_FORWARD", "Commodity forward", "linear", K, "OTC agreement to buy or sell at a fixed price.", fields("forwardPrice:Forward price:price2:num(3,2500,2); quantity:Quantity:amount0:int(1000,500000); deliveryMonth:Delivery::choice(Dec 2026|Mar 2027|Jun 2027)"), None, MD("cmd", "ois"), ["delta"], underlier="commodity"),
    Product("CMD_SWAP", "Commodity swap", "swap", K, "Fixed price against the average of a floating index.", fields("fixedPrice:Fixed price:price2:num(3,2500,2); quantityPerPeriod:Quantity per period:amount0:int(1000,100000); averaging:Averaging::choice(Monthly|Calendar-month)"), "fixings", MD("cmd", "ois"), ["delta"], legs=2, underlier="commodity"),
    Product("CMD_BASIS_SWAP", "Commodity basis swap", "swap", K, "Floating against floating on two locations or grades.", fields("spread:Spread:price2:num(-8,8,2); location:Locations::choice(WTI Cushing vs Midland|Henry Hub vs Waha|Brent vs WTI)"), "fixings", MD("cmd", "ois"), ["delta"], legs=2, underlier="commodity"),
    Product("CMD_FUT_OPTION", "Option on commodity future", "option", K, "Listed option on a commodity future.", fields(OPT + "; lots:Lots:amount0:int(10,1000)"), None, MD("cmd", "cmdvol"), ["delta", "gamma", "vega"], underlier="commodity", listed=True),
    Product("CMD_APO", "Average price option (APO)", "exotic", K, "Option on the monthly average price.", fields(OPT + "; averagingPeriod:Averaging::choice(Monthly|Quarterly)"), "fixings", MD("cmd", "cmdvol"), ["delta", "vega"], underlier="commodity"),
    Product("CMD_SWAPTION", "Commodity swaption", "option", K, "Option to enter a commodity swap.", fields("payerReceiver:Payer / receiver::choice(Payer|Receiver); strike:Strike:price2:num(3,2500,2); expiryDate:Expiry:date:date(0.25,1)"), None, MD("cmd", "cmdvol"), ["delta", "vega"], underlier="commodity"),
    Product("CMD_SPREAD_OPT", "Commodity spread option", "exotic", K, "Option on the spread between two commodities.", fields("spreadType:Spread::choice(Crack 3-2-1|Spark|Brent–WTI|Calendar Z6–H7); strike:Strike:price2:num(-5,30,2)"), None, MD("cmd", "cmdvol", "corr"), ["delta", "vega"], underlier="commodity"),
    Product("CMD_CALENDAR_SPREAD", "Calendar spread", "linear", K, "Long one delivery month, short another.", fields("nearMonth:Near month::choice(Dec 2026|Jan 2027); farMonth:Far month::choice(Mar 2027|Jun 2027); lots:Lots:amount0:int(10,800)"), None, MD("cmd"), ["delta"], underlier="commodity", listed=True),
    Product("CMD_INDEX_SWAP", "Commodity index swap", "swap", K, "Total return on a commodity index (BCOM, S&P GSCI).", fields("index:Index::choice(BCOM TR|S&P GSCI TR); fundingSpread:Fee:bp1:num(10,60,1)"), "cashflows", MD("cmd", "ois"), ["delta"], legs=2, underlier="commodity"),
    Product("POWER_SWAP", "Power swap", "swap", K, "Fixed price against the hourly or daily power index.", fields("hub:Hub::choice(PJM West|ERCOT North|EEX Base|N2EX); shape:Shape::choice(Baseload|Peak); mwh:Volume (MWh):amount0:int(1000,200000)"), "fixings", MD("cmd", "ois"), ["delta"], legs=2, underlier="commodity"),
    Product("GAS_SWING", "Gas swing option", "exotic", K, "Flexible daily volume within limits at a fixed price.", fields("hub:Hub::choice(Henry Hub|TTF|NBP); minDaily:Min daily (MMBtu):amount0:int(1000,10000); maxDaily:Max daily (MMBtu):amount0:int(10000,50000)"), "exercise", MD("cmd", "cmdvol"), ["delta", "vega"], underlier="commodity"),
    Product("EMISSIONS_FUTURE", "Emissions allowance future", "future", K, "Future on EU or UK carbon allowances.", fields("contract:Contract::choice(EUA Z6|UKA Z6|CCA Z6); lots:Lots:amount0:int(10,500)"), None, MD("cmd"), ["delta"], underlier="commodity", listed=True),
    Product("WEATHER_HDD", "Weather derivative (HDD/CDD)", "exotic", K, "Pays on heating or cooling degree days at a station.", fields("station:Station::choice(Chicago O'Hare|London Heathrow|Tokyo); index:Index::choice(HDD|CDD); strike:Strike (degree days):amount0:int(800,4000); tick:Tick:amount0:num(5000,25000,0)"), "observations", MD("ois"), ["delta"], underlier="commodity", notional=(1e6, 1e7)),
    Product("FREIGHT_FFA", "Freight forward agreement", "linear", K, "Cash-settled forward on a shipping route index.", fields("route:Route::choice(Capesize 5TC|Panamax 4TC|TD3C); days:Days:amount0:int(30,360); fixedRate:Rate ($/day):amount0:num(8000,40000,0)"), "fixings", MD("cmd"), ["delta"], underlier="commodity"),
]
