# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""Rates and FX products for the risk pack taxonomy."""
from risk_model import MD, Product, fields

R, X = "Rates", "FX"
SWAP_TERMS = "fixedRate:Fixed rate:pct4:rate(0.01,0.055); payFrequency:Pay frequency::choice(Annual|Semi-annual|Quarterly); dayCount:Day count::choice(ACT/360|30/360|ACT/365F); businessDay:Business day::choice(Mod. following|Following)"
OPT = "optionType:Option type::choice(Call|Put); exerciseStyle:Exercise::choice(European|American); expiryDate:Expiry:date:date(0.25,3); premium:Premium:amount0:num(20000,900000,0)"

PRODUCTS = [
    # ---- rates: linear -------------------------------------------------------------------------------------
    Product("IRS_FIXFLOAT", "Interest rate swap (fixed/float)", "swap", R, "Exchanges fixed for floating RFR-compounded payments.", fields(SWAP_TERMS), "cashflows", MD("ois", "proj", "fix"), ["dv01"], legs=2),
    Product("OIS", "Overnight index swap", "swap", R, "Fixed against compounded overnight RFR.", fields(SWAP_TERMS), "cashflows", MD("ois", "fix"), ["dv01"], legs=2),
    Product("BASIS_SWAP", "Basis swap (float/float)", "swap", R, "Two floating legs on different indices plus a spread.", fields("spread:Spread:bp1:num(-20,40,1); index1:Leg 1 index::choice(SOFR|TERM-SOFR-3M); index2:Leg 2 index::choice(TERM-SOFR-1M|TERM-SOFR-6M)"), "cashflows", MD("ois", "proj", "basis"), ["dv01"], legs=2),
    Product("XCCY_SWAP", "Cross-currency swap (non-MtM)", "swap", R, "Exchanges principal and interest in two currencies.", fields("otherCurrency:Other currency::choice(EUR|GBP|JPY|CHF); fxRateAtStart:FX at start:rate5:num(0.6,160,4); xccyBasis:Cross-currency basis:bp1:num(-35,10,1)"), "cashflows", MD("ois", "proj", "basis", "fx"), ["dv01", "fxDelta"], legs=2, underlier="pair"),
    Product("XCCY_SWAP_MTM", "Cross-currency swap (MtM resetting)", "swap", R, "Notional on one leg resets to the prevailing FX rate each period.", fields("otherCurrency:Other currency::choice(EUR|GBP|JPY); resetFrequency:Notional reset::choice(Quarterly|Semi-annual); xccyBasis:Cross-currency basis:bp1:num(-35,10,1)"), "cashflows", MD("ois", "proj", "basis", "fx"), ["dv01", "fxDelta"], legs=2, underlier="pair"),
    Product("ZC_SWAP", "Zero-coupon swap", "swap", R, "Single fixed payment at maturity against compounded floating.", fields("zeroRate:Zero rate:pct4:rate(0.015,0.05); compounding:Compounding::choice(Annual|Continuous)"), "cashflows", MD("ois", "proj"), ["dv01"], legs=2),
    Product("AMORT_SWAP", "Amortising swap", "swap", R, "Notional amortises on a schedule, typically matching a loan.", fields(SWAP_TERMS + "; amortisation:Amortisation::choice(Linear|Mortgage-style|Custom)"), "amortization", MD("ois", "proj"), ["dv01"], legs=2),
    Product("ACCRETING_SWAP", "Accreting swap", "swap", R, "Notional grows over time, e.g. for construction finance.", fields(SWAP_TERMS + "; accretionRate:Accretion:pct2:rate(0.02,0.12)"), "amortization", MD("ois", "proj"), ["dv01"], legs=2),
    Product("FWD_START_SWAP", "Forward-starting swap", "swap", R, "Swap whose accrual starts at a future date.", fields(SWAP_TERMS + "; forwardStart:Forward start:date:date(0.5,3)"), "cashflows", MD("ois", "proj"), ["dv01"], legs=2),
    Product("CMS_SWAP", "Constant maturity swap", "swap", R, "Floating leg pays a swap rate of fixed tenor, needing convexity adjustment.", fields("cmsTenor:CMS tenor::tenor(2Y|5Y|10Y|30Y); spread:Spread:bp1:num(-50,50,1)"), "cashflows", MD("ois", "proj", "swvol"), ["dv01", "vega"], legs=2),
    Product("FRA", "Forward rate agreement", "linear", R, "Cash-settled agreement on a future period's rate.", fields("fraRate:FRA rate:pct4:rate(0.02,0.055); startPeriod:Period::choice(1x4|3x6|6x9|6x12|9x12); fixingDate:Fixing date:date:date(0.1,1)"), "fixings", MD("ois", "proj"), ["dv01"], notional=(20e6, 500e6)),
    Product("STIR_FUTURE", "Short-term interest rate future", "future", R, "Exchange-traded future on a 3-month RFR period (e.g. SR3).", fields("contract:Contract::choice(SR3 Z6|SR3 H7|ER3 Z6|SON3 H7); lots:Lots:amount0:int(50,2000); tradePrice:Trade price:price2:num(95.2,96.9,3)"), None, MD("proj"), ["dv01"], listed=True),
    Product("BOND_FUTURE", "Government bond future", "future", R, "Future on a basket of deliverable government bonds.", fields("contract:Contract::choice(TY Z6|US Z6|RX Z6|G Z6); lots:Lots:amount0:int(20,800); ctd:Cheapest to deliver::pick(bond); conversionFactor:Conversion factor:df4:num(0.75,0.95,4)"), None, MD("govt", "bond", "repo"), ["dv01"], listed=True),
    # ---- rates: options ----------------------------------------------------------------------------------------
    Product("CAP", "Interest rate cap", "option", R, "Series of caplets paying when the floating rate exceeds the strike.", fields("strike:Strike:pct4:rate(0.02,0.06); capFrequency:Caplet frequency::choice(Quarterly|Semi-annual); premium:Premium:amount0:num(50000,1500000,0)"), "fixings", MD("ois", "proj", "capvol"), ["dv01", "vega"]),
    Product("FLOOR", "Interest rate floor", "option", R, "Series of floorlets paying when the floating rate is below the strike.", fields("strike:Strike:pct4:rate(0.005,0.03); floorFrequency:Floorlet frequency::choice(Quarterly|Semi-annual); premium:Premium:amount0:num(50000,1500000,0)"), "fixings", MD("ois", "proj", "capvol"), ["dv01", "vega"]),
    Product("COLLAR", "Interest rate collar", "option", R, "Long cap and short floor, usually zero-cost.", fields("capStrike:Cap strike:pct4:rate(0.04,0.06); floorStrike:Floor strike:pct4:rate(0.01,0.03)"), "fixings", MD("ois", "proj", "capvol"), ["dv01", "vega"]),
    Product("SWAPTION_EUR", "European swaption", "option", R, "Option to enter a swap at a fixed rate on one date.", fields("payerReceiver:Payer / receiver::choice(Payer|Receiver); strike:Strike:pct4:rate(0.02,0.05); expiryDate:Expiry:date:date(0.25,5); underlyingTenor:Swap tenor::tenor(2Y|5Y|10Y|30Y); settlement:Settlement::choice(Physical|Cash (par yield)); premium:Premium:amount0:num(100000,4000000,0)"), None, MD("ois", "proj", "swvol"), ["dv01", "vega"]),
    Product("SWAPTION_BERM", "Bermudan swaption", "option", R, "Swaption exercisable on several dates.", fields("payerReceiver:Payer / receiver::choice(Payer|Receiver); strike:Strike:pct4:rate(0.02,0.05); firstExercise:First exercise:date:date(0.5,3); exerciseFrequency:Exercise frequency::choice(Annual|Semi-annual)"), "exercise", MD("ois", "proj", "swvol"), ["dv01", "vega"]),
    Product("SWAPTION_AMER", "American swaption", "option", R, "Swaption exercisable at any time before expiry.", fields("payerReceiver:Payer / receiver::choice(Payer|Receiver); strike:Strike:pct4:rate(0.02,0.05); expiryDate:Expiry:date:date(0.5,3)"), None, MD("ois", "proj", "swvol"), ["dv01", "vega"]),
    Product("CMS_CAP", "CMS cap / floor", "option", R, "Caps or floors on a constant-maturity swap rate.", fields("cmsTenor:CMS tenor::tenor(10Y|30Y); strike:Strike:pct4:rate(0.02,0.06); capFloor:Cap / floor::choice(Cap|Floor)"), "fixings", MD("ois", "proj", "swvol"), ["dv01", "vega"]),
    Product("CMS_SPREAD_OPT", "CMS spread option", "option", R, "Option on the spread between two CMS rates (e.g. 10Y–2Y).", fields("longTenor:Long tenor::tenor(10Y|30Y); shortTenor:Short tenor::tenor(2Y|5Y); strike:Strike:bp1:num(-20,80,1)"), "fixings", MD("ois", "proj", "swvol", "corr"), ["dv01", "vega"]),
    Product("STIR_FUT_OPT", "STIR future option", "option", R, "Listed option on a short-term interest rate future.", fields("contract:Contract::choice(SR3 Z6 C 96.00|SR3 H7 P 95.75|ER3 Z6 C 97.50); lots:Lots:amount0:int(50,1500); premiumTicks:Premium (ticks):price2:num(2,25,1)"), None, MD("proj", "capvol"), ["dv01", "vega"], listed=True),
    Product("CALLABLE_SWAP", "Callable swap", "exotic", R, "Swap one party may cancel on call dates.", fields(SWAP_TERMS + "; callable:Callable by::choice(Us|Counterparty); firstCall:First call:date:date(1,4)"), "exercise", MD("ois", "proj", "swvol"), ["dv01", "vega"], legs=2),
    Product("RANGE_ACCRUAL_SWAP", "Range accrual swap", "exotic", R, "Coupon accrues only on days the index is inside a range.", fields("lowerBound:Lower bound:pct2:rate(0.0,0.02); upperBound:Upper bound:pct2:rate(0.04,0.07); accrualRate:Accrual rate:pct4:rate(0.03,0.07)"), "observations", MD("ois", "proj", "swvol"), ["dv01", "vega"], legs=2),
    Product("SNOWBALL_SWAP", "Snowball swap", "exotic", R, "Each coupon depends on the previous one plus a spread minus the index.", fields("initialCoupon:Initial coupon:pct4:rate(0.03,0.06); snowballSpread:Spread:bp1:num(50,250,1)"), "observations", MD("ois", "proj", "swvol"), ["dv01", "vega"], legs=2),
    Product("TARN_RATES", "Target redemption note (rates)", "exotic", R, "Terminates once cumulative coupons reach a target.", fields("target:Target coupon:pct2:rate(0.05,0.15); couponFormula:Coupon::const(2 × (Strike − Index))"), "observations", MD("ois", "proj", "swvol"), ["dv01", "vega"], legs=2),
    # ---- FX ------------------------------------------------------------------------------------------------------
    Product("FX_SPOT", "FX spot", "linear", X, "Exchange of two currencies at T+2.", fields("rate:Rate:rate5:num(0.6,160,5); valueDate:Value date:date:date(0.005,0.01)"), None, MD("fx"), ["fxDelta"], underlier="pair", notional=(1e6, 80e6)),
    Product("FX_FORWARD", "FX forward", "linear", X, "Exchange at an agreed rate on a future date.", fields("rate:Forward rate:rate5:num(0.6,160,5); valueDate:Value date:date:date(0.1,2); forwardPoints:Forward points:pips1:num(-150,300,1)"), None, MD("fx", "fxfwd", "ois"), ["fxDelta", "dv01"], underlier="pair", notional=(1e6, 150e6)),
    Product("FX_NDF", "Non-deliverable forward", "linear", X, "Cash-settled forward in USD on a restricted currency.", fields("rate:Forward rate:rate5:num(5,90,4); fixingDate:Fixing date:date:date(0.1,1); fixingSource:Fixing source::choice(PBOC|RBI|PTAX|KFTC)"), None, MD("fx", "fxfwd", "ois"), ["fxDelta"], underlier="ndf", notional=(1e6, 80e6)),
    Product("FX_SWAP", "FX swap", "swap", X, "Spot or near leg reversed on a far date.", fields("nearRate:Near rate:rate5:num(0.6,160,5); farRate:Far rate:rate5:num(0.6,160,5); swapPoints:Swap points:pips1:num(-150,300,1)"), "cashflows", MD("fx", "fxfwd", "ois"), ["fxDelta", "dv01"], legs=2, underlier="pair"),
    Product("FX_OPTION", "FX vanilla option", "option", X, "Right to exchange at a strike on expiry.", fields(OPT + "; strike:Strike:rate5:num(0.6,160,5); deltaAtTrade:Delta at trade:pct0:rate(0.1,0.6)"), None, MD("fx", "fxfwd", "fxvol"), ["fxDelta", "vega", "gamma"], underlier="pair", notional=(2e6, 100e6)),
    Product("FX_DIGITAL", "FX digital option", "option", X, "Fixed payout if the rate is beyond the strike at expiry.", fields("optionType:Type::choice(Call|Put); strike:Strike:rate5:num(0.6,160,5); payout:Payout:amount0:num(100000,3000000,0); expiryDate:Expiry:date:date(0.1,1)"), None, MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_BARRIER", "FX barrier option", "exotic", X, "Vanilla option knocked in or out when a barrier trades.", fields(OPT + "; strike:Strike:rate5:num(0.6,160,5); barrierType:Barrier::choice(Up-and-out|Down-and-out|Up-and-in|Down-and-in); barrier:Barrier level:rate5:num(0.6,165,5); rebate:Rebate:amount0:num(0,100000,0)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega", "gamma"], underlier="pair"),
    Product("FX_DOUBLE_BARRIER", "FX double-barrier option", "exotic", X, "Knocked out if either of two barriers trades.", fields(OPT + "; strike:Strike:rate5:num(0.6,160,5); lowerBarrier:Lower barrier:rate5:num(0.5,150,5); upperBarrier:Upper barrier:rate5:num(0.7,170,5)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_TOUCH", "FX one-touch / no-touch", "exotic", X, "Pays if the barrier is (or is not) touched before expiry.", fields("touchType:Type::choice(One-touch|No-touch|Double no-touch); barrier:Barrier:rate5:num(0.6,165,5); payout:Payout:amount0:num(100000,2000000,0); expiryDate:Expiry:date:date(0.1,1)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_ASIAN", "FX average-rate option", "exotic", X, "Payoff on the average rate over fixings.", fields(OPT + "; strike:Strike:rate5:num(0.6,160,5); averaging:Averaging::choice(Arithmetic|Geometric)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_TARF", "FX target redemption forward", "exotic", X, "Series of leveraged forwards ending when a profit target is hit.", fields("strike:Strike:rate5:num(0.6,160,5); target:Target (pips):amount0:int(500,3000); leverage:Leverage::choice(1x|2x)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_ACCUMULATOR", "FX accumulator", "exotic", X, "Buys (or sells) daily at a discount until knock-out.", fields("strike:Strike:rate5:num(0.6,160,5); knockOut:Knock-out:rate5:num(0.6,165,5); dailyAmount:Daily amount:amount0:num(100000,2000000,0)"), "observations", MD("fx", "fxvol"), ["fxDelta", "vega"], underlier="pair"),
    Product("FX_VARIANCE_SWAP", "FX variance swap", "exotic", X, "Exchanges realised against strike variance of an FX rate.", fields("varianceStrike:Variance strike (vol pts):price2:num(6,18,2); vegaNotional:Vega notional:amount0:num(50000,500000,0)"), "observations", MD("fx", "fxvol"), ["vega"], underlier="pair", notional=(5e5, 5e6)),
    Product("FX_QUANTO", "Quanto option", "exotic", X, "Option on a foreign underlying paid in domestic currency at a fixed rate.", fields(OPT + "; strike:Strike:price2:num(80,5000,2); quantoRate:Quanto rate:rate5:num(0.6,1.5,4)"), None, MD("fx", "fxvol", "corr"), ["fxDelta", "vega"], underlier="pair"),
]
