/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.mongodb;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.tls.TlsException;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.TlsFixture;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.model.Filters;
import java.nio.file.Files;
import java.time.Duration;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.bson.BsonDocument;
import org.bson.Document;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * MongoDB over TLS and with X.509 certificate log-in: the wiring (no Docker), then a real MongoDB 7 started with
 * {@code --tlsMode requireTLS} and certificates generated by the test. Skipped where Docker is not reachable.
 */
class MongoTlsTest {

    private static TlsFixture pki;
    private static GenericContainer<?> mongo;

    @BeforeAll
    static void start() throws Exception {
        pki = new TlsFixture();
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
        } catch (RuntimeException e) {
            docker = false;
        }
        if (!docker) {
            return;
        }
        Files.writeString(pki.path("server-full.pem"), Files.readString(pki.path("server.pem")) + Files.readString(pki.path("server.key")));
        GenericContainer<?> c = new GenericContainer<>("mongo:7").withExposedPorts(27017)
                .withCommand("mongod", "--bind_ip_all", "--tlsMode", "requireTLS", "--tlsCertificateKeyFile", "/tls/server-full.pem", "--tlsCAFile",
                        "/tls/ca.pem", "--tlsAllowConnectionsWithoutCertificates")
                .waitingFor(Wait.forLogMessage(".*Waiting for connections.*", 1).withStartupTimeout(Duration.ofMinutes(2)));
        for (String f : new String[] {"ca.pem", "server-full.pem"}) {
            c.withCopyFileToContainer(MountableFile.forHostPath(pki.path(f), 0644), "/tls/" + f);
        }
        mongo = c;
        mongo.start();
    }

    @AfterAll
    static void stop() {
        if (mongo != null) {
            mongo.stop();
        }
        pki.delete();
    }

    private static String uri() {
        return "mongodb://localhost:" + mongo.getMappedPort(27017);
    }

    private static void assumeMongo() {
        org.junit.jupiter.api.Assumptions.assumeTrue(mongo != null, "Docker is needed");
    }

    // ---- wiring, without a server

    @Test
    void tlsSettingsWithoutTlsBeingOnAreRefusedNotIgnored() {
        assertThatThrownBy(() -> MongoTls.plan(Map.of("tls.ca-file", "/x.pem"), "mongodb://h:27017", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.* is set but TLS is not switched on: set tls.enabled: true");
        assertThatThrownBy(() -> MongoTls.plan(Map.of("tls.enabled", "true"), "mongodb://h:27017/?tls=false", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls=false");
        assertThat(MongoTls.plan(Map.of(), "mongodb://h:27017", System::getenv).tls()).isNull();
        assertThat(MongoTls.plan(Map.of(), "mongodb://h:27017/?tls=true", System::getenv).tls()).isNotNull();
    }

    @Test
    void x509NeedsAClientCertificateAndAKnownMechanism() {
        assertThatThrownBy(() -> MongoTls.plan(Map.of("auth-mechanism", "x509", "tls.enabled", "true"), "mongodb://h", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("auth-mechanism: x509 logs in with a client certificate");
        assertThatThrownBy(() -> MongoTls.plan(Map.of("auth-mechanism", "x509"), "mongodb://h", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("switch TLS on");
        assertThatThrownBy(() -> MongoTls.plan(Map.of("auth-mechanism", "kerberos"), "mongodb://h", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("is not x509");
    }

    @Test
    void aMissingCaFileFailsTheStartNamingTheFile() {
        assertThatThrownBy(() -> MongoTls.plan(Map.of("tls.enabled", "true", "tls.ca-file", "/etc/drishti/nope.pem"), "mongodb://h", System::getenv))
                .isInstanceOf(TlsException.class).hasMessageContaining("tls.ca-file '/etc/drishti/nope.pem'");
    }

    // ---- a real MongoDB with TLS

    private static Map<String, String> settings(Map<String, String> tls) {
        Map<String, String> s = new LinkedHashMap<>(tls);
        s.put("uri", uri());
        s.put("database", "drishti");
        s.put("collection", "tlsdesk");
        s.put("connect-timeout-ms", "3000");
        s.put("refresh-seconds", "3600");
        return s;
    }

    /** Puts one trade into the collection through a TLS connection made by the same module. */
    private static void seed(Map<String, String> tls) {
        MongoTls.Plan plan = MongoTls.plan(settings(tls), uri(), System::getenv);
        MongoClientSettings.Builder b = MongoClientSettings.builder().applyConnectionString(new ConnectionString(uri()));
        MongoTls.apply(b, plan);
        try (MongoClient c = MongoClients.create(b.build())) {
            var db = c.getDatabase("drishti");
            MongoLayout.prepare(db, "tlsdesk", false);
            BsonDocument d = MongoLayout.record("trade", "T-1", LocalDate.of(2026, 9, 29), "{\"tradeId\":\"T-1\",\"mtm\":5}", Map.of(),
                    MongoLayout.DocFormat.BSON, null);
            db.getCollection("tlsdesk", BsonDocument.class).replaceOne(Filters.eq("_id", d.get("_id")), d,
                    new com.mongodb.client.model.ReplaceOptions().upsert(true));
        }
    }

    private static Map<String, String> withEnabled(Map<String, String> tls) {
        Map<String, String> s = new LinkedHashMap<>(tls);
        s.put("tls.enabled", "true");
        return s;
    }

    @Test
    void aTrustedServerIsReadAndHealthCarriesTheCertificateExpiry() throws Exception {
        assumeMongo();
        Map<String, String> tls = withEnabled(pki.clientSettings());
        seed(tls);
        MongoSourcePlugin p = new MongoSourcePlugin();
        p.start(DatedSourceContract.context(settings(tls)));
        try {
            assertThat(p.fetch(com.ash.drishti.api.EntityRef.of("trade", "T-1"))).isPresent();
            assertThat(p.health()).startsWith("UP").containsPattern("TLS certificate CN=drishti \\(tls.cert-file\\) expires in \\d+ days");
        } finally {
            p.close();
        }
    }

    @Test
    void anUntrustedServerIsRefused() {
        assumeMongo();
        Map<String, String> tls = withEnabled(pki.wrongCaSettings());
        MongoSourcePlugin p = new MongoSourcePlugin();
        p.start(DatedSourceContract.context(settings(tls)));
        try {
            assertThat(p.health()).startsWith("DOWN: cannot reach MongoDB");
        } finally {
            p.close();
        }
    }

    @Test
    void plainTextToATlsOnlyServerIsDown() {
        assumeMongo();
        MongoSourcePlugin p = new MongoSourcePlugin();
        p.start(DatedSourceContract.context(settings(Map.of())));
        try {
            assertThat(p.health()).startsWith("DOWN: cannot reach MongoDB");
        } finally {
            p.close();
        }
    }

    @Test
    void theClientCertificateIsTheLoginWithX509() throws Exception {
        assumeMongo();
        Map<String, String> tls = withEnabled(pki.clientSettings());
        seed(tls);
        Map<String, String> x509 = new LinkedHashMap<>(tls);
        x509.put("auth-mechanism", "x509");
        // before the user exists in $external the server refuses the login
        MongoSourcePlugin before = new MongoSourcePlugin();
        before.start(DatedSourceContract.context(settings(x509)));
        try {
            assertThat(before.health()).startsWith("DOWN");
        } finally {
            before.close();
        }
        MongoClientSettings.Builder b = MongoClientSettings.builder().applyConnectionString(new ConnectionString(uri()));
        MongoTls.apply(b, MongoTls.plan(settings(tls), uri(), System::getenv));
        try (MongoClient c = MongoClients.create(b.build())) {
            c.getDatabase("$external").runCommand(new Document("createUser", "CN=drishti").append("roles",
                    List.of(new Document("role", "readWrite").append("db", "drishti"))));
        }
        MongoSourcePlugin after = new MongoSourcePlugin();
        after.start(DatedSourceContract.context(settings(x509)));
        try {
            assertThat(after.fetch(com.ash.drishti.api.EntityRef.of("trade", "T-1"))).isPresent();
            assertThat(after.health()).startsWith("UP");
        } finally {
            after.close();
        }
    }
}
