-- Project Drishti · Any data. Any domain. One grammar.
--
-- Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
-- All rights reserved.
--
-- PROPRIETARY AND CONFIDENTIAL.
--
-- This file is the confidential and proprietary property of Ashutosh Sinha.
-- Unauthorised copying, use, modification, distribution or disclosure of this
-- file, via any medium, is strictly prohibited except with the express prior
-- written permission of the copyright holder.
--
-- See the LICENSE file in the root of this repository for the full terms.
-- Drishti identity schema for PostgreSQL. Applied at start-up; every statement is idempotent (IF NOT EXISTS), so this
-- file is the whole schema, not a migration. Its twin is schema-sqlite.sql; the JPA entities in
-- com.ash.drishti.identity.db map onto both, and a test checks each against them.

CREATE TABLE IF NOT EXISTS drishti_user (
    username             VARCHAR(64)  PRIMARY KEY,
    display_name         VARCHAR(200) NOT NULL,
    email                VARCHAR(320) NOT NULL DEFAULT '',
    desk                 VARCHAR(200) NOT NULL DEFAULT '',
    enabled              BOOLEAN      NOT NULL,
    must_change_password BOOLEAN      NOT NULL,
    password_hash        VARCHAR(512) NOT NULL,
    failed_attempts      INTEGER      NOT NULL DEFAULT 0,
    locked_until         TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at        TIMESTAMP WITH TIME ZONE,
    password_changed_at  TIMESTAMP WITH TIME ZONE,
    packs_assigned       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS drishti_user_role (
    username VARCHAR(64) NOT NULL REFERENCES drishti_user (username) ON DELETE CASCADE,
    role     VARCHAR(64) NOT NULL,
    PRIMARY KEY (username, role)
);

CREATE TABLE IF NOT EXISTS drishti_user_pack (
    username VARCHAR(64) NOT NULL REFERENCES drishti_user (username) ON DELETE CASCADE,
    pack     VARCHAR(64) NOT NULL,
    PRIMARY KEY (username, pack)
);

CREATE TABLE IF NOT EXISTS drishti_role (
    name        VARCHAR(64)  PRIMARY KEY,
    description VARCHAR(500) NOT NULL DEFAULT '',
    raw_json    BOOLEAN      NOT NULL DEFAULT FALSE,
    author      BOOLEAN      NOT NULL DEFAULT FALSE,
    approve     BOOLEAN      NOT NULL DEFAULT FALSE,
    admin       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by  VARCHAR(64)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS drishti_role_kind (
    role VARCHAR(64) NOT NULL REFERENCES drishti_role (name) ON DELETE CASCADE,
    kind VARCHAR(80) NOT NULL,
    PRIMARY KEY (role, kind)
);

-- Powers added after the first release, one row each: a new power needs no new column. calc: may use Calc;
-- no-layout: may not customise layouts (layout mode is allowed by default, so the row marks its absence).
CREATE TABLE IF NOT EXISTS drishti_role_power (
    role  VARCHAR(64) NOT NULL REFERENCES drishti_role (name) ON DELETE CASCADE,
    power VARCHAR(32) NOT NULL,
    PRIMARY KEY (role, power)
);

CREATE TABLE IF NOT EXISTS drishti_audit (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at      TIMESTAMP WITH TIME ZONE NOT NULL,
    actor   VARCHAR(64)  NOT NULL,
    action  VARCHAR(64)  NOT NULL,
    subject VARCHAR(200) NOT NULL DEFAULT '',
    detail  TEXT         NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS drishti_audit_subject ON drishti_audit (subject, id);
CREATE INDEX IF NOT EXISTS drishti_audit_actor ON drishti_audit (actor, id);

CREATE TABLE IF NOT EXISTS drishti_preference (
    username   VARCHAR(64)  NOT NULL,
    namespace  VARCHAR(64)  NOT NULL,
    name       VARCHAR(64)  NOT NULL,
    document   TEXT         NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (username, namespace, name)
);

CREATE TABLE IF NOT EXISTS drishti_design (
    username   VARCHAR(64) NOT NULL,
    id         VARCHAR(64) NOT NULL,
    document   TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (username, id)
);

CREATE TABLE IF NOT EXISTS drishti_design_sample (
    username   VARCHAR(64) NOT NULL,
    design_id  VARCHAR(64) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    content    TEXT NOT NULL,
    PRIMARY KEY (username, design_id, name)
);

CREATE TABLE IF NOT EXISTS drishti_pack_state (
    name       VARCHAR(64)  PRIMARY KEY,
    enabled    BOOLEAN      NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(64)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS drishti_alert (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(64)  NOT NULL,
    at         TIMESTAMP WITH TIME ZONE NOT NULL,
    rule       VARCHAR(64)  NOT NULL,
    kind       VARCHAR(80)  NOT NULL,
    entity_id  VARCHAR(200) NOT NULL,
    severity   VARCHAR(16)  NOT NULL,
    message    TEXT         NOT NULL,
    generation BIGINT       NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_alert_user ON drishti_alert (username, id);

CREATE TABLE IF NOT EXISTS drishti_api_token (
    id           VARCHAR(24)  PRIMARY KEY,
    username     VARCHAR(64)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    secret_hash  VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at   TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS drishti_api_token_user ON drishti_api_token (username);

-- Console sign-in sessions: a row per session, by a hash of its id; signing out, or disabling, deleting or resetting
-- the password of the user, removes the rows, and the console then refuses the cookie.
CREATE TABLE IF NOT EXISTS drishti_session (
    id_hash    VARCHAR(64) PRIMARY KEY,
    username   VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_session_user ON drishti_session (username);
CREATE INDEX IF NOT EXISTS drishti_session_expires ON drishti_session (expires_at);

CREATE TABLE IF NOT EXISTS drishti_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       VARCHAR(64)   NOT NULL,
    entity_id  VARCHAR(200)  NOT NULL,
    path       VARCHAR(200),
    username   VARCHAR(64)   NOT NULL,
    body       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_note_entity ON drishti_note (kind, entity_id);

CREATE TABLE IF NOT EXISTS drishti_access (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at            TIMESTAMP WITH TIME ZONE NOT NULL,
    username      VARCHAR(64)  NOT NULL,
    action        VARCHAR(16)  NOT NULL,
    kind          VARCHAR(64),
    entity_id     VARCHAR(200),
    detail        VARCHAR(500),
    business_date VARCHAR(10)
);
CREATE INDEX IF NOT EXISTS drishti_access_entity ON drishti_access (kind, entity_id, at);
CREATE INDEX IF NOT EXISTS drishti_access_user ON drishti_access (username, at);
CREATE INDEX IF NOT EXISTS drishti_access_at ON drishti_access (at);

-- Collaboration (docs/architecture/COLLABORATION.md): shares, comment threads, the inbox, the email outbox and legal holds.
-- Every table of the design is created here so later build steps add none; step 2 uses share, share_recipient and inbox.

CREATE TABLE IF NOT EXISTS drishti_share (
    id VARCHAR(30) PRIMARY KEY,
    sender VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    kind VARCHAR(64) NOT NULL,
    entity_id VARCHAR(200) NOT NULL,
    panel_id VARCHAR(100),
    gate_kind VARCHAR(64),
    pin_date DATE,
    pin_live BOOLEAN NOT NULL,
    pin_known_at TIMESTAMP WITH TIME ZONE,
    pin_generation BIGINT NOT NULL,
    pin_source VARCHAR(100),
    body VARCHAR(4000) NOT NULL,
    masked_spans VARCHAR(2000) NOT NULL,
    channels VARCHAR(40) NOT NULL,
    thread_id VARCHAR(30),
    hash VARCHAR(64) NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_share_sender ON drishti_share (sender, id);
CREATE INDEX IF NOT EXISTS drishti_share_entity ON drishti_share (kind, entity_id);

CREATE TABLE IF NOT EXISTS drishti_share_recipient (
    share_id VARCHAR(30) NOT NULL,
    seq INTEGER NOT NULL,
    addressed VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    state VARCHAR(16) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (share_id, seq)
);
CREATE INDEX IF NOT EXISTS drishti_share_recipient_user ON drishti_share_recipient (username, share_id);

CREATE TABLE IF NOT EXISTS drishti_thread (
    id VARCHAR(30) PRIMARY KEY,
    kind VARCHAR(64) NOT NULL,
    entity_id VARCHAR(200) NOT NULL,
    anchor VARCHAR(8) NOT NULL,
    panel_id VARCHAR(100),
    path VARCHAR(200),
    gate_kind VARCHAR(64),
    anchor_label VARCHAR(200) NOT NULL,
    state VARCHAR(10) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_at TIMESTAMP WITH TIME ZONE NOT NULL,
    comments INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_thread_entity ON drishti_thread (kind, entity_id);

CREATE TABLE IF NOT EXISTS drishti_comment (
    id VARCHAR(30) PRIMARY KEY,
    thread_id VARCHAR(30) NOT NULL,
    author VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    edited_at TIMESTAMP WITH TIME ZONE,
    revision INTEGER NOT NULL,
    pin_date DATE,
    pin_live BOOLEAN NOT NULL,
    pin_known_at TIMESTAMP WITH TIME ZONE,
    pin_generation BIGINT NOT NULL,
    pin_source VARCHAR(100),
    body VARCHAR(4000) NOT NULL,
    masked_spans VARCHAR(2000) NOT NULL,
    state VARCHAR(10) NOT NULL,
    state_reason VARCHAR(400)
);
CREATE INDEX IF NOT EXISTS drishti_comment_thread ON drishti_comment (thread_id, created_at);

CREATE TABLE IF NOT EXISTS drishti_comment_revision (
    comment_id VARCHAR(30) NOT NULL,
    revision INTEGER NOT NULL,
    at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor VARCHAR(64) NOT NULL,
    action VARCHAR(12) NOT NULL,
    body VARCHAR(4000),
    reason VARCHAR(400),
    prev_hash VARCHAR(64) NOT NULL,
    hash VARCHAR(64) NOT NULL,
    PRIMARY KEY (comment_id, revision)
);

CREATE TABLE IF NOT EXISTS drishti_mention (
    comment_id VARCHAR(30) NOT NULL,
    target VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (comment_id, target)
);
CREATE INDEX IF NOT EXISTS drishti_mention_target ON drishti_mention (target, created_at);

-- A legacy note and the comment it became (the import, and the deprecated /notes facade): note_id is drishti_note.id.
CREATE TABLE IF NOT EXISTS drishti_note_link (
    note_id BIGINT PRIMARY KEY,
    comment_id VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS drishti_follow (
    thread_id VARCHAR(30) NOT NULL,
    username VARCHAR(64) NOT NULL,
    muted BOOLEAN NOT NULL,
    since TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (thread_id, username)
);

CREATE TABLE IF NOT EXISTS drishti_inbox (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    at TIMESTAMP WITH TIME ZONE NOT NULL,
    type VARCHAR(12) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    entity_id VARCHAR(200) NOT NULL,
    panel_id VARCHAR(100),
    share_id VARCHAR(30),
    thread_id VARCHAR(30),
    comment_id VARCHAR(30),
    actor VARCHAR(64) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS drishti_inbox_user ON drishti_inbox (username, seq);

CREATE TABLE IF NOT EXISTS drishti_outbox (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(12) NOT NULL,
    recipient VARCHAR(200) NOT NULL,
    template VARCHAR(40) NOT NULL,
    ref_id VARCHAR(30) NOT NULL,
    state VARCHAR(10) NOT NULL,
    attempts INTEGER NOT NULL,
    next_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_until TIMESTAMP WITH TIME ZONE,
    leased_by VARCHAR(64),
    last_error VARCHAR(400),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS drishti_outbox_due ON drishti_outbox (state, next_at);

CREATE TABLE IF NOT EXISTS drishti_collab_hold (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(8) NOT NULL,
    kind VARCHAR(64),
    entity_id VARCHAR(200),
    username VARCHAR(64),
    thread_id VARCHAR(30),
    reason VARCHAR(400) NOT NULL,
    placed_by VARCHAR(64) NOT NULL,
    placed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    released_by VARCHAR(64),
    released_at TIMESTAMP WITH TIME ZONE
);
