-- Project Drishti · Any data. Any domain. One grammar.
--
-- Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
-- All rights reserved.
--
-- PROPRIETARY AND CONFIDENTIAL.
--
-- This file is the confidential and proprietary property of Ashutosh Sinha.
-- Unauthorised copying, use, modification, distribution or disclosure of this
-- file, via any medium, is strictly prohibited except with the express prior
-- written permission of the copyright holder.
--
-- See the LICENSE file in the root of this repository for the full terms.
-- Drishti identity schema for PostgreSQL. Applied at start-up; every statement is idempotent (IF NOT EXISTS), so this
-- file is the whole schema, not a migration. Its twin is schema-sqlite.sql; the JPA entities in
-- com.ash.drishti.identity.db map onto both, and a test checks each against them.

CREATE TABLE IF NOT EXISTS drishti_user (
    username             VARCHAR(64)  PRIMARY KEY,
    display_name         VARCHAR(200) NOT NULL,
    email                VARCHAR(320) NOT NULL DEFAULT '',
    desk                 VARCHAR(200) NOT NULL DEFAULT '',
    enabled              BOOLEAN      NOT NULL,
    must_change_password BOOLEAN      NOT NULL,
    password_hash        VARCHAR(512) NOT NULL,
    failed_attempts      INTEGER      NOT NULL DEFAULT 0,
    locked_until         TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at        TIMESTAMP WITH TIME ZONE,
    password_changed_at  TIMESTAMP WITH TIME ZONE,
    packs_assigned       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS drishti_user_role (
    username VARCHAR(64) NOT NULL REFERENCES drishti_user (username) ON DELETE CASCADE,
    role     VARCHAR(64) NOT NULL,
    PRIMARY KEY (username, role)
);

CREATE TABLE IF NOT EXISTS drishti_user_pack (
    username VARCHAR(64) NOT NULL REFERENCES drishti_user (username) ON DELETE CASCADE,
    pack     VARCHAR(64) NOT NULL,
    PRIMARY KEY (username, pack)
);

CREATE TABLE IF NOT EXISTS drishti_role (
    name        VARCHAR(64)  PRIMARY KEY,
    description VARCHAR(500) NOT NULL DEFAULT '',
    raw_json    BOOLEAN      NOT NULL DEFAULT FALSE,
    author      BOOLEAN      NOT NULL DEFAULT FALSE,
    approve     BOOLEAN      NOT NULL DEFAULT FALSE,
    admin       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by  VARCHAR(64)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS drishti_role_kind (
    role VARCHAR(64) NOT NULL REFERENCES drishti_role (name) ON DELETE CASCADE,
    kind VARCHAR(80) NOT NULL,
    PRIMARY KEY (role, kind)
);

-- Powers added after the first release (calc: may use Calc), one row each: a new power needs no new column.
CREATE TABLE IF NOT EXISTS drishti_role_power (
    role  VARCHAR(64) NOT NULL REFERENCES drishti_role (name) ON DELETE CASCADE,
    power VARCHAR(32) NOT NULL,
    PRIMARY KEY (role, power)
);

CREATE TABLE IF NOT EXISTS drishti_audit (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at      TIMESTAMP WITH TIME ZONE NOT NULL,
    actor   VARCHAR(64)  NOT NULL,
    action  VARCHAR(64)  NOT NULL,
    subject VARCHAR(200) NOT NULL DEFAULT '',
    detail  TEXT         NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS drishti_audit_subject ON drishti_audit (subject, id);
CREATE INDEX IF NOT EXISTS drishti_audit_actor ON drishti_audit (actor, id);

CREATE TABLE IF NOT EXISTS drishti_preference (
    username   VARCHAR(64)  NOT NULL,
    namespace  VARCHAR(64)  NOT NULL,
    name       VARCHAR(64)  NOT NULL,
    document   TEXT         NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (username, namespace, name)
);

CREATE TABLE IF NOT EXISTS drishti_pack_state (
    name       VARCHAR(64)  PRIMARY KEY,
    enabled    BOOLEAN      NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(64)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS drishti_alert (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(64)  NOT NULL,
    at         TIMESTAMP WITH TIME ZONE NOT NULL,
    rule       VARCHAR(64)  NOT NULL,
    kind       VARCHAR(80)  NOT NULL,
    entity_id  VARCHAR(200) NOT NULL,
    severity   VARCHAR(16)  NOT NULL,
    message    TEXT         NOT NULL,
    generation BIGINT       NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_alert_user ON drishti_alert (username, id);

CREATE TABLE IF NOT EXISTS drishti_api_token (
    id           VARCHAR(24)  PRIMARY KEY,
    username     VARCHAR(64)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    secret_hash  VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at   TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS drishti_api_token_user ON drishti_api_token (username);

CREATE TABLE IF NOT EXISTS drishti_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       VARCHAR(64)   NOT NULL,
    entity_id  VARCHAR(200)  NOT NULL,
    path       VARCHAR(200),
    username   VARCHAR(64)   NOT NULL,
    body       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS drishti_note_entity ON drishti_note (kind, entity_id);

CREATE TABLE IF NOT EXISTS drishti_access (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at            TIMESTAMP WITH TIME ZONE NOT NULL,
    username      VARCHAR(64)  NOT NULL,
    action        VARCHAR(16)  NOT NULL,
    kind          VARCHAR(64),
    entity_id     VARCHAR(200),
    detail        VARCHAR(500),
    business_date VARCHAR(10)
);
CREATE INDEX IF NOT EXISTS drishti_access_entity ON drishti_access (kind, entity_id, at);
CREATE INDEX IF NOT EXISTS drishti_access_user ON drishti_access (username, at);
CREATE INDEX IF NOT EXISTS drishti_access_at ON drishti_access (at);
