# Project Drishti · Any data. Any domain. One grammar.
#
# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
# All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL.
#
# This file is the confidential and proprietary property of Ashutosh Sinha.
# Unauthorised copying, use, modification, distribution or disclosure of this
# file, via any medium, is strictly prohibited except with the express prior
# written permission of the copyright holder.
#
# See the LICENSE file in the root of this repository for the full terms.

"""`drishti.py completion bash|zsh|powershell`: a shell completion script generated from the argparse tree.

It completes groups, commands, actions and options (so it is always current), the choices of options that have them, files
for options that take a value, and pack names (the folders of ./packs and of the current folder) for --pack.
zsh uses the bash script through bashcompinit.
"""
from __future__ import annotations

import argparse

SHELLS = ("bash", "zsh", "powershell")
PACK_OPTIONS = ("--pack",)


def walk(parser: argparse.ArgumentParser, path: tuple = ()) -> dict:
    """{path tuple: {"subs": [names], "opts": [flags], "values": {flag: choices or None}}} for the whole tree."""
    node = {"subs": [], "opts": [], "values": {}}
    out = {path: node}
    for a in parser._actions:                                     # noqa: SLF001 - argparse has no public tree API
        if isinstance(a, argparse._SubParsersAction):             # noqa: SLF001
            for name, sub in a.choices.items():
                node["subs"].append(name)
                out.update(walk(sub, path + (name,)))
        for o in a.option_strings:
            node["opts"].append(o)
            if a.nargs != 0:
                node["values"][o] = list(a.choices) if a.choices else None
    return out


def key(path: tuple) -> str:
    return " ".join(path)


def bash(tree: dict, prog: str) -> str:
    cases_subs, cases_opts, cases_vals = [], [], []
    for path, n in tree.items():
        k = key(path)
        if n["subs"]:
            cases_subs.append(f'    "{k}") subs="{" ".join(n["subs"])}" ;;')
        cases_opts.append(f'    "{k}") opts="{" ".join(sorted(n["opts"]))}"; vals="{" ".join(sorted(n["values"]))}" ;;')
        for flag, ch in n["values"].items():
            if ch:
                cases_vals.append(f'    "{k}|{flag}") choices="{" ".join(map(str, ch))}" ;;')
    return f'''# bash completion for {prog}: generated by `{prog} completion bash`
#   source <({prog} completion bash)         or save it as ~/.local/share/bash-completion/completions/{prog}
_drishti_complete() {{
  local cur prev path="" i w subs="" opts="" vals="" choices=""
  cur="${{COMP_WORDS[COMP_CWORD]}}"; prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  for ((i=1; i<COMP_CWORD; i++)); do          # the command path: words that name a child of the node reached so far
    w="${{COMP_WORDS[i]}}"
    case "$path|$w" in
{chr(10).join(f'      "{key(p[:-1])}|{p[-1]}") path="{key(p)}" ;;' for p in tree if p)}
    esac
  done
  case "$path" in
{chr(10).join(cases_subs)}
  esac
  case "$path" in
{chr(10).join(cases_opts)}
  esac
  case "$path|$prev" in
{chr(10).join(cases_vals)}
    *) choices="" ;;
  esac
  if [[ -n "$choices" ]]; then COMPREPLY=($(compgen -W "$choices" -- "$cur")); return; fi
  if [[ " $vals " == *" $prev "* ]]; then      # an option that takes a value
    if [[ "$prev" == --pack ]]; then COMPREPLY=($(compgen -W "$(ls packs 2>/dev/null)" -- "$cur") $(compgen -d -- "$cur")); return; fi
    COMPREPLY=($(compgen -f -- "$cur")); return
  fi
  if [[ "$cur" == -* ]]; then COMPREPLY=($(compgen -W "$opts" -- "$cur")); return; fi
  if [[ -n "$subs" ]]; then COMPREPLY=($(compgen -W "$subs" -- "$cur")); return; fi
  COMPREPLY=($(compgen -f -- "$cur"))
}}
complete -o filenames -F _drishti_complete {prog}
complete -o filenames -F _drishti_complete {prog.removesuffix(".py")}
'''


def zsh(tree: dict, prog: str) -> str:
    return (f"# zsh completion for {prog}: generated by `{prog} completion zsh`\n#   source <({prog} completion zsh)   (in ~/.zshrc, after compinit)\n"
            "autoload -U +X compinit && compinit\nautoload -U +X bashcompinit && bashcompinit\n" + bash(tree, prog))


def powershell(tree: dict, prog: str) -> str:
    rows = []
    for path, n in tree.items():
        words = sorted(n["subs"] + n["opts"])
        rows.append(f"    '{key(path)}' = @({', '.join(repr(w) for w in words)})")
    table = "\n".join(rows)
    return f"""# PowerShell completion for {prog}: generated by `{prog} completion powershell`
#   {prog} completion powershell | Out-String | Invoke-Expression      (add the line to $PROFILE to keep it)
$script:DrishtiTree = @{{
{table}
}}
$script:DrishtiBlock = {{
  param($wordToComplete, $commandAst, $cursorPosition)
  $words = @($commandAst.CommandElements | ForEach-Object {{ $_.ToString() }})
  $path = ''
  foreach ($w in $words | Select-Object -Skip 1) {{
    $try = (($path + ' ' + $w).Trim())
    if ($script:DrishtiTree.ContainsKey($try)) {{ $path = $try }}
  }}
  $script:DrishtiTree[$path] | Where-Object {{ $_ -like "$wordToComplete*" }} |
    ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }}
}}
Register-ArgumentCompleter -Native -CommandName '{prog}', '{prog.removesuffix(".py")}', 'python', 'python3' -ScriptBlock $script:DrishtiBlock
"""


def generate(shell: str, parser: argparse.ArgumentParser, prog: str = "drishti.py") -> str:
    tree = walk(parser)
    return {"bash": bash, "zsh": zsh, "powershell": powershell}[shell](tree, prog)
