/*
 * Project Drishti · Any data. Any domain. One grammar.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.drishti.plugin.activemq;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.ash.drishti.api.SourcePlugin;
import com.ash.drishti.api.tls.TlsContexts;
import com.ash.drishti.api.tls.TlsException;
import com.ash.drishti.api.tls.TlsMaterial;
import com.ash.drishti.api.tls.TlsSettings;
import com.ash.drishti.testkit.DatedSourceContract;
import com.ash.drishti.testkit.MessageSourceContract;
import com.ash.drishti.testkit.TestPki;
import jakarta.jms.Connection;
import jakarta.jms.MessageProducer;
import jakarta.jms.Session;
import jakarta.jms.TextMessage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.apache.activemq.ActiveMQSslConnectionFactory;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.MountableFile;

/**
 * The whole message-source contract over {@code ssl://} with a client certificate required (ActiveMQ Classic 6.1 in Docker,
 * certificates generated by the test), then the failure cases: an untrusted CA, no client certificate, a wrong host name, bad
 * settings. Skipped where Docker or the image is not reachable.
 */
class ActiveMqTlsTest extends MessageSourceContract {

    static final String IMAGE = "apache/activemq-classic:6.1.7";
    static GenericContainer<?> broker;
    static Path dir;
    static TestPki.Identity ca;
    static Map<String, String> tlsSettings;

    @BeforeAll
    static void startBroker() throws Exception {
        boolean docker;
        try {
            docker = org.testcontainers.DockerClientFactory.instance().isDockerAvailable();
            if (docker) {
                org.testcontainers.DockerClientFactory.lazyClient().inspectImageCmd(IMAGE).exec();
            }
        } catch (RuntimeException e) {
            docker = false;
        }
        org.junit.jupiter.api.Assumptions.assumeTrue(docker, "Docker and the image " + IMAGE + " are needed");
        dir = Files.createTempDirectory("amq-tls");
        ca = TestPki.ca("test-ca");
        TestPki.issue(ca, "broker", "RSA", 30).writeKeystore(dir.resolve("broker.p12"), "PKCS12", "changeit", "broker", "changeit");
        TestPki.writeTruststore(dir.resolve("truststore.p12"), "PKCS12", "changeit", ca.cert());
        TestPki.Identity client = TestPki.issue(ca, "drishti", "EC", 30);
        ca.writeCertPem(dir.resolve("ca.pem"));
        client.writeCertPem(dir.resolve("client.pem"));
        client.writeKeyPem(dir.resolve("client.key"), TestPki.KeyFormat.SEC1_EC, null);
        Files.writeString(dir.resolve("activemq.xml"), """
                <beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                       http://activemq.apache.org/schema/core http://activemq.apache.org/schema/core/activemq-core.xsd">
                  <broker xmlns="http://activemq.apache.org/schema/core" brokerName="localhost" dataDirectory="${activemq.data}" useJmx="false">
                    <persistenceAdapter><kahaDB directory="${activemq.data}/kahadb"/></persistenceAdapter>
                    <sslContext>
                      <sslContext keyStore="file:/opt/apache-activemq/conf/broker.p12" keyStoreType="PKCS12" keyStorePassword="changeit"
                                  trustStore="file:/opt/apache-activemq/conf/truststore.p12" trustStoreType="PKCS12" trustStorePassword="changeit"/>
                    </sslContext>
                    <transportConnectors>
                      <transportConnector name="mutual" uri="ssl://0.0.0.0:61617?needClientAuth=true"/>
                      <transportConnector name="server-only" uri="ssl://0.0.0.0:61618"/>
                    </transportConnectors>
                  </broker>
                </beans>
                """);
        GenericContainer<?> c = new GenericContainer<>(IMAGE).withExposedPorts(61617, 61618).waitingFor(Wait.forListeningPort());
        for (String f : new String[] {"activemq.xml", "broker.p12", "truststore.p12"}) {
            c.withCopyFileToContainer(MountableFile.forHostPath(dir.resolve(f), 0644), "/opt/apache-activemq/conf/" + f);
        }
        broker = c;
        broker.start();
        tlsSettings = new HashMap<>();
        tlsSettings.put("tls.ca-file", dir.resolve("ca.pem").toString());
        tlsSettings.put("tls.cert-file", dir.resolve("client.pem").toString());
        tlsSettings.put("tls.key-file", dir.resolve("client.key").toString());
    }

    @AfterAll
    static void stopBroker() throws Exception {
        if (broker != null) {
            broker.stop();
        }
        if (dir != null) {
            try (var files = Files.walk(dir)) {
                files.sorted(java.util.Comparator.reverseOrder()).forEach(p -> p.toFile().delete());
            }
        }
    }

    static String url(int port, String host) {
        return "ssl://" + host + ":" + broker.getMappedPort(port);
    }

    @Override
    protected SourcePlugin start(Path state) throws Exception {
        Map<String, String> s = new HashMap<>(shared(state));
        s.putAll(tlsSettings);
        s.put("broker-url", "failover:(" + url(61617, broker.getHost()) + ")?initialReconnectDelay=200&maxReconnectDelay=2000");
        s.put("destinations", "queue:" + TRADES + ",queue:" + ENTITIES);
        ActiveMqSourcePlugin p = new ActiveMqSourcePlugin();
        p.start(DatedSourceContract.context(s));
        return p;
    }

    @Override
    protected void send(String destination, String id, String body, boolean deleted) throws Exception {
        TlsMaterial m = TlsContexts.build(TlsSettings.from(tlsSettings));
        ActiveMQSslConnectionFactory f = new ActiveMQSslConnectionFactory(url(61617, broker.getHost()));
        f.setKeyAndTrustManagers(m.keyManagers(), m.trustManagers(), new SecureRandom());
        try (Connection c = f.createConnection();
             Session s = c.createSession(false, Session.AUTO_ACKNOWLEDGE);
             MessageProducer p = s.createProducer(s.createQueue(destination))) {
            TextMessage msg = s.createTextMessage(body);
            if (id != null) {
                msg.setStringProperty("id", id);
            }
            if (deleted) {
                msg.setStringProperty("deleted", "true");
            }
            p.send(msg);
        }
    }

    // ---------------------------------------------------------------- failures

    /** Starts a plugin straight on an ssl:// URL (no failover, so the first failure is the health text) and returns its health. */
    String healthWith(Map<String, String> tls, int port, String host) throws Exception {
        Map<String, String> s = new HashMap<>(shared(Files.createTempDirectory(dir, "state")));
        s.putAll(tls);
        s.put("broker-url", url(port, host));
        s.put("destinations", "queue:" + TRADES);
        ActiveMqSourcePlugin p = new ActiveMqSourcePlugin();
        p.start(DatedSourceContract.context(s));
        try {
            // sample for a few seconds: UP as soon as it is, otherwise every distinct reason it gave
            java.util.Set<String> seen = new java.util.LinkedHashSet<>();
            long until = System.nanoTime() + TimeUnit.SECONDS.toNanos(8);
            while (System.nanoTime() < until) {
                String h = p.health();
                if (h.startsWith("UP")) {
                    return h;
                }
                if (!h.startsWith("DOWN: connecting") && !h.startsWith("DOWN: not started")) {
                    seen.add(h);
                }
                Thread.sleep(100);
            }
            return seen.isEmpty() ? "DOWN: no reason given" : String.join(" | ", seen);
        } finally {
            p.close();
        }
    }

    @Test
    void theMutualListenerWorksOverPkcs12AndJksStoresToo() throws Exception {
        TestPki.Identity c2 = TestPki.issue(ca, "drishti-p12", "RSA", 30);
        c2.writeKeystore(dir.resolve("c2.p12"), "PKCS12", "pw", "k", "pw");
        TestPki.writeTruststore(dir.resolve("t2.jks"), "JKS", "pw", ca.cert());
        Map<String, String> stores = Map.of("tls.keystore", dir.resolve("c2.p12").toString(), "tls.keystore-password", "pw",
                "tls.truststore", dir.resolve("t2.jks").toString(), "tls.truststore-password", "pw");
        assertThat(healthWith(stores, 61617, broker.getHost())).startsWith("UP");
    }

    @Test
    void aClientWithoutACertificateIsRefusedByTheMutualListener() throws Exception {
        String h = healthWith(Map.of("tls.ca-file", dir.resolve("ca.pem").toString()), 61617, broker.getHost());
        assertThat(h).startsWith("DOWN");
    }

    @Test
    void theServerOnlyListenerNeedsNoClientCertificate() throws Exception {
        assertThat(healthWith(Map.of("tls.ca-file", dir.resolve("ca.pem").toString()), 61618, broker.getHost())).startsWith("UP");
    }

    @Test
    void aBrokerWhoseCaIsNotTrustedIsRefusedWithThePkixReason() throws Exception {
        TestPki.ca("rogue").writeCertPem(dir.resolve("rogue.pem"));
        String h = healthWith(Map.of("tls.ca-file", dir.resolve("rogue.pem").toString()), 61618, broker.getHost());
        assertThat(h).startsWith("DOWN").contains("PKIX path building failed");
    }

    @Test
    void aWrongHostNameIsRefusedUnlessVerificationIsSwitchedOff() throws Exception {
        Map<String, String> strict = Map.of("tls.ca-file", dir.resolve("ca.pem").toString());
        String refused = healthWith(strict, 61618, "127.0.0.2");           // reaches the broker, but the certificate carries no such address
        assertThat(refused).startsWith("DOWN").containsAnyOf("No subject alternative", "certificate_unknown", "hostname", "host name");
        Map<String, String> lax = Map.of("tls.ca-file", dir.resolve("ca.pem").toString(), "tls.verify-hostname", "false");
        assertThat(healthWith(lax, 61618, "127.0.0.2")).startsWith("UP");
    }

    @Test
    void settingsThatDoNotFitAreRefusedAtStart() throws Exception {
        Map<String, String> s = new HashMap<>(shared(Files.createTempDirectory(dir, "state2")));
        s.put("broker-url", "tcp://localhost:61616");
        s.put("tls.enabled", "true");
        s.put("destinations", "queue:x");
        assertThatThrownBy(() -> new ActiveMqSourcePlugin().start(DatedSourceContract.context(s))).isInstanceOf(TlsException.class)
                .hasMessageContaining("no ssl:// endpoint");
        Map<String, String> bad = new HashMap<>(shared(Files.createTempDirectory(dir, "state3")));
        bad.put("broker-url", url(61618, broker.getHost()));
        bad.put("tls.ca-file", dir.resolve("missing.pem").toString());
        bad.put("destinations", "queue:x");
        assertThatThrownBy(() -> new ActiveMqSourcePlugin().start(DatedSourceContract.context(bad))).isInstanceOf(TlsException.class)
                .hasMessageContaining("missing.pem").hasMessageContaining("file not found");
    }

    @Test
    void hostnameVerificationOffIsAddedToEverySslEndpoint() {
        assertThat(ActiveMqSourcePlugin.withHostnameCheck("failover:(ssl://a:61617,ssl://b:61617?x=1)?randomize=false", false))
                .isEqualTo("failover:(ssl://a:61617?socket.verifyHostName=false,ssl://b:61617?x=1&socket.verifyHostName=false)?randomize=false");
        assertThat(ActiveMqSourcePlugin.withHostnameCheck("ssl://a:61617", true)).isEqualTo("ssl://a:61617");
    }
}
